//! ML-DSA signatures in the libcrux provider: round-trip within libcrux and
//! cross-provider with RustCrypto (same seed-based private-key wire format).
#![cfg(feature = "draft-ietf-mls-pq-ciphersuites")]

use openmls_libcrux_crypto::CryptoProvider as Libcrux;
use openmls_rust_crypto::RustCrypto;
use openmls_traits::{crypto::OpenMlsCrypto, types::SignatureScheme};

const SCHEMES: [SignatureScheme; 3] = [
    SignatureScheme::MLDSA44,
    SignatureScheme::MLDSA65,
    SignatureScheme::MLDSA87,
];

fn providers() -> (Libcrux, RustCrypto) {
    (Libcrux::new().unwrap(), RustCrypto::default())
}

#[test]
fn round_trip() {
    let (libcrux, _) = providers();
    for scheme in SCHEMES {
        let (sk, pk) = libcrux.signature_key_gen(scheme).unwrap();
        assert_eq!(sk.len(), 32, "{scheme:?}: private key is the 32-byte seed");
        let sig = libcrux.sign(scheme, b"hello", &sk).unwrap();
        libcrux
            .verify_signature(scheme, b"hello", &pk, &sig)
            .unwrap();
        assert!(libcrux
            .verify_signature(scheme, b"hellp", &pk, &sig)
            .is_err());
        // Wrong scheme for the key material must not verify.
        let other = SCHEMES.iter().find(|s| **s != scheme).unwrap();
        assert!(libcrux
            .verify_signature(*other, b"hello", &pk, &sig)
            .is_err());
    }
}

#[test]
fn cross_provider() {
    let (libcrux, rust_crypto) = providers();
    for scheme in SCHEMES {
        // Keys generated by one provider are usable by the other: signing with
        // the other provider's seed under its public key only works if both
        // derive the same key pair from the seed.
        let (sk_l, pk_l) = libcrux.signature_key_gen(scheme).unwrap();
        let (sk_r, pk_r) = rust_crypto.signature_key_gen(scheme).unwrap();
        assert_eq!(pk_l.len(), pk_r.len(), "{scheme:?}: public key size");

        // libcrux signs, RustCrypto verifies (both key origins).
        for (sk, pk) in [(&sk_l, &pk_l), (&sk_r, &pk_r)] {
            let sig = libcrux.sign(scheme, b"msg", sk).unwrap();
            rust_crypto
                .verify_signature(scheme, b"msg", pk, &sig)
                .unwrap_or_else(|e| panic!("{scheme:?}: RustCrypto rejected libcrux sig: {e:?}"));
        }
        // RustCrypto signs, libcrux verifies (both key origins).
        for (sk, pk) in [(&sk_l, &pk_l), (&sk_r, &pk_r)] {
            let sig = rust_crypto.sign(scheme, b"msg", sk).unwrap();
            libcrux
                .verify_signature(scheme, b"msg", pk, &sig)
                .unwrap_or_else(|e| panic!("{scheme:?}: libcrux rejected RustCrypto sig: {e:?}"));
        }
    }
}
