//! In-memory storage providers for the migration compat tests.
//!
//! [`StorageProviderState`] holds the group state as a set of in-memory
//! `Table`s (`HashMap<Vec<u8>, Vec<u8>>`, keyed and valued by serialized bytes),
//! shared behind an `Arc<Mutex<_>>` so a provider can be handed out repeatedly for
//! the same underlying state. Two thin views wrap it, one per serde codec:
//!
//! - [`PostcardProvider`] — a **non-self-describing** (binary) codec, standing in
//!   for a previous version's on-disk format.
//! - [`SerdeJsonProvider`] — a **self-describing** codec, used as the migration
//!   bridge format and the current version's store.
//!
//! Each is paired with a libcrux crypto/rand provider into a full
//! `OpenMlsProvider` (the `*OpenMlsProvider` structs) so real group operations can
//! run against it — in both the current-version and previous-version (`_compat`)
//! flavours, since a migration test drives both lines.
//!
//! Each backing view implements the `StorageProvider` trait for every
//! (codec × trait-version) combination it needs:
//!
//! | module              | codec        | `StorageProvider` version         |
//! |---------------------|--------------|-----------------------------------|
//! | `serde_json_current`| `serde_json` | current crate                     |
//! | `serde_json_compat` | `serde_json` | previous-version crate (`_compat`)|
//! | `postcard_current`  | `postcard`   | current crate                     |
//! | `postcard_compat`   | `postcard`   | previous-version crate (`_compat`)|
//!
//! The trait methods are generated by the `impl_storage_provider_*!` macros and
//! the free `Table` read/write helpers by the `storage_helpers!` macro, so each
//! module only supplies its codec, error type, and trait imports.

#![allow(dead_code, unused)]

use std::{
    collections::HashMap,
    sync::{Arc, Mutex},
};

type Table = HashMap<Vec<u8>, Vec<u8>>;

#[derive(Default)]
struct Data {
    // group state
    join_config: Table,
    own_leaf_nodes: Table,
    queued_proposals: Table,
    proposal_queue_refs: Table,
    tree: Table,
    interim_transcript_hash: Table,
    group_context: Table,
    confirmation_tag: Table,
    group_state: Table,
    message_secrets: Table,
    resumption_psk_store: Table,
    own_leaf_index: Table,
    group_epoch_secrets: Table,
    encryption_epoch_key_pairs: Table,

    // crypto objects
    signature_key_pairs: Table,
    encryption_key_pairs: Table,
    key_packages: Table,
    psks: Table,

    // extensions-draft
    application_export_tree: Table,

    // virtual-clients-draft
    vc_emulation_epoch_state: Table,
    vc_emulation_bindings: Table,
    registered_vc_emulation_epoch: Table,
    vc_operation_tree: Table,
    retained_key_package_material: Table,
    retained_key_package_epoch: Table,
}

#[derive(Default)]
pub struct StorageProviderState(Arc<Mutex<Data>>);

impl StorageProviderState {
    pub fn as_postcard_provider(&self) -> PostcardProvider<'_> {
        PostcardProvider(self)
    }
    pub fn as_serde_json_provider(&self) -> SerdeJsonProvider<'_> {
        SerdeJsonProvider(self)
    }
}

// The previous-version crypto/rand provider is a local wrapper around the current
// libcrux provider (see `crate::test_crypto_provider`), aliased here to the name
// the previous-version libcrux crate used, so it drops in unchanged below.
use crate::test_crypto_provider as openmls_libcrux_crypto_compat;

#[cfg(feature = "storage_migration_0_8")]
use openmls_traits_0_5_0 as openmls_traits_compat;

#[cfg(feature = "storage_migration_0_7")]
use openmls_traits_0_4_1 as openmls_traits_compat;

/// A full [`OpenMlsProvider`](openmls_traits_compat::OpenMlsProvider) for the
/// `0.8.1` API that pairs a [`PostcardProvider`] (storage) with a libcrux-backed
/// crypto/rand provider. This is what group operations run against while the
/// group state is set up before a migration.
pub struct PostcardOpenMlsProvider<'a> {
    storage: &'a PostcardProvider<'a>,
    crypto: openmls_libcrux_crypto_compat::CryptoProvider,
}

pub struct PostcardProvider<'a>(&'a StorageProviderState);

impl<'a> PostcardProvider<'a> {
    pub fn as_openmls_provider(&'a self) -> PostcardOpenMlsProvider<'a> {
        PostcardOpenMlsProvider {
            storage: self,
            crypto: openmls_libcrux_crypto_compat::CryptoProvider::new()
                .expect("failed to initialize libcrux crypto provider"),
        }
    }
}
pub struct SerdeJsonProvider<'a>(&'a StorageProviderState);

/// A full [`OpenMlsProvider`](openmls_traits::OpenMlsProvider) for the *current*
/// API that pairs a [`SerdeJsonProvider`] (storage) with a libcrux-backed
/// crypto/rand provider. This is used to drive a migrated group through real
/// operations.
pub struct SerdeJsonOpenMlsProvider<'a> {
    storage: &'a SerdeJsonProvider<'a>,
    crypto: openmls_libcrux_crypto_current::CryptoProvider,
}

/// A full [`OpenMlsProvider`](openmls_traits_compat::OpenMlsProvider) for the *current*
/// API that pairs a [`SerdeJsonProvider`] (storage) with a libcrux-backed
/// crypto/rand provider. This is used to drive a migrated group through real
/// operations.
pub struct SerdeJsonOpenMlsProviderCompat<'a> {
    storage: &'a SerdeJsonProvider<'a>,
    crypto: openmls_libcrux_crypto_compat::CryptoProvider,
}

impl<'a> SerdeJsonProvider<'a> {
    pub fn as_openmls_provider(&'a self) -> SerdeJsonOpenMlsProvider<'a> {
        SerdeJsonOpenMlsProvider {
            storage: self,
            crypto: openmls_libcrux_crypto_current::CryptoProvider::new()
                .expect("failed to initialize libcrux crypto provider"),
        }
    }
}

impl<'a> SerdeJsonProvider<'a> {
    pub fn as_openmls_provider_compat(&'a self) -> SerdeJsonOpenMlsProviderCompat<'a> {
        SerdeJsonOpenMlsProviderCompat {
            storage: self,
            crypto: openmls_libcrux_crypto_compat::CryptoProvider::new()
                .expect("failed to initialize libcrux crypto provider"),
        }
    }
}

macro_rules! impl_storage_provider_basic {
    ($version:expr, $read_fn:ident, $write_fn:ident, $delete_fn:ident, $error:ty) => {
        //
        //    ---   setters/writers/enqueuers for group state  ---
        //

        /// Writes the MlsGroupJoinConfig for the group with given id to storage
        fn write_mls_join_config<
            GroupId: traits::GroupId<$version>,
            MlsGroupJoinConfig: traits::MlsGroupJoinConfig<$version>,
        >(
            &self,
            group_id: &GroupId,
            config: &MlsGroupJoinConfig,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, config, &mut data.join_config)
        }

        /// Adds an own leaf node for the group with given id to storage
        fn append_own_leaf_node<
            GroupId: traits::GroupId<$version>,
            LeafNode: traits::LeafNode<$version>,
        >(
            &self,
            group_id: &GroupId,
            leaf_node: &LeafNode,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            append(group_id, leaf_node, &mut data.own_leaf_nodes)
        }

        /// Enqueue a proposal.
        fn queue_proposal<
            GroupId: traits::GroupId<$version>,
            ProposalRef: traits::ProposalRef<$version>,
            QueuedProposal: traits::QueuedProposal<$version>,
        >(
            &self,
            group_id: &GroupId,
            proposal_ref: &ProposalRef,
            proposal: &QueuedProposal,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            let data = &mut *data;
            store_proposal(
                group_id,
                proposal_ref,
                proposal,
                &mut data.queued_proposals,
                &mut data.proposal_queue_refs,
            )
        }

        /// Write the TreeSync tree.
        fn write_tree<GroupId: traits::GroupId<$version>, TreeSync: traits::TreeSync<$version>>(
            &self,
            group_id: &GroupId,
            tree: &TreeSync,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, tree, &mut data.tree)
        }

        /// Write the interim transcript hash.
        fn write_interim_transcript_hash<
            GroupId: traits::GroupId<$version>,
            InterimTranscriptHash: traits::InterimTranscriptHash<$version>,
        >(
            &self,
            group_id: &GroupId,
            interim_transcript_hash: &InterimTranscriptHash,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(
                group_id,
                interim_transcript_hash,
                &mut data.interim_transcript_hash,
            )
        }

        /// Write the group context.
        fn write_context<
            GroupId: traits::GroupId<$version>,
            GroupContext: traits::GroupContext<$version>,
        >(
            &self,
            group_id: &GroupId,
            group_context: &GroupContext,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, group_context, &mut data.group_context)
        }

        /// Write the confirmation tag.
        fn write_confirmation_tag<
            GroupId: traits::GroupId<$version>,
            ConfirmationTag: traits::ConfirmationTag<$version>,
        >(
            &self,
            group_id: &GroupId,
            confirmation_tag: &ConfirmationTag,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, confirmation_tag, &mut data.confirmation_tag)
        }

        /// Writes the MlsGroupState for group with given id.
        fn write_group_state<
            GroupState: traits::GroupState<$version>,
            GroupId: traits::GroupId<$version>,
        >(
            &self,
            group_id: &GroupId,
            group_state: &GroupState,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, group_state, &mut data.group_state)
        }

        /// Writes the MessageSecretsStore for the group with the given id.
        fn write_message_secrets<
            GroupId: traits::GroupId<$version>,
            MessageSecrets: traits::MessageSecrets<$version>,
        >(
            &self,
            group_id: &GroupId,
            message_secrets: &MessageSecrets,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, message_secrets, &mut data.message_secrets)
        }

        /// Writes the ResumptionPskStore for the group with the given id.
        fn write_resumption_psk_store<
            GroupId: traits::GroupId<$version>,
            ResumptionPskStore: traits::ResumptionPskStore<$version>,
        >(
            &self,
            group_id: &GroupId,
            resumption_psk_store: &ResumptionPskStore,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(
                group_id,
                resumption_psk_store,
                &mut data.resumption_psk_store,
            )
        }

        /// Writes the own leaf index inside the group for the group with the given id.
        fn write_own_leaf_index<
            GroupId: traits::GroupId<$version>,
            LeafNodeIndex: traits::LeafNodeIndex<$version>,
        >(
            &self,
            group_id: &GroupId,
            own_leaf_index: &LeafNodeIndex,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, own_leaf_index, &mut data.own_leaf_index)
        }

        /// Writes the GroupEpochSecrets for the group with the given id.
        fn write_group_epoch_secrets<
            GroupId: traits::GroupId<$version>,
            GroupEpochSecrets: traits::GroupEpochSecrets<$version>,
        >(
            &self,
            group_id: &GroupId,
            group_epoch_secrets: &GroupEpochSecrets,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(group_id, group_epoch_secrets, &mut data.group_epoch_secrets)
        }

        //
        //     ---    deleters for group state    ---
        //

        /// Removes an individual proposal from the proposal queue of the group with the provided id
        fn remove_proposal<
            GroupId: traits::GroupId<$version>,
            ProposalRef: traits::ProposalRef<$version>,
        >(
            &self,
            group_id: &GroupId,
            proposal_ref: &ProposalRef,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            let data = &mut *data;
            remove_queued_proposal(
                group_id,
                proposal_ref,
                &mut data.queued_proposals,
                &mut data.proposal_queue_refs,
            )
        }

        /// Deletes own leaf nodes for the given id from storage
        fn delete_own_leaf_nodes<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.own_leaf_nodes)
        }

        /// Deletes the MlsGroupJoinConfig for the given id from storage
        fn delete_group_config<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.join_config)
        }

        /// Deletes the tree from storage
        fn delete_tree<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.tree)
        }

        /// Deletes the confirmation tag from storage
        fn delete_confirmation_tag<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.confirmation_tag)
        }

        /// Deletes the MlsGroupState for group with given id.
        fn delete_group_state<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.group_state)
        }

        /// Deletes the group context for the group with given id
        fn delete_context<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.group_context)
        }

        /// Deletes the interim transcript hash for the group with given id
        fn delete_interim_transcript_hash<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.interim_transcript_hash)
        }

        /// Deletes the MessageSecretsStore for the group with the given id.
        fn delete_message_secrets<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.message_secrets)
        }

        /// Deletes the ResumptionPskStore for the group with the given id.
        fn delete_all_resumption_psk_secrets<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.resumption_psk_store)
        }

        /// Deletes the own leaf index inside the group for the group with the given id.
        fn delete_own_leaf_index<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.own_leaf_index)
        }

        /// Deletes the GroupEpochSecrets for the group with the given id.
        fn delete_group_epoch_secrets<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(group_id, &mut data.group_epoch_secrets)
        }

        /// Clear the proposal queue for the group with the given id.
        fn clear_proposal_queue<
            GroupId: traits::GroupId<$version>,
            ProposalRef: traits::ProposalRef<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            let data = &mut *data;
            clear_proposals::<_, ProposalRef>(
                group_id,
                &mut data.queued_proposals,
                &mut data.proposal_queue_refs,
            )
        }

        //
        //    ---   deleters for crypto objects   ---
        //

        /// Delete a signature key pair based on its public key
        ///
        /// The signature key pair is not known to OpenMLS. This may be used by the
        /// application
        fn delete_signature_key_pair<SignaturePublicKey: traits::SignaturePublicKey<$version>>(
            &self,
            public_key: &SignaturePublicKey,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(public_key, &mut data.signature_key_pairs)
        }

        /// Delete an encryption key pair for a public key.
        ///
        /// This is only be used for encryption key pairs that are generated for
        /// update leaf nodes. All other encryption key pairs are stored as part
        /// of the key package or the epoch encryption key pairs.
        fn delete_encryption_key_pair<EncryptionKey: traits::EncryptionKey<$version>>(
            &self,
            public_key: &EncryptionKey,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(public_key, &mut data.encryption_key_pairs)
        }

        /// Delete a list of HPKE encryption key pairs for a given epoch.
        /// This includes the private and public keys.
        fn delete_encryption_epoch_key_pairs<
            GroupId: traits::GroupId<$version>,
            EpochKey: traits::EpochKey<$version>,
        >(
            &self,
            group_id: &GroupId,
            epoch: &EpochKey,
            leaf_index: u32,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            delete_epoch_key_pairs(
                group_id,
                epoch,
                leaf_index,
                &mut data.encryption_epoch_key_pairs,
            )
        }

        /// Delete a key package based on the hash reference.
        ///
        /// This function only deletes the key package.
        /// The corresponding encryption keys must be deleted separately.
        fn delete_key_package<KeyPackageRef: traits::HashReference<$version>>(
            &self,
            hash_ref: &KeyPackageRef,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(hash_ref, &mut data.key_packages)
        }

        /// Delete a PSK based on an identifier.
        fn delete_psk<PskKey: traits::PskId<$version>>(
            &self,
            psk_id: &PskKey,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $delete_fn(psk_id, &mut data.psks)
        }

        //
        //    ---   setters/writers/enqueuers for crypto objects  ---
        //

        /// Store a signature key.
        ///
        /// The signature key pair is not known to OpenMLS. This may be used by the
        /// application
        fn write_signature_key_pair<
            SignaturePublicKey: traits::SignaturePublicKey<$version>,
            SignatureKeyPair: traits::SignatureKeyPair<$version>,
        >(
            &self,
            public_key: &SignaturePublicKey,
            signature_key_pair: &SignatureKeyPair,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(
                public_key,
                signature_key_pair,
                &mut data.signature_key_pairs,
            )
        }

        /// Store an HPKE encryption key pair.
        /// This includes the private and public key
        ///
        /// This is only be used for encryption key pairs that are generated for
        /// update leaf nodes. All other encryption key pairs are stored as part
        /// of the key package or the epoch encryption key pairs.
        fn write_encryption_key_pair<
            EncryptionKey: traits::EncryptionKey<$version>,
            HpkeKeyPair: traits::HpkeKeyPair<$version>,
        >(
            &self,
            public_key: &EncryptionKey,
            key_pair: &HpkeKeyPair,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(public_key, key_pair, &mut data.encryption_key_pairs)
        }

        /// Store a list of HPKE encryption key pairs for a given epoch.
        /// This includes the private and public keys.
        fn write_encryption_epoch_key_pairs<
            GroupId: traits::GroupId<$version>,
            EpochKey: traits::EpochKey<$version>,
            HpkeKeyPair: traits::HpkeKeyPair<$version>,
        >(
            &self,
            group_id: &GroupId,
            epoch: &EpochKey,
            leaf_index: u32,
            key_pairs: &[HpkeKeyPair],
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            write_epoch_key_pairs(
                group_id,
                epoch,
                leaf_index,
                key_pairs,
                &mut data.encryption_epoch_key_pairs,
            )
        }

        /// Store key packages.
        ///
        /// Store a key package. This includes the private init key.
        /// The encryption key is stored separately with `write_encryption_key_pair`.
        ///
        /// Note that it is recommended to store a list of the hash references as well
        /// in order to iterate over key packages. OpenMLS does not have a reference
        /// for them.
        // ANCHOR: write_key_package
        fn write_key_package<
            HashReference: traits::HashReference<$version>,
            KeyPackage: traits::KeyPackage<$version>,
        >(
            &self,
            hash_ref: &HashReference,
            key_package: &KeyPackage,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(hash_ref, key_package, &mut data.key_packages)
        }
        // ANCHOR_END: write_key_package

        /// Store a PSK.
        ///
        /// This stores PSKs based on the PSK id.
        ///
        /// PSKs are only read by OpenMLS. The application is responsible for managing
        /// and storing PSKs.
        fn write_psk<PskId: traits::PskId<$version>, PskBundle: traits::PskBundle<$version>>(
            &self,
            psk_id: &PskId,
            psk: &PskBundle,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            $write_fn(psk_id, psk, &mut data.psks)
        }

        //
        //    ---   getters for group state  ---
        //

        /// Returns the MlsGroupJoinConfig for the group with given id
        fn mls_group_join_config<
            GroupId: traits::GroupId<$version>,
            MlsGroupJoinConfig: traits::MlsGroupJoinConfig<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<MlsGroupJoinConfig>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.join_config)
        }

        // ANCHOR: own_leaf_nodes
        /// Returns the own leaf nodes for the group with given id
        fn own_leaf_nodes<
            GroupId: traits::GroupId<$version>,
            LeafNode: traits::LeafNode<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Vec<LeafNode>, $error> {
            let data = self.0 .0.lock().unwrap();
            read_list(group_id, &data.own_leaf_nodes)
        }
        // ANCHOR_END: own_leaf_nodes

        /// Returns references of all queued proposals for the group with group id `group_id`, or an empty vector of none are stored.
        fn queued_proposal_refs<
            GroupId: traits::GroupId<$version>,
            ProposalRef: traits::ProposalRef<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Vec<ProposalRef>, $error> {
            let data = self.0 .0.lock().unwrap();
            read_list(group_id, &data.proposal_queue_refs)
        }

        /// Returns all queued proposals for the group with group id `group_id`, or an empty vector of none are stored.
        fn queued_proposals<
            GroupId: traits::GroupId<$version>,
            ProposalRef: traits::ProposalRef<$version>,
            QueuedProposal: traits::QueuedProposal<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Vec<(ProposalRef, QueuedProposal)>, $error> {
            let data = self.0 .0.lock().unwrap();
            read_queued_proposals(group_id, &data.queued_proposals, &data.proposal_queue_refs)
        }

        /// Returns the TreeSync tree for the group with group id `group_id`.
        fn tree<GroupId: traits::GroupId<$version>, TreeSync: traits::TreeSync<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<TreeSync>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.tree)
        }

        /// Returns the group context for the group with group id `group_id`.
        fn group_context<
            GroupId: traits::GroupId<$version>,
            GroupContext: traits::GroupContext<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<GroupContext>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.group_context)
        }

        /// Returns the interim transcript hash for the group with group id `group_id`.
        fn interim_transcript_hash<
            GroupId: traits::GroupId<$version>,
            InterimTranscriptHash: traits::InterimTranscriptHash<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<InterimTranscriptHash>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.interim_transcript_hash)
        }

        /// Returns the confirmation tag for the group with group id `group_id`.
        fn confirmation_tag<
            GroupId: traits::GroupId<$version>,
            ConfirmationTag: traits::ConfirmationTag<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<ConfirmationTag>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.confirmation_tag)
        }

        /// Returns the group state for the group with group id `group_id`.
        fn group_state<
            GroupState: traits::GroupState<$version>,
            GroupId: traits::GroupId<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<GroupState>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.group_state)
        }

        /// Returns the MessageSecretsStore for the group with the given id.
        fn message_secrets<
            GroupId: traits::GroupId<$version>,
            MessageSecrets: traits::MessageSecrets<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<MessageSecrets>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.message_secrets)
        }

        /// Returns the ResumptionPskStore for the group with the given id.
        ///
        /// Returning `None` here is considered an error because the store is needed
        /// by OpenMLS when loading a group.
        fn resumption_psk_store<
            GroupId: traits::GroupId<$version>,
            ResumptionPskStore: traits::ResumptionPskStore<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<ResumptionPskStore>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.resumption_psk_store)
        }

        /// Returns the own leaf index inside the group for the group with the given id.
        fn own_leaf_index<
            GroupId: traits::GroupId<$version>,
            LeafNodeIndex: traits::LeafNodeIndex<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<LeafNodeIndex>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.own_leaf_index)
        }

        /// Returns the GroupEpochSecrets for the group with the given id.
        fn group_epoch_secrets<
            GroupId: traits::GroupId<$version>,
            GroupEpochSecrets: traits::GroupEpochSecrets<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<GroupEpochSecrets>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(group_id, &data.group_epoch_secrets)
        }

        //
        //    ---   getter for crypto objects  ---
        //

        /// Get a signature key based on the public key.
        ///
        /// The signature key pair is not known to OpenMLS. This may be used by the
        /// application
        fn signature_key_pair<
            SignaturePublicKey: traits::SignaturePublicKey<$version>,
            SignatureKeyPair: traits::SignatureKeyPair<$version>,
        >(
            &self,
            public_key: &SignaturePublicKey,
        ) -> Result<Option<SignatureKeyPair>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(public_key, &data.signature_key_pairs)
        }

        /// Get an HPKE encryption key pair based on the public key.
        ///
        /// This is only be used for encryption key pairs that are generated for
        /// update leaf nodes. All other encryption key pairs are stored as part
        /// of the key package or the epoch encryption key pairs.
        fn encryption_key_pair<
            HpkeKeyPair: traits::HpkeKeyPair<$version>,
            EncryptionKey: traits::EncryptionKey<$version>,
        >(
            &self,
            public_key: &EncryptionKey,
        ) -> Result<Option<HpkeKeyPair>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(public_key, &data.encryption_key_pairs)
        }

        /// Get a list of HPKE encryption key pairs for a given epoch.
        /// This includes the private and public keys.
        fn encryption_epoch_key_pairs<
            GroupId: traits::GroupId<$version>,
            EpochKey: traits::EpochKey<$version>,
            HpkeKeyPair: traits::HpkeKeyPair<$version>,
        >(
            &self,
            group_id: &GroupId,
            epoch: &EpochKey,
            leaf_index: u32,
        ) -> Result<Vec<HpkeKeyPair>, $error> {
            let data = self.0 .0.lock().unwrap();
            read_epoch_key_pairs(
                group_id,
                epoch,
                leaf_index,
                &data.encryption_epoch_key_pairs,
            )
        }

        /// Get a key package based on its hash reference.
        fn key_package<
            KeyPackageRef: traits::HashReference<$version>,
            KeyPackage: traits::KeyPackage<$version>,
        >(
            &self,
            hash_ref: &KeyPackageRef,
        ) -> Result<Option<KeyPackage>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(hash_ref, &data.key_packages)
        }

        /// Get a PSK based on the PSK identifier.
        fn psk<PskBundle: traits::PskBundle<$version>, PskId: traits::PskId<$version>>(
            &self,
            psk_id: &PskId,
        ) -> Result<Option<PskBundle>, $error> {
            let data = self.0 .0.lock().unwrap();
            $read_fn(psk_id, &data.psks)
        }
    };
}

// `$feat` gates the extensions-draft methods on the feature that turns the draft
// on for *this* line: `extensions-draft-current` for the current-version impls,
// `extensions-draft-compat` for the previous-version ones. The methods must exist
// exactly when that line's `openmls_traits` has them, which is what enables a
// migration across a feature-flag toggle (source without, target with).
macro_rules! impl_storage_provider_extensions_draft {
    ($version:expr, $error:ty, $feat:literal) => {
        /// Write the ApplicationExportTree for the group with the given id.
        #[cfg(feature = $feat)]
        fn write_application_export_tree<
            GroupId: traits::GroupId<$version>,
            ApplicationExportTree: traits::ApplicationExportTree<$version>,
        >(
            &self,
            group_id: &GroupId,
            application_export_tree: &ApplicationExportTree,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            write(
                group_id,
                application_export_tree,
                &mut data.application_export_tree,
            )
        }
        #[cfg(feature = $feat)]
        /// Get the application export tree for the group with the given id.
        fn application_export_tree<
            GroupId: traits::GroupId<$version>,
            ApplicationExportTree: traits::ApplicationExportTree<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<ApplicationExportTree>, $error> {
            let data = self.0 .0.lock().unwrap();
            read(group_id, &data.application_export_tree)
        }

        /// Delete the application export tree for the group with the given id.
        #[cfg(feature = $feat)]
        fn delete_application_export_tree<
            GroupId: traits::GroupId<$version>,
            ApplicationExportTree: traits::ApplicationExportTree<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            delete(group_id, &mut data.application_export_tree)
        }
    };
}

macro_rules! impl_storage_provider_virtual_clients_draft {
    ($version:expr, $error:ty) => {
        #[cfg(feature = "virtual-clients-draft")]
        fn vc_emulation_epoch_state<
            EpochId: traits::VcEpochId<$version>,
            VcEmulationEpochState: traits::VcEmulationEpochState<$version>,
        >(
            &self,
            epoch_id: &EpochId,
        ) -> Result<Option<VcEmulationEpochState>, $error> {
            let data = self.0 .0.lock().unwrap();
            read(epoch_id, &data.vc_emulation_epoch_state)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn vc_emulation_bindings<
            GroupId: traits::GroupId<$version>,
            VcEmulationBindings: traits::VcEmulationBindings<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<VcEmulationBindings>, $error> {
            let data = self.0 .0.lock().unwrap();
            read(group_id, &data.vc_emulation_bindings)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn registered_vc_emulation_epoch<
            GroupId: traits::GroupId<$version>,
            RegisteredVcEmulationEpoch: traits::RegisteredVcEmulationEpoch<$version>,
        >(
            &self,
            group_id: &GroupId,
        ) -> Result<Option<RegisteredVcEmulationEpoch>, $error> {
            let data = self.0 .0.lock().unwrap();
            read(group_id, &data.registered_vc_emulation_epoch)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn vc_operation_tree<
            EpochId: traits::VcEpochId<$version>,
            VcOperationTree: traits::VcOperationTree<$version>,
        >(
            &self,
            epoch_id: &EpochId,
        ) -> Result<Option<VcOperationTree>, $error> {
            let data = self.0 .0.lock().unwrap();
            read(epoch_id, &data.vc_operation_tree)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn retained_key_package_material<
            KeyPackageRef: traits::HashReference<$version>,
            RetainedKeyPackageMaterial: traits::RetainedKeyPackageMaterial<$version>,
        >(
            &self,
            hash_ref: &KeyPackageRef,
        ) -> Result<Option<RetainedKeyPackageMaterial>, $error> {
            let data = self.0 .0.lock().unwrap();
            read(hash_ref, &data.retained_key_package_material)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn has_retained_key_package_material_for_epoch<EpochId: traits::VcEpochId<$version>>(
            &self,
            epoch_id: &EpochId,
        ) -> Result<bool, $error> {
            let data = self.0 .0.lock().unwrap();
            epoch_is_referenced(epoch_id, &data.retained_key_package_epoch)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn write_vc_emulation_epoch_state<
            EpochId: traits::VcEpochId<$version>,
            VcEmulationEpochState: traits::VcEmulationEpochState<$version>,
        >(
            &self,
            epoch_id: &EpochId,
            vc_emulation_epoch_state: &VcEmulationEpochState,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            write(
                epoch_id,
                vc_emulation_epoch_state,
                &mut data.vc_emulation_epoch_state,
            )
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn write_vc_emulation_bindings<
            GroupId: traits::GroupId<$version>,
            VcEmulationBindings: traits::VcEmulationBindings<$version>,
        >(
            &self,
            group_id: &GroupId,
            bindings: &VcEmulationBindings,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            write(group_id, bindings, &mut data.vc_emulation_bindings)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn write_registered_vc_emulation_epoch<
            GroupId: traits::GroupId<$version>,
            RegisteredVcEmulationEpoch: traits::RegisteredVcEmulationEpoch<$version>,
        >(
            &self,
            group_id: &GroupId,
            registered: &RegisteredVcEmulationEpoch,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            write(
                group_id,
                registered,
                &mut data.registered_vc_emulation_epoch,
            )
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn write_vc_operation_tree<
            EpochId: traits::VcEpochId<$version>,
            VcOperationTree: traits::VcOperationTree<$version>,
        >(
            &self,
            epoch_id: &EpochId,
            vc_operation_tree: &VcOperationTree,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            write(epoch_id, vc_operation_tree, &mut data.vc_operation_tree)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn write_retained_key_package_material_batch<
            EpochId: traits::VcEpochId<$version>,
            VcOperationTree: traits::VcOperationTree<$version>,
            KeyPackageRef: traits::HashReference<$version>,
            RetainedKeyPackageMaterial: traits::RetainedKeyPackageMaterial<$version>,
        >(
            &self,
            epoch_id: &EpochId,
            operation_tree: &VcOperationTree,
            materials: &[(KeyPackageRef, RetainedKeyPackageMaterial)],
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            let Data {
                vc_operation_tree,
                retained_key_package_material,
                retained_key_package_epoch,
                ..
            } = &mut *data;
            write_retained_batch(
                epoch_id,
                operation_tree,
                materials,
                vc_operation_tree,
                retained_key_package_material,
                retained_key_package_epoch,
            )
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn delete_vc_emulation_state_if_unreferenced<EpochId: traits::VcEpochId<$version>>(
            &self,
            epoch_id: &EpochId,
        ) -> Result<bool, $error> {
            let mut data = self.0 .0.lock().unwrap();
            let Data {
                vc_emulation_epoch_state,
                vc_operation_tree,
                retained_key_package_epoch,
                ..
            } = &mut *data;
            delete_vc_state_if_unreferenced(
                epoch_id,
                vc_emulation_epoch_state,
                vc_operation_tree,
                retained_key_package_epoch,
            )
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn delete_vc_emulation_bindings<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            delete(group_id, &mut data.vc_emulation_bindings)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn delete_registered_vc_emulation_epoch<GroupId: traits::GroupId<$version>>(
            &self,
            group_id: &GroupId,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            delete(group_id, &mut data.registered_vc_emulation_epoch)
        }

        #[cfg(feature = "virtual-clients-draft")]
        fn delete_retained_key_package_material<KeyPackageRef: traits::HashReference<$version>>(
            &self,
            hash_ref: &KeyPackageRef,
        ) -> Result<(), $error> {
            let mut data = self.0 .0.lock().unwrap();
            delete(hash_ref, &mut data.retained_key_package_material)?;
            delete(hash_ref, &mut data.retained_key_package_epoch)
        }
    };
}

/// Generates the helper functions each storage-provider module uses to read
/// and write the in-memory `Table`s. The four modules below differ only in the
/// serde codec (`serde_json` vs `postcard`), its error type, and which trait
/// crate/version (`CURRENT_VERSION` from the current or the previous line) the
/// `Key`/`Entity` bounds come from — so the bodies are generated from this one
/// definition. Each module `use`s the matching `Key`/`Entity`/`traits`/`Table`
/// before invoking it. The `virtual-clients-draft` helpers are always generated
/// but unused where the corresponding `StorageProvider` impl does not include the
/// vc-draft methods (allowed by the crate-level `#![allow(dead_code)]`).
macro_rules! storage_helpers {
    ($version:expr, $err:ty, $ser:path, $de:path) => {
        fn write<K: Key<$version>, E: Entity<$version>>(
            key: &K,
            value: &E,
            data: &mut Table,
        ) -> Result<(), $err> {
            let key = $ser(key)?;
            let value = $ser(value)?;
            let _ = data.insert(key, value);

            Ok(())
        }

        fn read<K: Key<$version>, E: Entity<$version>>(
            key: &K,
            data: &Table,
        ) -> Result<Option<E>, $err> {
            let key = $ser(key)?;

            if let Some(data) = data.get(&key) {
                let value: E = $de(data)?;

                Ok(Some(value))
            } else {
                Ok(None)
            }
        }

        fn delete<K: Key<$version>>(key: &K, data: &mut Table) -> Result<(), $err> {
            let key = $ser(key)?;

            let _ = data.remove(&key);

            Ok(())
        }

        /// Appends a value to the list stored under `key`.
        fn append<K: Key<$version>, E: Entity<$version>>(
            key: &K,
            value: &E,
            data: &mut Table,
        ) -> Result<(), $err> {
            let key = $ser(key)?;
            let mut list: Vec<Vec<u8>> = match data.get(&key) {
                Some(bytes) => $de(bytes)?,
                None => Vec::new(),
            };
            list.push($ser(value)?);
            let _ = data.insert(key, $ser(&list)?);

            Ok(())
        }

        /// Reads the list of values stored under `key`, or an empty vector if none.
        fn read_list<K: Key<$version>, E: Entity<$version>>(
            key: &K,
            data: &Table,
        ) -> Result<Vec<E>, $err> {
            let key = $ser(key)?;
            let list: Vec<Vec<u8>> = match data.get(&key) {
                Some(bytes) => $de(bytes)?,
                None => return Ok(Vec::new()),
            };

            list.iter().map(|bytes| $de(bytes)).collect()
        }

        /// Stores a proposal keyed by `(group_id, proposal_ref)` and appends the
        /// reference to the per-group proposal queue.
        fn store_proposal<
            GroupId: Key<$version>,
            ProposalRef: Key<$version> + Entity<$version>,
            QueuedProposal: Entity<$version>,
        >(
            group_id: &GroupId,
            proposal_ref: &ProposalRef,
            proposal: &QueuedProposal,
            proposals: &mut Table,
            proposal_refs: &mut Table,
        ) -> Result<(), $err> {
            let proposal_key = $ser(&(group_id, proposal_ref))?;
            let _ = proposals.insert(proposal_key, $ser(proposal)?);

            let refs_key = $ser(group_id)?;
            let mut refs: Vec<Vec<u8>> = match proposal_refs.get(&refs_key) {
                Some(bytes) => $de(bytes)?,
                None => Vec::new(),
            };
            refs.push($ser(proposal_ref)?);
            let _ = proposal_refs.insert(refs_key, $ser(&refs)?);

            Ok(())
        }

        /// Reads all queued proposals (reference and proposal) for a group.
        fn read_queued_proposals<
            GroupId: Key<$version>,
            ProposalRef: Key<$version> + Entity<$version>,
            QueuedProposal: Entity<$version>,
        >(
            group_id: &GroupId,
            proposals: &Table,
            proposal_refs: &Table,
        ) -> Result<Vec<(ProposalRef, QueuedProposal)>, $err> {
            let refs_key = $ser(group_id)?;
            let refs: Vec<Vec<u8>> = match proposal_refs.get(&refs_key) {
                Some(bytes) => $de(bytes)?,
                None => return Ok(Vec::new()),
            };

            refs.iter()
                .map(|ref_bytes| {
                    let proposal_ref: ProposalRef = $de(ref_bytes)?;
                    let proposal_key = $ser(&(group_id, &proposal_ref))?;
                    let proposal_bytes = proposals.get(&proposal_key).unwrap();
                    let proposal: QueuedProposal = $de(proposal_bytes)?;
                    Ok((proposal_ref, proposal))
                })
                .collect()
        }

        /// Removes a single proposal and its reference from the queue.
        fn remove_queued_proposal<GroupId: Key<$version>, ProposalRef: Key<$version>>(
            group_id: &GroupId,
            proposal_ref: &ProposalRef,
            proposals: &mut Table,
            proposal_refs: &mut Table,
        ) -> Result<(), $err> {
            let proposal_key = $ser(&(group_id, proposal_ref))?;
            let _ = proposals.remove(&proposal_key);

            let refs_key = $ser(group_id)?;
            if let Some(bytes) = proposal_refs.get(&refs_key) {
                let mut refs: Vec<Vec<u8>> = $de(bytes)?;
                let target = $ser(proposal_ref)?;
                refs.retain(|item| item != &target);
                let _ = proposal_refs.insert(refs_key, $ser(&refs)?);
            }

            Ok(())
        }

        /// Clears all proposals and references for a group.
        fn clear_proposals<
            GroupId: Key<$version>,
            ProposalRef: Key<$version> + Entity<$version>,
        >(
            group_id: &GroupId,
            proposals: &mut Table,
            proposal_refs: &mut Table,
        ) -> Result<(), $err> {
            let refs_key = $ser(group_id)?;
            if let Some(bytes) = proposal_refs.get(&refs_key) {
                let refs: Vec<Vec<u8>> = $de(bytes)?;
                for ref_bytes in &refs {
                    let proposal_ref: ProposalRef = $de(ref_bytes)?;
                    let proposal_key = $ser(&(group_id, &proposal_ref))?;
                    let _ = proposals.remove(&proposal_key);
                }
            }
            let _ = proposal_refs.remove(&refs_key);

            Ok(())
        }

        /// Writes the HPKE key pairs for a `(group_id, epoch, leaf_index)` slot.
        fn write_epoch_key_pairs<
            GroupId: Key<$version>,
            EpochKey: Key<$version>,
            HpkeKeyPair: Entity<$version>,
        >(
            group_id: &GroupId,
            epoch: &EpochKey,
            leaf_index: u32,
            key_pairs: &[HpkeKeyPair],
            data: &mut Table,
        ) -> Result<(), $err> {
            let key = $ser(&(group_id, epoch, leaf_index))?;
            let _ = data.insert(key, $ser(key_pairs)?);

            Ok(())
        }

        /// Reads the HPKE key pairs for a `(group_id, epoch, leaf_index)` slot.
        fn read_epoch_key_pairs<
            GroupId: Key<$version>,
            EpochKey: Key<$version>,
            HpkeKeyPair: Entity<$version>,
        >(
            group_id: &GroupId,
            epoch: &EpochKey,
            leaf_index: u32,
            data: &Table,
        ) -> Result<Vec<HpkeKeyPair>, $err> {
            let key = $ser(&(group_id, epoch, leaf_index))?;
            match data.get(&key) {
                Some(bytes) => $de(bytes),
                None => Ok(Vec::new()),
            }
        }

        /// Deletes the HPKE key pairs for a `(group_id, epoch, leaf_index)` slot.
        fn delete_epoch_key_pairs<GroupId: Key<$version>, EpochKey: Key<$version>>(
            group_id: &GroupId,
            epoch: &EpochKey,
            leaf_index: u32,
            data: &mut Table,
        ) -> Result<(), $err> {
            let key = $ser(&(group_id, epoch, leaf_index))?;
            let _ = data.remove(&key);

            Ok(())
        }

        /// Whether any retained key package material still references `epoch_id`.
        #[cfg(feature = "virtual-clients-draft")]
        fn epoch_is_referenced<EpochId: Key<$version>>(
            epoch_id: &EpochId,
            epoch_tags: &Table,
        ) -> Result<bool, $err> {
            let serialized = $ser(epoch_id)?;
            Ok(epoch_tags.values().any(|value| value == &serialized))
        }

        /// Writes an advanced operation tree together with the retained key package
        /// material it produced, tagging each material with its epoch.
        #[cfg(feature = "virtual-clients-draft")]
        fn write_retained_batch<
            EpochId: Key<$version>,
            VcOperationTree: Entity<$version>,
            KeyPackageRef: Key<$version>,
            RetainedKeyPackageMaterial: Entity<$version>,
        >(
            epoch_id: &EpochId,
            operation_tree: &VcOperationTree,
            materials: &[(KeyPackageRef, RetainedKeyPackageMaterial)],
            operation_trees: &mut Table,
            material_table: &mut Table,
            epoch_tags: &mut Table,
        ) -> Result<(), $err> {
            let serialized_epoch = $ser(epoch_id)?;
            let _ = operation_trees.insert(serialized_epoch.clone(), $ser(operation_tree)?);
            for (hash_ref, material) in materials {
                let ref_key = $ser(hash_ref)?;
                let _ = material_table.insert(ref_key.clone(), $ser(material)?);
                let _ = epoch_tags.insert(ref_key, serialized_epoch.clone());
            }

            Ok(())
        }

        /// Deletes the emulation state and operation tree for `epoch_id` if no
        /// retained key package material still references it.
        #[cfg(feature = "virtual-clients-draft")]
        fn delete_vc_state_if_unreferenced<EpochId: Key<$version>>(
            epoch_id: &EpochId,
            epoch_states: &mut Table,
            operation_trees: &mut Table,
            epoch_tags: &Table,
        ) -> Result<bool, $err> {
            let serialized = $ser(epoch_id)?;
            if epoch_tags.values().any(|value| value == &serialized) {
                return Ok(false);
            }
            let _ = epoch_states.remove(&serialized);
            let _ = operation_trees.remove(&serialized);

            Ok(true)
        }
    };
}

mod serde_json_current {
    use super::{Data, SerdeJsonProvider, Table};
    use openmls_traits::storage::CURRENT_VERSION;

    use openmls_traits::storage::{traits, Entity, Key, StorageProvider};

    impl StorageProvider<CURRENT_VERSION> for SerdeJsonProvider<'_> {
        type Error = serde_json::Error;
        impl_storage_provider_basic!(CURRENT_VERSION, read, write, delete, serde_json::Error);
        impl_storage_provider_extensions_draft!(
            CURRENT_VERSION,
            serde_json::Error,
            "extensions-draft-current"
        );
        impl_storage_provider_virtual_clients_draft!(CURRENT_VERSION, serde_json::Error);
    }

    // The full current-version `OpenMlsProvider` (storage + crypto + rand) used to
    // drive a migrated group through real operations.
    impl<'a> openmls_traits::OpenMlsProvider for super::SerdeJsonOpenMlsProvider<'a> {
        type CryptoProvider = openmls_libcrux_crypto_current::CryptoProvider;
        type RandProvider = openmls_libcrux_crypto_current::CryptoProvider;
        type StorageProvider = super::SerdeJsonProvider<'a>;

        fn storage(&self) -> &Self::StorageProvider {
            self.storage
        }

        fn crypto(&self) -> &Self::CryptoProvider {
            &self.crypto
        }

        fn rand(&self) -> &Self::RandProvider {
            &self.crypto
        }
    }

    storage_helpers!(
        CURRENT_VERSION,
        serde_json::Error,
        serde_json::to_vec,
        serde_json::from_slice
    );
}

mod serde_json_compat {
    use super::{
        openmls_libcrux_crypto_compat, openmls_traits_compat, Data, SerdeJsonProvider, Table,
    };
    use openmls_traits_compat::storage::CURRENT_VERSION;

    use openmls_traits_compat::storage::{traits, Entity, Key, StorageProvider};

    impl StorageProvider<CURRENT_VERSION> for SerdeJsonProvider<'_> {
        type Error = serde_json::Error;
        impl_storage_provider_basic!(CURRENT_VERSION, read, write, delete, serde_json::Error);
        #[cfg(any(feature = "storage_migration_0_7", feature = "storage_migration_0_8"))]
        impl_storage_provider_extensions_draft!(
            CURRENT_VERSION,
            serde_json::Error,
            "extensions-draft-compat"
        );
    }

    // The full compat-version `OpenMlsProvider` (storage + crypto + rand).
    impl<'a> openmls_traits_compat::OpenMlsProvider for super::SerdeJsonOpenMlsProviderCompat<'a> {
        type CryptoProvider = openmls_libcrux_crypto_compat::CryptoProvider;
        type RandProvider = openmls_libcrux_crypto_compat::CryptoProvider;
        type StorageProvider = super::SerdeJsonProvider<'a>;

        fn storage(&self) -> &Self::StorageProvider {
            self.storage
        }

        fn crypto(&self) -> &Self::CryptoProvider {
            &self.crypto
        }

        fn rand(&self) -> &Self::RandProvider {
            &self.crypto
        }
    }

    storage_helpers!(
        CURRENT_VERSION,
        serde_json::Error,
        serde_json::to_vec,
        serde_json::from_slice
    );
}

mod postcard_current {
    use super::{Data, PostcardProvider, Table};
    use openmls_traits::storage::CURRENT_VERSION;
    use openmls_traits::storage::{traits, Entity, Key, StorageProvider};

    impl StorageProvider<CURRENT_VERSION> for PostcardProvider<'_> {
        type Error = postcard::Error;
        impl_storage_provider_basic!(CURRENT_VERSION, read, write, delete, postcard::Error);
        impl_storage_provider_extensions_draft!(
            CURRENT_VERSION,
            postcard::Error,
            "extensions-draft-current"
        );
        impl_storage_provider_virtual_clients_draft!(CURRENT_VERSION, postcard::Error);
    }

    storage_helpers!(
        CURRENT_VERSION,
        postcard::Error,
        postcard::to_allocvec,
        postcard::from_bytes
    );
}

mod postcard_compat {
    use super::{
        openmls_libcrux_crypto_compat, openmls_traits_compat, Data, PostcardProvider, Table,
    };

    use openmls_traits_compat::storage::CURRENT_VERSION;
    use openmls_traits_compat::storage::{traits, Entity, Key, StorageProvider};

    impl PostcardProvider<'_> {
        fn iter_group_ids<GroupId: traits::GroupId<CURRENT_VERSION>>(
            &self,
        ) -> Result<Vec<GroupId>, postcard::Error> {
            let mut data = self.0 .0.lock().unwrap();
            data.group_context
                .iter()
                .map(|(k, _v)| postcard::from_bytes(k))
                .collect::<Result<Vec<_>, _>>()
        }
    }

    impl StorageProvider<CURRENT_VERSION> for PostcardProvider<'_> {
        type Error = postcard::Error;
        impl_storage_provider_basic!(CURRENT_VERSION, read, write, delete, postcard::Error);
        #[cfg(any(feature = "storage_migration_0_7", feature = "storage_migration_0_8"))]
        impl_storage_provider_extensions_draft!(
            CURRENT_VERSION,
            postcard::Error,
            "extensions-draft-compat"
        );
    }

    #[cfg(any(feature = "storage_migration_0_7", feature = "storage_migration_0_8"))]
    impl<'a> openmls_traits_compat::OpenMlsProvider for super::PostcardOpenMlsProvider<'a> {
        type CryptoProvider = openmls_libcrux_crypto_compat::CryptoProvider;
        type RandProvider = openmls_libcrux_crypto_compat::CryptoProvider;
        type StorageProvider = super::PostcardProvider<'a>;

        fn storage(&self) -> &Self::StorageProvider {
            self.storage
        }

        fn crypto(&self) -> &Self::CryptoProvider {
            &self.crypto
        }

        fn rand(&self) -> &Self::RandProvider {
            &self.crypto
        }
    }

    storage_helpers!(
        CURRENT_VERSION,
        postcard::Error,
        postcard::to_allocvec,
        postcard::from_bytes
    );
}
