kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: test
  image: rust:latest
  commands:
  - apt-get update -qq --yes && apt-get install -qq --yes clang
  - git submodule update --init --recursive
  - cd openmls
  - cargo build --verbose
  - cargo build --release
  - cargo test --verbose
 
