-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: function definitions
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls

/-- [openmls::binary_tree::array_representation::treemath::MAX_TREE_SIZE]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 9:0-9:52 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MAX_TREE_SIZE
  : Result Std.U32 := do
  let i ← 1#u32 <<< 30#i32
  i - 1#u32

/-- [openmls::binary_tree::array_representation::treemath::MIN_TREE_SIZE]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 10:0-10:40 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MIN_TREE_SIZE : Std.U32 := 1#u32

/-- [openmls::binary_tree::array_representation::treemath::MAX_TREE_INDEX]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 17:0-17:46 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MAX_TREE_INDEX
  : Result Std.U32 := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  i - 1#u32

/-- [openmls::binary_tree::array_representation::treemath::MAX_LEAF]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 21:0-21:41 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MAX_LEAF : Result Std.U32 := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  i / 2#u32

/-- [openmls::binary_tree::array_representation::treemath::MAX_PARENT]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 26:0-26:37 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MAX_PARENT : Result Std.U32 := do
  let i ← binary_tree.array_representation.treemath.MAX_LEAF
  i - 1#u32

/-- [openmls::binary_tree::array_representation::treemath::MAX_LEAF_COUNT]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 31:0-31:41 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MAX_LEAF_COUNT
  : Result Std.U32 := do
  let i ← binary_tree.array_representation.treemath.MAX_LEAF
  i + 1#u32

/-- [openmls::binary_tree::array_representation::treemath::MAX_ROOT_INDEX]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 36:0-36:46 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.MAX_ROOT_INDEX
  : Result Std.U32 := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  i / 2#u32

/-- [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::clone]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 41:4-41:9
    Visibility: public -/
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCloneClone.clone
  (self : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result binary_tree.array_representation.treemath.LeafNodeIndex
  := do
  ok self

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 41:4-41:9 -/
@[reducible]
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCloneClone
  : core.clone.Clone binary_tree.array_representation.treemath.LeafNodeIndex
  := {
  clone :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::Copy for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 42:4-42:8 -/
@[reducible]
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreMarkerCopy
  : core.marker.Copy binary_tree.array_representation.treemath.LeafNodeIndex
  := {
  cloneCloneInst :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCloneClone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::StructuralPartialEq for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 43:4-43:13 -/
@[reducible]
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreMarkerStructuralPartialEq
  : core.marker.StructuralPartialEq
  binary_tree.array_representation.treemath.LeafNodeIndex := {
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::LeafNodeIndex> for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::eq]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 43:4-43:13
    Visibility: public -/
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialEqLeafNodeIndex.eq
  (self : binary_tree.array_representation.treemath.LeafNodeIndex)
  (other : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  ok (self = other)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::LeafNodeIndex> for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 43:4-43:13 -/
@[reducible]
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialEqLeafNodeIndex
  : core.cmp.PartialEq binary_tree.array_representation.treemath.LeafNodeIndex
  binary_tree.array_representation.treemath.LeafNodeIndex := {
  eq :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialEqLeafNodeIndex.eq
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Eq for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 44:4-44:6 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpEq :
  core.cmp.Eq binary_tree.array_representation.treemath.LeafNodeIndex := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialEqLeafNodeIndex
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 46:4-46:7
    Visibility: public -/
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpOrd.cmp
  (self : binary_tree.array_representation.treemath.LeafNodeIndex)
  (other : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result core.cmp.Ordering
  := do
  core.U32.Insts.CoreCmpOrd.cmp self other

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::LeafNodeIndex> for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::partial_cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 45:4-45:14
    Visibility: public -/
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialOrdLeafNodeIndex.partial_cmp
  (self : binary_tree.array_representation.treemath.LeafNodeIndex)
  (other : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result (core.option.Option core.cmp.Ordering)
  := do
  let o ←
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpOrd.cmp
      self other
  ok (core.option.Option.Some o)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::LeafNodeIndex> for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 45:4-45:14 -/
@[reducible]
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialOrdLeafNodeIndex
  : core.cmp.PartialOrd binary_tree.array_representation.treemath.LeafNodeIndex
  binary_tree.array_representation.treemath.LeafNodeIndex := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialEqLeafNodeIndex
  partial_cmp :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialOrdLeafNodeIndex.partial_cmp
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 46:4-46:7 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpOrd :
  core.cmp.Ord binary_tree.array_representation.treemath.LeafNodeIndex := {
  EqInst :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpEq
  PartialOrdInst :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialOrdLeafNodeIndex
  cmp :=
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpOrd.cmp
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::hash::Hash for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::hash]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 47:4-47:8
    Visibility: public -/
def
  binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : binary_tree.array_representation.treemath.LeafNodeIndex)
  (state : __H) :
  Result __H
  := do
  core.U32.Insts.CoreHashHash.hash corehashHasherInst self state

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::hash::Hash for openmls::binary_tree::array_representation::treemath::LeafNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 47:4-47:8 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreHashHash
  : core.hash.Hash binary_tree.array_representation.treemath.LeafNodeIndex := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreHashHash.hash
    corehashHasherInst
}

/-- [openmls::binary_tree::array_representation::treemath::_]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 48:4-48:13 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath._ : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::_#1]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 49:4-49:15 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__1 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::valid]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 67:4-69:5 -/
def binary_tree.array_representation.treemath.LeafNodeIndex.valid
  (self : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_LEAF
  ok (self <= i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::new]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 77:4-79:5
    Visibility: public -/
def binary_tree.array_representation.treemath.LeafNodeIndex.new
  (index : Std.U32) :
  Result binary_tree.array_representation.treemath.LeafNodeIndex
  := do
  ok index

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::u32]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 82:4-84:5
    Visibility: public -/
def binary_tree.array_representation.treemath.LeafNodeIndex.u32
  (self : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Std.U32
  := do
  ok self

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::usize]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 87:4-89:5
    Visibility: public -/
def binary_tree.array_representation.treemath.LeafNodeIndex.usize
  (self : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Std.Usize
  := do
  let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 self
  ok (UScalar.cast .Usize i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 94:4-96:5 -/
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index
  (self : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Std.U32
  := do
  self * 2#u32

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::from_tree_index]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 101:4-104:5 -/
def binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index
  (node_index : Std.U32) :
  Result binary_tree.array_representation.treemath.LeafNodeIndex
  := do
  let b ← core.num.U32.is_multiple_of node_index 2#u32
  massert b
  let i ← node_index / 2#u32
  ok i

/-- [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::clone]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:16-108:21
    Visibility: public -/
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCloneClone.clone
  (self : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result binary_tree.array_representation.treemath.ParentNodeIndex
  := do
  ok self

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:16-108:21 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCloneClone
  : core.clone.Clone binary_tree.array_representation.treemath.ParentNodeIndex
  := {
  clone :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::Copy for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:23-108:27 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreMarkerCopy
  : core.marker.Copy binary_tree.array_representation.treemath.ParentNodeIndex
  := {
  cloneCloneInst :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCloneClone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::StructuralPartialEq for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:29-108:38 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreMarkerStructuralPartialEq
  : core.marker.StructuralPartialEq
  binary_tree.array_representation.treemath.ParentNodeIndex := {
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::ParentNodeIndex> for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::eq]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:29-108:38
    Visibility: public -/
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex.eq
  (self : binary_tree.array_representation.treemath.ParentNodeIndex)
  (other : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  ok (self = other)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::ParentNodeIndex> for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:29-108:38 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex
  : core.cmp.PartialEq
  binary_tree.array_representation.treemath.ParentNodeIndex
  binary_tree.array_representation.treemath.ParentNodeIndex := {
  eq :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex.eq
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Eq for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:40-108:42 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpEq :
  core.cmp.Eq binary_tree.array_representation.treemath.ParentNodeIndex := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:56-108:59
    Visibility: public -/
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpOrd.cmp
  (self : binary_tree.array_representation.treemath.ParentNodeIndex)
  (other : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result core.cmp.Ordering
  := do
  core.U32.Insts.CoreCmpOrd.cmp self other

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::ParentNodeIndex> for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::partial_cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:44-108:54
    Visibility: public -/
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialOrdParentNodeIndex.partial_cmp
  (self : binary_tree.array_representation.treemath.ParentNodeIndex)
  (other : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result (core.option.Option core.cmp.Ordering)
  := do
  let o ←
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpOrd.cmp
      self other
  ok (core.option.Option.Some o)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::ParentNodeIndex> for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:44-108:54 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialOrdParentNodeIndex
  : core.cmp.PartialOrd
  binary_tree.array_representation.treemath.ParentNodeIndex
  binary_tree.array_representation.treemath.ParentNodeIndex := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex
  partial_cmp :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialOrdParentNodeIndex.partial_cmp
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::ParentNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:56-108:59 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpOrd
  : core.cmp.Ord binary_tree.array_representation.treemath.ParentNodeIndex := {
  EqInst :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpEq
  PartialOrdInst :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialOrdParentNodeIndex
  cmp :=
    binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpOrd.cmp
}

/-- [openmls::binary_tree::array_representation::treemath::_#2]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:61-108:70 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__2 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::_#3]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 108:72-108:83 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__3 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::valid]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 115:4-117:5 -/
def binary_tree.array_representation.treemath.ParentNodeIndex.valid
  (self : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_PARENT
  ok (self <= i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::new]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 125:4-127:5 -/
def binary_tree.array_representation.treemath.ParentNodeIndex.new
  (index : Std.U32) :
  Result binary_tree.array_representation.treemath.ParentNodeIndex
  := do
  ok index

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::u32]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 130:4-132:5
    Visibility: public -/
def binary_tree.array_representation.treemath.ParentNodeIndex.u32
  (self : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Std.U32
  := do
  ok self

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::usize]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 134:4-136:5 -/
def binary_tree.array_representation.treemath.ParentNodeIndex.usize
  (self : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Std.Usize
  := do
  ok (UScalar.cast .Usize self)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 141:4-143:5 -/
def binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
  (self : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Std.U32
  := do
  let i ← self * 2#u32
  i + 1#u32

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::from_tree_index]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 148:4-152:5 -/
def binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
  (node_index : Std.U32) :
  Result binary_tree.array_representation.treemath.ParentNodeIndex
  := do
  massert (node_index > 0#u32)
  let i ← node_index % 2#u32
  massert (i = 1#u32)
  let i1 ← node_index - 1#u32
  let i2 ← i1 / 2#u32
  ok i2

/-- [openmls::binary_tree::array_representation::treemath::{impl core::convert::From<openmls::binary_tree::array_representation::treemath::LeafNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::from]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 172:4-174:5
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreConvertFromLeafNodeIndex.from
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  ok (binary_tree.array_representation.treemath.TreeNodeIndex.Leaf leaf_index)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::convert::From<openmls::binary_tree::array_representation::treemath::LeafNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 171:0-175:1 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreConvertFromLeafNodeIndex
  : core.convert.From binary_tree.array_representation.treemath.TreeNodeIndex
  binary_tree.array_representation.treemath.LeafNodeIndex := {
  «from» :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreConvertFromLeafNodeIndex.from
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::convert::From<openmls::binary_tree::array_representation::treemath::ParentNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::from]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 178:4-180:5
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreConvertFromParentNodeIndex.from
  (parent_index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  ok (binary_tree.array_representation.treemath.TreeNodeIndex.Parent
    parent_index)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::convert::From<openmls::binary_tree::array_representation::treemath::ParentNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 177:0-181:1 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreConvertFromParentNodeIndex
  : core.convert.From binary_tree.array_representation.treemath.TreeNodeIndex
  binary_tree.array_representation.treemath.ParentNodeIndex := {
  «from» :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreConvertFromParentNodeIndex.from
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::clone]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:16-184:21
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCloneClone.clone
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  ok self

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:16-184:21 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCloneClone
  : core.clone.Clone binary_tree.array_representation.treemath.TreeNodeIndex
  := {
  clone :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::Copy for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:23-184:27 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreMarkerCopy
  : core.marker.Copy binary_tree.array_representation.treemath.TreeNodeIndex
  := {
  cloneCloneInst :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCloneClone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::StructuralPartialEq for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:29-184:38 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreMarkerStructuralPartialEq
  : core.marker.StructuralPartialEq
  binary_tree.array_representation.treemath.TreeNodeIndex := {
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::eq]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:29-184:38
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialEqTreeNodeIndex.eq
  (self : binary_tree.array_representation.treemath.TreeNodeIndex)
  (other : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | binary_tree.array_representation.treemath.TreeNodeIndex.Leaf __self_0 =>
      match other with
      | binary_tree.array_representation.treemath.TreeNodeIndex.Leaf __arg1_0
        =>
        binary_tree.array_representation.treemath.LeafNodeIndex.Insts.CoreCmpPartialEqLeafNodeIndex.eq
          __self_0 __arg1_0
      | binary_tree.array_representation.treemath.TreeNodeIndex.Parent _ =>
        fail panic
    | binary_tree.array_representation.treemath.TreeNodeIndex.Parent __self_0
      =>
      match other with
      | binary_tree.array_representation.treemath.TreeNodeIndex.Leaf _ =>
        fail panic
      | binary_tree.array_representation.treemath.TreeNodeIndex.Parent __arg1_0
        =>
        binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex.eq
          __self_0 __arg1_0
  else ok false

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:29-184:38 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialEqTreeNodeIndex
  : core.cmp.PartialEq binary_tree.array_representation.treemath.TreeNodeIndex
  binary_tree.array_representation.treemath.TreeNodeIndex := {
  eq :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialEqTreeNodeIndex.eq
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Eq for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:40-184:42 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpEq :
  core.cmp.Eq binary_tree.array_representation.treemath.TreeNodeIndex := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialEqTreeNodeIndex
}

/-- [openmls::binary_tree::array_representation::treemath::_#4]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:44-184:53 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__4 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::_#5]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 184:55-184:66 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__5 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::valid]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 194:4-199:5 -/
def binary_tree.array_representation.treemath.TreeNodeIndex.valid
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  match self with
  | binary_tree.array_representation.treemath.TreeNodeIndex.Leaf
    leaf_node_index =>
    binary_tree.array_representation.treemath.LeafNodeIndex.valid
      leaf_node_index
  | binary_tree.array_representation.treemath.TreeNodeIndex.Parent
    parent_node_index =>
    binary_tree.array_representation.treemath.ParentNodeIndex.valid
      parent_node_index

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::new]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 207:4-213:5 -/
def binary_tree.array_representation.treemath.TreeNodeIndex.new
  (index : Std.U32) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  let b ← core.num.U32.is_multiple_of index 2#u32
  if b
  then
    let lni ←
      binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index
        index
    ok (binary_tree.array_representation.treemath.TreeNodeIndex.Leaf lni)
  else
    let pni ←
      binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
        index
    ok (binary_tree.array_representation.treemath.TreeNodeIndex.Parent pni)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 224:4-229:5 -/
def binary_tree.array_representation.treemath.TreeNodeIndex.u32
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Std.U32
  := do
  match self with
  | binary_tree.array_representation.treemath.TreeNodeIndex.Leaf index =>
    binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index index
  | binary_tree.array_representation.treemath.TreeNodeIndex.Parent index =>
    binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
      index

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 251:4-253:5
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpOrd.cmp
  (self : binary_tree.array_representation.treemath.TreeNodeIndex)
  (other : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result core.cmp.Ordering
  := do
  let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 self
  let i1 ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 other
  core.U32.Insts.CoreCmpOrd.cmp i i1

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::partial_cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 257:4-259:5
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialOrdTreeNodeIndex.partial_cmp
  (self : binary_tree.array_representation.treemath.TreeNodeIndex)
  (other : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result (core.option.Option core.cmp.Ordering)
  := do
  let o ←
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpOrd.cmp
      self other
  ok (core.option.Option.Some o)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 256:0-260:1 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialOrdTreeNodeIndex
  : core.cmp.PartialOrd binary_tree.array_representation.treemath.TreeNodeIndex
  binary_tree.array_representation.treemath.TreeNodeIndex := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialEqTreeNodeIndex
  partial_cmp :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialOrdTreeNodeIndex.partial_cmp
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::TreeNodeIndex}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 250:0-254:1 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpOrd :
  core.cmp.Ord binary_tree.array_representation.treemath.TreeNodeIndex := {
  EqInst :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpEq
  PartialOrdInst :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpPartialOrdTreeNodeIndex
  cmp :=
    binary_tree.array_representation.treemath.TreeNodeIndex.Insts.CoreCmpOrd.cmp
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::TreeSize}::clone]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:16-262:21
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeSize.Insts.CoreCloneClone.clone
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result binary_tree.array_representation.treemath.TreeSize
  := do
  ok self

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::clone::Clone for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:16-262:21 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.Insts.CoreCloneClone :
  core.clone.Clone binary_tree.array_representation.treemath.TreeSize := {
  clone :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::Copy for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:23-262:27 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.Insts.CoreMarkerCopy :
  core.marker.Copy binary_tree.array_representation.treemath.TreeSize := {
  cloneCloneInst :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCloneClone
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::marker::StructuralPartialEq for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:29-262:38 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeSize.Insts.CoreMarkerStructuralPartialEq
  : core.marker.StructuralPartialEq
  binary_tree.array_representation.treemath.TreeSize := {
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::TreeSize> for openmls::binary_tree::array_representation::treemath::TreeSize}::eq]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:29-262:38
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialEqTreeSize.eq
  (self : binary_tree.array_representation.treemath.TreeSize)
  (other : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  ok (self = other)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialEq<openmls::binary_tree::array_representation::treemath::TreeSize> for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:29-262:38 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialEqTreeSize
  : core.cmp.PartialEq binary_tree.array_representation.treemath.TreeSize
  binary_tree.array_representation.treemath.TreeSize := {
  eq :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialEqTreeSize.eq
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Eq for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:40-262:42 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpEq :
  core.cmp.Eq binary_tree.array_representation.treemath.TreeSize := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialEqTreeSize
}

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::TreeSize}::cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:56-262:59
    Visibility: public -/
def binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpOrd.cmp
  (self : binary_tree.array_representation.treemath.TreeSize)
  (other : binary_tree.array_representation.treemath.TreeSize) :
  Result core.cmp.Ordering
  := do
  core.U32.Insts.CoreCmpOrd.cmp self other

/-- [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::TreeSize> for openmls::binary_tree::array_representation::treemath::TreeSize}::partial_cmp]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:44-262:54
    Visibility: public -/
def
  binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialOrdTreeSize.partial_cmp
  (self : binary_tree.array_representation.treemath.TreeSize)
  (other : binary_tree.array_representation.treemath.TreeSize) :
  Result (core.option.Option core.cmp.Ordering)
  := do
  let o ←
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpOrd.cmp
      self other
  ok (core.option.Option.Some o)

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::PartialOrd<openmls::binary_tree::array_representation::treemath::TreeSize> for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:44-262:54 -/
@[reducible]
def
  binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialOrdTreeSize
  : core.cmp.PartialOrd binary_tree.array_representation.treemath.TreeSize
  binary_tree.array_representation.treemath.TreeSize := {
  PartialEqInst :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialEqTreeSize
  partial_cmp :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialOrdTreeSize.partial_cmp
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::{impl core::cmp::Ord for openmls::binary_tree::array_representation::treemath::TreeSize}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:56-262:59 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpOrd :
  core.cmp.Ord binary_tree.array_representation.treemath.TreeSize := {
  EqInst := binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpEq
  PartialOrdInst :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpPartialOrdTreeSize
  cmp :=
    binary_tree.array_representation.treemath.TreeSize.Insts.CoreCmpOrd.cmp
}

/-- [openmls::binary_tree::array_representation::treemath::_#6]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:61-262:70 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__6 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::_#7]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 262:72-262:83 -/
@[global_simps, irreducible]
def binary_tree.array_representation.treemath.__7 : Unit := ()

/-- [openmls::binary_tree::array_representation::treemath::log2]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 372:0-377:1 -/
def binary_tree.array_representation.treemath.log2
  (x : Std.U32) : Result Std.Usize := do
  if x = 0#u32
  then ok 0#usize
  else
    let i ← core.num.U32.leading_zeros x
    let i1 ← 31#u32 - i
    ok (UScalar.cast .Usize i1)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::valid]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 269:4-274:5 -/
def binary_tree.array_representation.treemath.TreeSize.valid
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  if binary_tree.array_representation.treemath.MIN_TREE_SIZE <= self
  then
    let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
    if self <= i
    then
      let i1 ← binary_tree.array_representation.treemath.log2 self
      let i2 ← lift (UScalar.cast .U32 i1)
      let i3 ← i2 + 1#u32
      let i4 ← core.num.U32.pow 2#u32 i3
      let i5 ← i4 - 1#u32
      ok (self = i5)
    else ok false
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 284:4-287:5 -/
def binary_tree.array_representation.treemath.TreeSize.new
  (nodes : Std.U32) :
  Result binary_tree.array_representation.treemath.TreeSize
  := do
  let k ← binary_tree.array_representation.treemath.log2 nodes
  let i ← k + 1#usize
  let i1 ← 1#u32 <<< i
  let i2 ← i1 - 1#u32
  ok i2

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::leaf_count]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 296:4-298:5 -/
def binary_tree.array_representation.treemath.TreeSize.leaf_count
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result Std.U32
  := do
  let i ← self / 2#u32
  i + 1#u32

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::parent_count]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 301:4-303:5 -/
def binary_tree.array_representation.treemath.TreeSize.parent_count
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result Std.U32
  := do
  self / 2#u32

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::u32]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 306:4-308:5 -/
def binary_tree.array_representation.treemath.TreeSize.u32
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result Std.U32
  := do
  ok self

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::leaf_is_left]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 312:4-314:5 -/
def binary_tree.array_representation.treemath.TreeSize.leaf_is_left
  (self : binary_tree.array_representation.treemath.TreeSize)
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let i ←
    binary_tree.array_representation.treemath.LeafNodeIndex.u32 leaf_index
  let i1 ← binary_tree.array_representation.treemath.TreeSize.leaf_count self
  let i2 ← i1 / 2#u32
  ok (i < i2)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 319:4-321:5 -/
def binary_tree.array_representation.treemath.TreeSize.inc
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result binary_tree.array_representation.treemath.TreeSize
  := do
  let i ← self * 2#u32
  let i1 ← i + 1#u32
  ok i1

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 326:4-333:5 -/
def binary_tree.array_representation.treemath.TreeSize.dec
  (self : binary_tree.array_representation.treemath.TreeSize) :
  Result binary_tree.array_representation.treemath.TreeSize
  := do
  massert (self >= 2#u32)
  if self >= 2#u32
  then let i ← core.num.U32.div_ceil self 2#u32
       let i1 ← i - 1#u32
       ok i1
  else ok 0#u32

/-- [openmls::binary_tree::array_representation::treemath::level]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 379:0-382:1
    Visibility: public -/
def binary_tree.array_representation.treemath.level
  (index : Std.U32) : Result Std.Usize := do
  let i ← core.num.U32.trailing_ones index
  ok (UScalar.cast .Usize i)

/-- [openmls::binary_tree::array_representation::treemath::root]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 386:0-390:1 -/
def binary_tree.array_representation.treemath.root
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  let size1 ← binary_tree.array_representation.treemath.TreeSize.u32 size
  massert (size1 > 0#u32)
  let i ← binary_tree.array_representation.treemath.log2 size1
  let i1 ← 1#u32 <<< i
  let i2 ← i1 - 1#u32
  binary_tree.array_representation.treemath.TreeNodeIndex.new i2

/-- [openmls::binary_tree::array_representation::treemath::left]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 394:0-400:1 -/
def binary_tree.array_representation.treemath.left
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  let x ←
    binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
      index
  let k ← binary_tree.array_representation.treemath.level x
  massert (k > 0#usize)
  let i ← k - 1#usize
  let i1 ← 1#u32 <<< i
  let index1 ← lift (x ^^^ i1)
  binary_tree.array_representation.treemath.TreeNodeIndex.new index1

/-- [openmls::binary_tree::array_representation::treemath::right]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 404:0-410:1 -/
def binary_tree.array_representation.treemath.right
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  let x ←
    binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
      index
  let k ← binary_tree.array_representation.treemath.level x
  massert (k > 0#usize)
  let i ← k - 1#usize
  let i1 ← 3#u32 <<< i
  let index1 ← lift (x ^^^ i1)
  binary_tree.array_representation.treemath.TreeNodeIndex.new index1

/-- [openmls::binary_tree::array_representation::treemath::parent]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 416:0-422:1 -/
def binary_tree.array_representation.treemath.parent
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result binary_tree.array_representation.treemath.ParentNodeIndex
  := do
  let x1 ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 x
  let k ← binary_tree.array_representation.treemath.level x1
  let i ← k + 1#usize
  let i1 ← x1 >>> i
  let b ← lift (i1 &&& 1#u32)
  let i2 ← 1#u32 <<< k
  let i3 ← lift (x1 ||| i2)
  let i4 ← b <<< i
  let index ← lift (i3 ^^^ i4)
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
    index

/-- [openmls::binary_tree::array_representation::treemath::sibling]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 432:0-439:1 -/
def binary_tree.array_representation.treemath.sibling
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  let p ← binary_tree.array_representation.treemath.parent index
  let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 index
  let i1 ←
    binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index p
  let o ← core.U32.Insts.CoreCmpOrd.cmp i i1
  match o with
  | core.cmp.Ordering.Less => binary_tree.array_representation.treemath.right p
  | core.cmp.Ordering.Equal => binary_tree.array_representation.treemath.left p
  | core.cmp.Ordering.Greater =>
    binary_tree.array_representation.treemath.left p

/-- [openmls::binary_tree::array_representation::treemath::_#18::ensures::{impl core::ops::function::FnMut<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), bool> for openmls::binary_tree::array_representation::treemath::_#18::ensures::closure<'_0>}::call_mut]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 452:21-452:81 -/
def
  binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexBool.call_mut
  (c : binary_tree.array_representation.treemath.__18.ensures.closure)
  (tupled_args : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result (Bool ×
    binary_tree.array_representation.treemath.__18.ensures.closure)
  := do
  let b ←
    binary_tree.array_representation.treemath.ParentNodeIndex.valid tupled_args
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.ParentNodeIndex.u32 tupled_args
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.parent_count c
    ok (i < i1, c)
  else ok (false, c)

/-- [openmls::binary_tree::array_representation::treemath::_#18::ensures::{impl core::ops::function::FnOnce<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), bool> for openmls::binary_tree::array_representation::treemath::_#18::ensures::closure<'_0>}::call_once]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 452:21-452:81 -/
def
  binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexBool.call_once
  (c : binary_tree.array_representation.treemath.__18.ensures.closure)
  (pni : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let (b, _) ←
    binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexBool.call_mut
      c pni
  ok b

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::_#18::ensures::{impl core::ops::function::FnOnce<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), bool> for openmls::binary_tree::array_representation::treemath::_#18::ensures::closure<'_0>}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 452:21-452:81 -/
@[reducible]
def
  binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexBool
  : core.ops.function.FnOnce
  binary_tree.array_representation.treemath.__18.ensures.closure
  binary_tree.array_representation.treemath.ParentNodeIndex Bool := {
  call_once :=
    binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexBool.call_once
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::_#18::ensures::{impl core::ops::function::FnMut<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), bool> for openmls::binary_tree::array_representation::treemath::_#18::ensures::closure<'_0>}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 452:21-452:81 -/
@[reducible]
def
  binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexBool
  : core.ops.function.FnMut
  binary_tree.array_representation.treemath.__18.ensures.closure
  binary_tree.array_representation.treemath.ParentNodeIndex Bool := {
  FnOnceInst :=
    binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexBool
  call_mut :=
    binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexBool.call_mut
}

/-- [openmls::binary_tree::array_representation::treemath::direct_path]: loop body 0:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 458:4-462:5 -/
@[rust_loop_body]
def binary_tree.array_representation.treemath.direct_path_loop.body
  (r : Std.U32)
  (d : alloc.vec.Vec binary_tree.array_representation.treemath.ParentNodeIndex)
  (x : Std.U32) :
  Result (ControlFlow ((alloc.vec.Vec
    binary_tree.array_representation.treemath.ParentNodeIndex) × Std.U32)
    (alloc.vec.Vec binary_tree.array_representation.treemath.ParentNodeIndex))
  := do
  if x != r
  then
    let tni ← binary_tree.array_representation.treemath.TreeNodeIndex.new x
    let parent ← binary_tree.array_representation.treemath.parent tni
    let d1 ← alloc.vec.Vec.push d parent
    let x1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        parent
    ok (cont (d1, x1))
  else ok (done d)

/-- [openmls::binary_tree::array_representation::treemath::direct_path]: loop 0:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 458:4-462:5 -/
@[rust_loop]
def binary_tree.array_representation.treemath.direct_path_loop
  (r : Std.U32)
  (d : alloc.vec.Vec binary_tree.array_representation.treemath.ParentNodeIndex)
  (x : Std.U32) :
  Result (alloc.vec.Vec
    binary_tree.array_representation.treemath.ParentNodeIndex)
  := do
  loop
    (fun (d1, x1) =>
      binary_tree.array_representation.treemath.direct_path_loop.body r d1 x1)
    (d, x)

/-- [openmls::binary_tree::array_representation::treemath::direct_path]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 453:0-464:1 -/
def binary_tree.array_representation.treemath.direct_path
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result (alloc.vec.Vec
    binary_tree.array_representation.treemath.ParentNodeIndex)
  := do
  let tni ← binary_tree.array_representation.treemath.root size
  let r ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 tni
  let d ←
    alloc.vec.Vec.new binary_tree.array_representation.treemath.ParentNodeIndex
  let x ←
    binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index
      node_index
  binary_tree.array_representation.treemath.direct_path_loop r d x

/-- [openmls::binary_tree::array_representation::treemath::copath::{impl core::ops::function::FnMut<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::copath::closure}::call_mut]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 481:17-481:46 -/
def
  binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex.call_mut
  (c : binary_tree.array_representation.treemath.copath.closure)
  (tupled_args : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result (binary_tree.array_representation.treemath.TreeNodeIndex ×
    binary_tree.array_representation.treemath.copath.closure)
  := do
  ok (binary_tree.array_representation.treemath.TreeNodeIndex.Parent
    tupled_args, c)

/-- [openmls::binary_tree::array_representation::treemath::copath::{impl core::ops::function::FnOnce<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::copath::closure}::call_once]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 481:17-481:46 -/
def
  binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexTreeNodeIndex.call_once
  (c : binary_tree.array_representation.treemath.copath.closure)
  (pni : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result binary_tree.array_representation.treemath.TreeNodeIndex
  := do
  let (tni, _) ←
    binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex.call_mut
      c pni
  ok tni

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::copath::{impl core::ops::function::FnOnce<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::copath::closure}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 481:17-481:46 -/
@[reducible]
def
  binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexTreeNodeIndex
  : core.ops.function.FnOnce
  binary_tree.array_representation.treemath.copath.closure
  binary_tree.array_representation.treemath.ParentNodeIndex
  binary_tree.array_representation.treemath.TreeNodeIndex := {
  call_once :=
    binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexTreeNodeIndex.call_once
}

/-- Trait implementation: [openmls::binary_tree::array_representation::treemath::copath::{impl core::ops::function::FnMut<(&'_ openmls::binary_tree::array_representation::treemath::ParentNodeIndex,), openmls::binary_tree::array_representation::treemath::TreeNodeIndex> for openmls::binary_tree::array_representation::treemath::copath::closure}]
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 481:17-481:46 -/
@[reducible]
def
  binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex
  : core.ops.function.FnMut
  binary_tree.array_representation.treemath.copath.closure
  binary_tree.array_representation.treemath.ParentNodeIndex
  binary_tree.array_representation.treemath.TreeNodeIndex := {
  FnOnceInst :=
    binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnOnceTupleSharedParentNodeIndexTreeNodeIndex
  call_mut :=
    binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex.call_mut
}

/-- [openmls::binary_tree::array_representation::treemath::copath]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 468:0-486:1 -/
def binary_tree.array_representation.treemath.copath
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result (alloc.vec.Vec
    binary_tree.array_representation.treemath.TreeNodeIndex)
  := do
  let direct_path ←
    binary_tree.array_representation.treemath.direct_path leaf_index size
  let b ← alloc.vec.Vec.is_empty direct_path
  if b
  then
    alloc.vec.Vec.new binary_tree.array_representation.treemath.TreeNodeIndex
  else
    let (_, direct_path1) ← alloc.vec.Vec.pop direct_path
    let y ←
      lift (Std.Array.to_slice
        (Array.make 1#usize [
           binary_tree.array_representation.treemath.TreeNodeIndex.Leaf
           leaf_index
           ] : Array binary_tree.array_representation.treemath.TreeNodeIndex
        1#usize))
    let ret ← alloc.slice.Slice.into_vec y
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref direct_path1
    let i ← core.slice.Slice.iter s
    let m ←
      core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map
        binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex
        i ()
    let v ←
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT
        binary_tree.array_representation.treemath.ParentNodeIndex)
        binary_tree.array_representation.treemath.copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator
        binary_tree.array_representation.treemath.TreeNodeIndex) m
    let (ret1, _) ← alloc.vec.Vec.append ret v
    let ii ←
      alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
        ret1
    let m1 ←
      alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.map
        (BuiltinFnMut binary_tree.array_representation.treemath.TreeNodeIndex
        binary_tree.array_representation.treemath.TreeNodeIndex) ii
        (binary_tree.array_representation.treemath.sibling)
    core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
      (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator
      binary_tree.array_representation.treemath.TreeNodeIndex) (BuiltinFnMut
      binary_tree.array_representation.treemath.TreeNodeIndex
      binary_tree.array_representation.treemath.TreeNodeIndex)
      (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator
      binary_tree.array_representation.treemath.TreeNodeIndex) m1

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop body 0:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop_body]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop0.body
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.U32 × Std.I32) (Std.U32 × Std.I32))
  := do
  if xn != yn
  then
    let xn1 ← xn >>> 1#i32
    let yn1 ← yn >>> 1#i32
    let k1 ← k + 1#i32
    ok (cont (xn1, yn1, k1))
  else ok (done (xn, k))

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop 0:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop0
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (Std.U32 × Std.I32)
  := do
  loop
    (fun (xn1, yn1, k1) =>
      binary_tree.array_representation.treemath.lowest_common_ancestor_loop0.body
      xn1 yn1 k1)
    (xn, yn, k)

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop body 1:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop_body]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop1.body
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.U32 × Std.I32) (Std.U32 × Std.I32))
  := do
  if xn != yn
  then
    let xn1 ← xn >>> 1#i32
    let yn1 ← yn >>> 1#i32
    let k1 ← k + 1#i32
    ok (cont (xn1, yn1, k1))
  else ok (done (xn, k))

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop 1:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop1
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (Std.U32 × Std.I32)
  := do
  loop
    (fun (xn1, yn1, k1) =>
      binary_tree.array_representation.treemath.lowest_common_ancestor_loop1.body
      xn1 yn1 k1)
    (xn, yn, k)

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop body 2:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop_body]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop2.body
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.U32 × Std.I32) (Std.U32 × Std.I32))
  := do
  if xn != yn
  then
    let xn1 ← xn >>> 1#i32
    let yn1 ← yn >>> 1#i32
    let k1 ← k + 1#i32
    ok (cont (xn1, yn1, k1))
  else ok (done (xn, k))

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop 2:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop2
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (Std.U32 × Std.I32)
  := do
  loop
    (fun (xn1, yn1, k1) =>
      binary_tree.array_representation.treemath.lowest_common_ancestor_loop2.body
      xn1 yn1 k1)
    (xn, yn, k)

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop body 3:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop_body]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop3.body
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (ControlFlow (Std.U32 × Std.U32 × Std.I32) (Std.U32 × Std.I32))
  := do
  if xn != yn
  then
    let xn1 ← xn >>> 1#i32
    let yn1 ← yn >>> 1#i32
    let k1 ← k + 1#i32
    ok (cont (xn1, yn1, k1))
  else ok (done (xn, k))

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]: loop 3:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 504:4-508:5 -/
@[rust_loop]
def binary_tree.array_representation.treemath.lowest_common_ancestor_loop3
  (xn : Std.U32) (yn : Std.U32) (k : Std.I32) :
  Result (Std.U32 × Std.I32)
  := do
  loop
    (fun (xn1, yn1, k1) =>
      binary_tree.array_representation.treemath.lowest_common_ancestor_loop3.body
      xn1 yn1 k1)
    (xn, yn, k)

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 492:0-510:1 -/
def binary_tree.array_representation.treemath.lowest_common_ancestor
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result binary_tree.array_representation.treemath.ParentNodeIndex
  := do
  let x1 ←
    binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index x
  let y1 ←
    binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index y
  let i ← binary_tree.array_representation.treemath.level x1
  let lx ← i + 1#usize
  let i1 ← binary_tree.array_representation.treemath.level y1
  let ly ← i1 + 1#usize
  if lx <= ly
  then
    let i2 ← x1 >>> ly
    let i3 ← y1 >>> ly
    if i2 = i3
    then
      binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
        y1
    else
      if ly <= lx
      then
        let i4 ← x1 >>> lx
        let i5 ← y1 >>> lx
        if i4 = i5
        then
          binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
            x1
        else
          let (xn, k) ←
            binary_tree.array_representation.treemath.lowest_common_ancestor_loop0
              x1 y1 0#i32
          let i6 ← xn <<< k
          let i7 ← k - 1#i32
          let i8 ← 1#u32 <<< i7
          let i9 ← i6 + i8
          let i10 ← i9 - 1#u32
          binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
            i10
      else
        let (xn, k) ←
          binary_tree.array_representation.treemath.lowest_common_ancestor_loop1
            x1 y1 0#i32
        let i4 ← xn <<< k
        let i5 ← k - 1#i32
        let i6 ← 1#u32 <<< i5
        let i7 ← i4 + i6
        let i8 ← i7 - 1#u32
        binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
          i8
  else
    if ly <= lx
    then
      let i2 ← x1 >>> lx
      let i3 ← y1 >>> lx
      if i2 = i3
      then
        binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
          x1
      else
        let (xn, k) ←
          binary_tree.array_representation.treemath.lowest_common_ancestor_loop2
            x1 y1 0#i32
        let i4 ← xn <<< k
        let i5 ← k - 1#i32
        let i6 ← 1#u32 <<< i5
        let i7 ← i4 + i6
        let i8 ← i7 - 1#u32
        binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
          i8
    else
      let (xn, k) ←
        binary_tree.array_representation.treemath.lowest_common_ancestor_loop3
          x1 y1 0#i32
      let i2 ← xn <<< k
      let i3 ← k - 1#i32
      let i4 ← 1#u32 <<< i3
      let i5 ← i2 + i4
      let i6 ← i5 - 1#u32
      binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
        i6

/-- [openmls::binary_tree::array_representation::treemath::common_direct_path]: loop body 0:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 528:4-537:5 -/
@[rust_loop_body]
def binary_tree.array_representation.treemath.common_direct_path_loop.body
  (x_path : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex)
  (y_path : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) (len : Std.Usize)
  (common_path : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec
    binary_tree.array_representation.treemath.ParentNodeIndex) × Std.Usize)
    (alloc.vec.Vec binary_tree.array_representation.treemath.ParentNodeIndex))
  := do
  if i < len
  then
    let xi ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) x_path i
    let yi ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT
        binary_tree.array_representation.treemath.ParentNodeIndex) y_path i
    let b ←
      binary_tree.array_representation.treemath.ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex.eq
        xi yi
    if b
    then
      let common_path1 ← alloc.vec.Vec.push common_path xi
      let i1 ← i + 1#usize
      ok (cont (common_path1, i1))
    else ok (done common_path)
  else ok (done common_path)

/-- [openmls::binary_tree::array_representation::treemath::common_direct_path]: loop 0:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 528:4-537:5 -/
@[rust_loop]
def binary_tree.array_representation.treemath.common_direct_path_loop
  (x_path : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex)
  (y_path : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) (len : Std.Usize)
  (common_path : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) (i : Std.Usize) :
  Result (alloc.vec.Vec
    binary_tree.array_representation.treemath.ParentNodeIndex)
  := do
  loop
    (fun (common_path1, i1) =>
      binary_tree.array_representation.treemath.common_direct_path_loop.body
      x_path y_path len common_path1 i1)
    (common_path, i)

/-- [openmls::binary_tree::array_representation::treemath::common_direct_path]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 515:0-541:1 -/
def binary_tree.array_representation.treemath.common_direct_path
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result (alloc.vec.Vec
    binary_tree.array_representation.treemath.ParentNodeIndex)
  := do
  let x_path ← binary_tree.array_representation.treemath.direct_path x size
  let y_path ← binary_tree.array_representation.treemath.direct_path y size
  let (s, deref_mut_back) ←
    alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut x_path
  let s1 ← core.slice.Slice.reverse s
  let (s2, deref_mut_back1) ←
    alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut y_path
  let s3 ← core.slice.Slice.reverse s2
  let x_path1 := deref_mut_back s1
  let i ← alloc.vec.Vec.len x_path1
  let y_path1 := deref_mut_back1 s3
  let i1 ← alloc.vec.Vec.len y_path1
  let len ← core.cmp.min core.Usize.Insts.CoreCmpOrd i i1
  let common_path ←
    alloc.vec.Vec.with_capacity
      binary_tree.array_representation.treemath.ParentNodeIndex len
  let common_path1 ←
    binary_tree.array_representation.treemath.common_direct_path_loop x_path1
      y_path1 len common_path 0#usize
  let (s4, deref_mut_back2) ←
    alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut common_path1
  let s5 ← core.slice.Slice.reverse s4
  ok (deref_mut_back2 s5)

/-- [openmls::binary_tree::array_representation::treemath::is_node_in_tree]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 553:0-555:1 -/
def binary_tree.array_representation.treemath.is_node_in_tree
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let i ←
    binary_tree.array_representation.treemath.TreeNodeIndex.u32 node_index
  let i1 ← binary_tree.array_representation.treemath.TreeSize.u32 size
  ok (i < i1)

end openmls
