-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [openmls]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace openmls


/-- [openmls::binary_tree::array_representation::treemath::root::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 384:0-384:25 -/
@[reducible]
def binary_tree.array_representation.treemath.root.pre
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid size

/-- [openmls::binary_tree::array_representation::treemath::root::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 385:0-385:49 -/
@[reducible]
def binary_tree.array_representation.treemath.root.post
  (size : binary_tree.array_representation.treemath.TreeSize)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ← binary_tree.array_representation.treemath.TreeSize.u32 size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.root.spec
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.root size
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.root.post size res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::left::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 392:0-392:26 -/
@[reducible]
def binary_tree.array_representation.treemath.left.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

/-- [openmls::binary_tree::array_representation::treemath::left::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 393:0-393:60 -/
@[reducible]
def binary_tree.array_representation.treemath.left.post
  (index : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        index
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.left.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.left.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.left index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.left.post index res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::right::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 402:0-402:26 -/
@[reducible]
def binary_tree.array_representation.treemath.right.pre
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid index

/-- [openmls::binary_tree::array_representation::treemath::right::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 403:0-403:60 -/
@[reducible]
def binary_tree.array_representation.treemath.right.post
  (index : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid r
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 r
    let i1 ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index
        index
    ok (i > i1)
  else ok false

def binary_tree.array_representation.treemath.right.spec
  (index : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.right.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.right index
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.right.post index res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::parent::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 414:0-414:51 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.pre
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid x
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 x
    let i1 ← binary_tree.array_representation.treemath.MAX_ROOT_INDEX
    ok (i != i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::parent::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 415:0-415:75 -/
@[reducible]
def binary_tree.array_representation.treemath.parent.post
  (x : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.ParentNodeIndex.valid r
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index r
    let i1 ← binary_tree.array_representation.treemath.level i
    let i2 ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 x
    let i3 ← binary_tree.array_representation.treemath.level i2
    let i4 ← i3 + 1#usize
    ok (i1 = i4)
  else ok false

def binary_tree.array_representation.treemath.parent.spec
  (x : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.parent.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.parent x
  ⦃ ⇓ res =>
  ⌜ (binary_tree.array_representation.treemath.parent.post x res).holds ⌝
  ⦄


/-- [openmls::binary_tree::array_representation::treemath::sibling::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 431:0-431:59 -/
@[reducible]
def binary_tree.array_representation.treemath.sibling.pre
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeNodeIndex.valid index
  if b
  then
    let i ← binary_tree.array_representation.treemath.TreeNodeIndex.u32 index
    let i1 ← binary_tree.array_representation.treemath.MAX_ROOT_INDEX
    ok (i != i1)
  else ok false

def binary_tree.array_representation.treemath.sibling.spec
  (index : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.sibling.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.sibling index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 449:0-449:65 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.pre
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 node_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::direct_path::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 450:0-452:84 -/
@[reducible]
def binary_tree.array_representation.treemath.direct_path.post
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize)
  (result : alloc.vec.Vec
  binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  let i ← alloc.vec.Vec.len result
  if i <= 29#usize
  then
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref result
    let i1 ← core.slice.Slice.iter s
    let (b, _) ←
      core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
        binary_tree.array_representation.treemath.__18.ensures.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexBool
        i1 size
    ok b
  else ok false

def binary_tree.array_representation.treemath.direct_path.spec
  (node_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.direct_path.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.direct_path node_index size
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.direct_path.post node_index size
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::copath::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 467:0-467:65 -/
@[reducible]
def binary_tree.array_representation.treemath.copath.pre
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ←
      binary_tree.array_representation.treemath.LeafNodeIndex.u32 leaf_index
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    ok (i < i1)
  else ok false

def binary_tree.array_representation.treemath.copath.spec
  (leaf_index : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.copath.pre leaf_index size).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.copath leaf_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 490:0-490:57 -/
@[reducible]
def binary_tree.array_representation.treemath.lowest_common_ancestor.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.LeafNodeIndex.valid x
  if b
  then
    let b1 ← binary_tree.array_representation.treemath.LeafNodeIndex.valid y
    if b1
    then
      let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
      let i1 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i != i1)
    else ok false
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::lowest_common_ancestor::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 491:0-491:25 -/
@[reducible]
def binary_tree.array_representation.treemath.lowest_common_ancestor.post
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid r

def binary_tree.array_representation.treemath.lowest_common_ancestor.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.lowest_common_ancestor.pre x
  y).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.lowest_common_ancestor x y
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.lowest_common_ancestor.post x y
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::common_direct_path::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 514:0-514:87 -/
@[reducible]
def binary_tree.array_representation.treemath.common_direct_path.pre
  (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid size
  if b
  then
    let i ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 x
    let i1 ←
      binary_tree.array_representation.treemath.TreeSize.leaf_count size
    if i < i1
    then
      let i2 ← binary_tree.array_representation.treemath.LeafNodeIndex.u32 y
      ok (i2 < i1)
    else ok false
  else ok false

def binary_tree.array_representation.treemath.common_direct_path.spec
   (x : binary_tree.array_representation.treemath.LeafNodeIndex)
  (y : binary_tree.array_representation.treemath.LeafNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.common_direct_path.pre x y
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.common_direct_path x y size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::is_node_in_tree::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 552:0-552:31 -/
@[reducible]
def binary_tree.array_representation.treemath.is_node_in_tree.pre
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid node_index

def binary_tree.array_representation.treemath.is_node_in_tree.spec
  (node_index : binary_tree.array_representation.treemath.TreeNodeIndex)
  (size : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.is_node_in_tree.pre node_index
  size).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.is_node_in_tree node_index size
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 75:4-75:34 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.new.pre
  (index : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_LEAF
  ok (index <= i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 76:4-76:29 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.new.post
  (index : Std.U32)
  (r : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.LeafNodeIndex.valid r

def binary_tree.array_representation.treemath.LeafNodeIndex.new.spec
  (index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.new.pre index).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.new index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.LeafNodeIndex.new.post index
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 92:4-92:29 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.LeafNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::to_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 93:4-93:53 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.post
  (self_ : binary_tree.array_representation.treemath.LeafNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  if r <= i
  then let i1 ← r % 2#u32
       ok (i1 = 0#u32)
  else ok false

def binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.LeafNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.LeafNodeIndex.to_tree_index.post
  self res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 99:4-99:68 -/
@[reducible]
def binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  if i = 0#u32
  then
    let i1 ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
    ok (node_index <= i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::LeafNodeIndex}::from_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 100:4-100:29 -/
@[reducible]
def
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.post
  (node_index : Std.U32)
  (r : binary_tree.array_representation.treemath.LeafNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.LeafNodeIndex.valid r

def
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.LeafNodeIndex.from_tree_index.post
  node_index res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 123:4-123:36 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.new.pre
  (index : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_PARENT
  ok (index <= i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 124:4-124:29 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.new.post
  (index : Std.U32)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid r

def binary_tree.array_representation.treemath.ParentNodeIndex.new.spec
   (index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.new.pre
  index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.new index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.ParentNodeIndex.new.post index
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 139:4-139:29 -/
@[reducible]
def binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::to_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 140:4-140:52 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.post
  (self_ : binary_tree.array_representation.treemath.ParentNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  if r < i
  then let i1 ← r % 2#u32
       ok (i1 = 1#u32)
  else ok false

def
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.spec
   (self : binary_tree.array_representation.treemath.ParentNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.pre
  self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index.post
  self res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::from_tree_index::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 146:4-146:68 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  (node_index : Std.U32) : Result Bool := do
  let i ← node_index % 2#u32
  if i = 1#u32
  then
    let i1 ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
    ok (node_index <= i1)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::ParentNodeIndex}::from_tree_index::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 147:4-147:29 -/
@[reducible]
def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.post
  (node_index : Std.U32)
  (r : binary_tree.array_representation.treemath.ParentNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.ParentNodeIndex.valid r

def
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.spec
   (node_index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.pre
  node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index
  node_index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.ParentNodeIndex.from_tree_index.post
  node_index res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 205:4-205:40 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.new.pre
  (index : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  ok (index <= i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 206:4-206:29 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.new.post
  (index : Std.U32)
  (r : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid r

def binary_tree.array_representation.treemath.TreeNodeIndex.new.spec
  (index : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.TreeNodeIndex.new.pre index).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.new index
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeNodeIndex.new.post index
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 222:4-222:29 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeNodeIndex.valid self_

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeNodeIndex}::u32::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 223:4-223:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeNodeIndex.u32.post
  (self_ : binary_tree.array_representation.treemath.TreeNodeIndex)
  (r : Std.U32) :
  Result Bool
  := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_INDEX
  ok (r <= i)

def binary_tree.array_representation.treemath.TreeNodeIndex.u32.spec
  (self : binary_tree.array_representation.treemath.TreeNodeIndex) : Prop :=
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.pre self).holds
  →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeNodeIndex.u32 self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeNodeIndex.u32.post self
  res).holds ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 282:4-282:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.pre
  (nodes : Std.U32) : Result Bool := do
  let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
  ok (nodes <= i)

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::new::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 283:4-283:39 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.new.post
  (nodes : Std.U32)
  (result : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  binary_tree.array_representation.treemath.TreeSize.valid result

def binary_tree.array_representation.treemath.TreeSize.new.spec
  (nodes : Std.U32) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.new.pre nodes).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.new nodes
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.new.post nodes res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 318:4-318:55 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
  if b
  then
    let i ← binary_tree.array_representation.treemath.MAX_TREE_SIZE
    ok (self_ < i)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::inc::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 317:4-317:76 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.inc.post
  (self_ : binary_tree.array_representation.treemath.TreeSize)
  (self__future : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ←
    binary_tree.array_representation.treemath.TreeSize.valid self__future
  if b
  then let i ← self_ * 2#u32
       let i1 ← i + 1#u32
       ok (self__future = i1)
  else ok false

def binary_tree.array_representation.treemath.TreeSize.inc.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.inc.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.inc self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.inc.post self res).holds
  ⌝ ⦄


/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::pre]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 324:4-324:55 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.pre
  (self_ : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ← binary_tree.array_representation.treemath.TreeSize.valid self_
  if b
  then ok (binary_tree.array_representation.treemath.MIN_TREE_SIZE < self_)
  else ok false

/-- [openmls::binary_tree::array_representation::treemath::{openmls::binary_tree::array_representation::treemath::TreeSize}::dec::post]:
    Source: 'openmls/src/binary_tree/array_representation/treemath.rs', lines 325:4-325:72 -/
@[reducible]
def binary_tree.array_representation.treemath.TreeSize.dec.post
  (self_ : binary_tree.array_representation.treemath.TreeSize)
  (self__future : binary_tree.array_representation.treemath.TreeSize) :
  Result Bool
  := do
  let b ←
    binary_tree.array_representation.treemath.TreeSize.valid self__future
  if b
  then let i ← self_ / 2#u32
       ok (self__future = i)
  else ok false

def binary_tree.array_representation.treemath.TreeSize.dec.spec
  (self : binary_tree.array_representation.treemath.TreeSize) : Prop :=
  (binary_tree.array_representation.treemath.TreeSize.dec.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  binary_tree.array_representation.treemath.TreeSize.dec self
  ⦃ ⇓ res =>
  ⌜
  (binary_tree.array_representation.treemath.TreeSize.dec.post self res).holds
  ⌝ ⦄

end openmls
