-- [openmls]: generic, function-agnostic proof infrastructure (concern A).
-- Foundation imported by every other proof module: the measure-decreasing loop driver and its
-- triple helpers, the `Vec` length helper `vecLen`, and the `attribute [spec] uncurry` that lets
-- `mvcgen` step Aeneas tuple-destructuring binds. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxRecDepth 2048

/-! ### `subst_vals` — `subst` for machine-scalar value equations

`mvcgen` leaves chains of hypotheses `h : ↑x = e` whose left-hand side is a scalar value
projection (`UScalar.val x` / `IScalar.val x` / `IScalar.toNat x`), which `subst` rejects
(the LHS is not a variable). `subst_vals` substitutes them anyway: it rewrites `↑x → e` in
every other hypothesis and the goal, then drops `h` and `x` when `x` is otherwise dead.
Two design guarantees, both load-bearing in this development:

* **Occurs-check**: a self-referential equation (e.g. the `Nat.log` fixpoint shape
  `↑size = 2 ^ (Nat.log 2 ↑size + 1) − 1`, on which `scalar_tac`'s preprocessing diverges) is
  left untouched — `subst_vals` is quarantine-safe by construction.
* **No information loss**: when the goal still mentions the scalar itself at scalar level
  (e.g. `decide (x < y) = true`), the — by then fully substituted — equation is kept for
  `scalar_tac`.

Works on inaccessible hypotheses (no `rename_i` needed). Limitation: fires only when the
projected operand is a plain local variable (`IScalar.toNat p.2` is skipped). -/
section subst_vals

open Lean Meta Elab Tactic

/-- The fvar `x` when `e` is a machine-scalar value projection
    (`UScalar.val x` / `IScalar.val x` / `IScalar.toNat x`) of a local variable `x`. -/
private def valProjFVar? (e : Expr) : Option FVarId := do
  let .const n _ := e.getAppFn | none
  guard (n == ``Aeneas.Std.UScalar.val || n == ``Aeneas.Std.IScalar.val
      || n == ``Aeneas.Std.IScalar.toNat)
  guard (e.getAppNumArgs ≥ 1)
  let x := e.appArg!
  guard x.isFVar
  return x.fvarId!

/-- Work loop of `subst_vals`: pick an unvisited `h : ↑x = e` with `x ∉ e`, rewrite
    `↑x → e` everywhere else (`simpGoal` with `h` as the only rule), drop `h`/`x` if `x`
    is then dead, recurse. `visited` is keyed on `x`, whose `FVarId` is stable (never
    simplified); `none` means the substitution closed the goal. -/
private partial def substValsLoop (g : MVarId) (visited : Std.HashSet FVarId := {}) :
    MetaM (Option MVarId) := do
  let found ← g.withContext do
    let lctx ← getLCtx
    let mut res := none
    for d in lctx do
      if d.isImplementationDetail then continue
      let ty ← instantiateMVars d.type
      if let some (_, lhs, rhs) := ty.eq? then
        if let some x := valProjFVar? lhs then
          if !visited.contains x && !(rhs.containsFVar x) then
            res := some (d.fvarId, x); break
    pure res
  match found with
  | none => return some g
  | some (h, x) =>
    let g' ← g.withContext do
      let thms ← ({} : SimpTheorems).add (.fvar h) #[] (mkFVar h)
      let ctx ← Simp.mkContext (config := {}) (simpTheorems := #[thms])
        (congrTheorems := ← getSimpCongrTheorems)
      let fvars := (← g.getNondepPropHyps).filter (· != h)
      let s ← saveState
      try
        let (res, _) ← simpGoal g ctx (fvarIdsToSimp := fvars)
        match res with
        | some (_, g') => pure (some g')
        | none => pure none
      catch _ =>
        -- `↑x` occurs nowhere else: nothing to rewrite ("simp made no progress").
        restoreState s; pure (some g)
    match g' with
    | none => return none
    | some g' =>
      -- Speculative `clear` must backtrack the FULL state: `MVarId.clear` assigns the
      -- old goal even when we abandon its result.
      let g' ← do
        let s ← saveState
        try
          let g₂ ← g'.clear h
          g₂.clear x
        catch _ =>
          restoreState s
          pure g'
      substValsLoop g' (visited.insert x)

/-- Substitute every hypothesis `↑x = e` (machine-scalar value equation with `x ∉ e`) as
    `subst` would; see the section docstring. -/
elab "subst_vals" : tactic => do
  match ← substValsLoop (← getMainGoal) with
  | some g => replaceMainGoal [g]
  | none => replaceMainGoal []

end subst_vals

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/- Lets `mvcgen` step Aeneas tuple-destructuring do-binds (`let (a,b) ← e` desugars to
   `e >>= uncurry (fun a b => …)`). Registered here so it is in scope for every importing module
   before any `Vec`/iterator-heavy `mvcgen`. -/
attribute [spec] uncurry

/-- Length of a `CoreModels` `Vec` (its underlying `Seq`/slice length, as a `Nat`).
    `alloc.vec.Vec T` is reducibly `Seq T = Slice T`, so `v` is itself the slice. -/
def vecLen {T : Type} (v : alloc.vec.Vec T) : Nat := Aeneas.Std.Slice.length v

/-- A slice iterator's remaining elements. A real definition, hence **not** part of the trusted
    surface: `CoreModels`' `core.slice.iter.Iter T` is `@[reducible]`-equal to
    `rust_primitives.sequence.Seq T = Aeneas.Std.Slice T`, a subtype of `List T`, so the remaining
    elements are literally the underlying list. Lives here — next to `vecLen`, its `Vec` twin —
    as shared vocabulary for the iterator contracts in `MissingCoreSpecs.lean`. -/
def sliceIterElems {T : Type} (it : core.slice.iter.Iter T) : List T := it.val

/-! ### Generic measure-decreasing loop spec (PostCond-flavoured body obligation)

   `Aeneas.Std.loop.spec_decr_nat`'s body obligation is a raw `WP.spec … (fun r => …)`
   predicate, which `mvcgen`/`mspec` will not step through. This variant phrases the body
   obligation as a `⦃ ⇓ r => match … ⌜…⌝ ⦄` Triple, so the body can be discharged with
   `mvcgen`. Adapted from `libcrux-iot` `sha3` `Foundation/I32LoopSpec.lean`
   (`loop_range_spec_i32`). -/
section loop_measure_helpers

abbrev ResultPS := Std.Do.PostShape.except Error (Std.Do.PostShape.except PUnit Std.Do.PostShape.pure)

theorem triple_noThrow_elim {α : Type} {x : Result α} {Q : α → Std.Do.Assertion ResultPS}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ Std.Do.PostCond.noThrow Q ⦄) {v : α} (hv : x = ok v) :
    (Q v).down := by
  subst hv; simpa [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply] using h

theorem triple_noThrow_exists_ok {α : Type} {x : Result α}
    {Q : α → Std.Do.Assertion ResultPS}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ Std.Do.PostCond.noThrow Q ⦄) : ∃ v, x = ok v := by
  match x, h with
  | .ok v, _ => exact ⟨v, rfl⟩
  | .fail _, h => exact absurd h (by simp [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply])
  | .div, h => exact absurd h (by simp [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply])

theorem triple_of_ok {α : Type} {x : Result α} {v : α} {P : α → Prop}
    (hx : x = ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, Std.Do.PredTrans.apply, hp]

/-- Panic-freedom + functional spec for a `loop` driven by a strictly-decreasing `Nat`
    measure, with a `mvcgen`-steppable body obligation. -/
theorem loop_spec_measure {α β : Type} (body : α → Result (ControlFlow α β))
    (measure : α → Nat) (inv : α → Prop) (post : β → Prop) (x0 : α)
    (h_init : inv x0)
    (h_step : ∀ a, inv a →
      ⦃ ⌜ True ⌝ ⦄
      body a
      ⦃ ⇓ r => match r with
        | .cont a' => ⌜ inv a' ∧ measure a' < measure a ⌝
        | .done y => ⌜ post y ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄ Aeneas.Std.loop body x0 ⦃ ⇓ r => ⌜ post r ⌝ ⦄ := by
  suffices gen : ∀ (n : Nat) (a : α), measure a = n → inv a →
      ⦃ ⌜ True ⌝ ⦄ Aeneas.Std.loop body a ⦃ ⇓ r => ⌜ post r ⌝ ⦄ by
    exact gen _ x0 rfl h_init
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro a hn hinv
    have hs := h_step a hinv
    obtain ⟨r, hbody⟩ := triple_noThrow_exists_ok hs
    have hpost := triple_noThrow_elim hs hbody
    rw [Aeneas.Std.loop.eq_def, hbody]
    match r with
    | .done y =>
      simp at hpost; exact triple_of_ok rfl hpost
    | .cont a' =>
      simp only at hpost
      obtain ⟨hinv', hlt⟩ := hpost
      subst hn
      exact ih (measure a') hlt a' rfl hinv'

end loop_measure_helpers

/-! ### Partial-correctness → Triple bridge

   Generic (nothing treemath- or `CoreModels`-specific), and needed by DAG siblings
   `MissingCoreSpecs` and `PartialSpecs` alike, hence its home here. -/

/-- Bridge from a partial-correctness fact to the generic `mvcgen`-compatible triple: the same
reduction `@[step]` performs when deriving a `.mvcgen_spec`. Done by hand because the subjects
at the use sites are `CoreModels` operations / project-local extraction outputs that we do not
want to register in the global `step` set. -/
theorem triple_of_partialSpec {α} {x : Result α}
    {p_ok : α → Prop} {p_fail : Aeneas.Std.Error → Prop} {p_div : Prop}
    (h : Aeneas.Std.WP.partialSpec x p_ok p_fail p_div)
    (Q : PostCond α Aeneas.Std.Result.postShape)
    (h_ok : ∀ r, p_ok r → Aeneas.Std.willYield r Q)
    (h_fail : ∀ e, p_fail e → Aeneas.Std.willFail e Q)
    (h_div : p_div → Aeneas.Std.willDiverge Q) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ Q ⦄ := by
  cases x <;>
    simp_all [Aeneas.Std.WP.partialSpec, Triple, _root_.Std.Do.WP.wp, PredTrans.apply,
      Aeneas.Std.willYield, Aeneas.Std.willFail, Aeneas.Std.willDiverge]

/-- `vecLen v` is the length of `v`'s underlying list. -/
theorem vecLen_eq_length {T : Type} (v : alloc.vec.Vec T) : vecLen v = v.1.length := rfl

/-! ### `scalar_tac`-free escape hatch for `Nat.log`-poisoned contexts

   `scalar_tac`'s preprocessing loops on hypotheses carrying a `Nat.log` fixpoint / `2 ^ (…) - 1`
   shape (reproducer: `Openmls/Issues/ScalarTacNatLogLoop.lean`), so goals in such a context must be
   closed by `omega` on plain `Nat`s instead. This `rfl` lets `simp only` rewrite a machine-word `<`
   into the `Nat` `<` that `omega` understands, with no `scalar_tac` call at all. -/

theorem u32_lt_nat (u v : Std.U32) : (u < v) = ((↑u : Nat) < ↑v) := rfl

end openmls
