-- [openmls]: PROVED `@[spec]` contracts for standard-library `core`/`alloc` operations.
-- These fill in specs that the extraction did not provide. Every contract is *discharged here*
-- (no `sorry`), so none of them is part of the trusted audit surface.
-- Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
import Openmls.Proofs.BitMath
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

/-- `Vec::len` returns the vec's length. -/
@[spec]
theorem vec_len_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.len v
    ⦃ ⇓ n => ⌜ (↑n : Nat) = vecLen v ⌝ ⦄ := by
  unfold alloc.vec.Vec.len vecLen CoreModels.rust_primitives.sequence.seq_len
  mvcgen

/-- `Vec::new` returns an empty vec. -/
@[spec]
theorem vec_new_spec (T : Type) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.new T
    ⦃ ⇓ v => ⌜ vecLen v = 0 ∧ v.1 = [] ⌝ ⦄ := by
  unfold alloc.vec.Vec.new rust_primitives.sequence.seq_empty vecLen
  mvcgen

/-- `Vec::with_capacity` returns an empty vec. -/
@[spec]
theorem vec_with_capacity_spec (T : Type) (c : Std.Usize) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.with_capacity T c
    ⦃ ⇓ v => ⌜ vecLen v = 0 ⌝ ⦄ := by
  unfold alloc.vec.Vec.with_capacity alloc.vec.Vec.new
    rust_primitives.sequence.seq_empty vecLen
  mvcgen

/-- `Vec::is_empty` returns `decide (vecLen v = 0)` — proved from the `seq_len` body. -/
@[spec]
theorem vec_is_empty_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.is_empty v
    ⦃ ⇓ b => ⌜ b = decide (vecLen v = 0) ⌝ ⦄ := by
  unfold alloc.vec.Vec.is_empty vecLen CoreModels.rust_primitives.sequence.seq_len
  mvcgen
  simp only [Aeneas.Std.Slice.length]
  scalar_tac

/-- `Vec::pop` never fails: on a nonempty vec it returns the last element and the vec with its
    last element dropped; on an empty vec it returns `None` and the vec unchanged. Proved from
    the `seq_len`/`seq_remove` bodies. -/
@[spec]
theorem vec_pop_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.pop v
    ⦃ ⇓ res => ⌜ res.2.1 = v.1.dropLast
        ∧ (v.1 ≠ [] → ∃ x, res.1 = core.option.Option.Some x ∧ v.1 = res.2.1 ++ [x]) ⌝ ⦄ := by
  unfold alloc.vec.Vec.pop CoreModels.rust_primitives.sequence.seq_len
    CoreModels.rust_primitives.sequence.seq_remove
  mvcgen
  case vc1.hQ =>
    -- Nonempty, in-bounds: `seq_remove` at `len − 1` is `take (len−1) ++ drop len`, i.e.
    -- `dropLast`, and the removed element is `getLast`.
    rename_i r hr h1 hlt
    have hrv : (↑r : Nat) = v.1.length - 1 := by scalar_tac
    have hpos : 0 < v.1.length := by scalar_tac
    have hne : v.1 ≠ [] := List.ne_nil_of_length_pos hpos
    have hdrop : List.drop ((↑r : Nat) + 1) v.1 = [] :=
      List.drop_eq_nil_of_le (by omega)
    have htake : List.take (↑r : Nat) v.1 = v.1.dropLast := by
      rw [List.dropLast_eq_take, hrv]
    refine ⟨by rw [hdrop, List.append_nil, htake], fun _ => ⟨_, rfl, ?_⟩⟩
    rw [hdrop, List.append_nil, htake]
    conv_lhs => rw [← List.dropLast_append_getLast hne]
    congr 1
    simp [List.getLast_eq_getElem, List.get_eq_getElem, hrv]
  case vc2.hQ =>
    -- `len − 1 < length` cannot fail on a nonempty vec.
    exfalso; scalar_tac
  case vc3.h_fail =>
    -- `len > 0` and `len < 1` is absurd.
    exfalso; scalar_tac
  case vc4.hQ =>
    -- Empty vec: `dropLast [] = []` and the implication is vacuous.
    have hnil : v.1 = [] := by
      have h0 : v.1.length = 0 := by scalar_tac
      exact List.eq_nil_of_length_eq_zero h0
    simp [hnil]

/-- `<Vec<T> as Deref<[T]>>::deref` exposes the vec's contents as a slice with the same list.
    Proved from the `seq_to_slice` body (the identity on the underlying `Seq`). -/
@[spec]
theorem vec_deref_slice_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
    ⦃ ⇓ s => ⌜ s.val = v.1 ⌝ ⦄ := by
  unfold alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref alloc.vec.Vec.as_slice
    CoreModels.rust_primitives.sequence.seq_to_slice
  mvcgen

/-- `<Vec<T> as Index<usize>>::index`: succeeds (no out-of-bounds panic) when the index is within
    the vec's length. Pinned to the concrete `usize` `SliceIndex` instance
    (`core.Usize.Insts.CoreSliceIndexSliceIndexSliceT`) rather than quantified over instances: a
    quantified form is false over `CoreModels`' arbitrary-`get` structure, since `SliceIndex`'s
    `get` field is an arbitrary `I → Slice T → Result (Option Output)` that may `fail`/return
    `None` (→ `panic`) regardless of the bound. Every call site in the treemath development passes
    exactly this concrete instance, whose `get` returns `ok (some elem)` in bounds, so the spec is
    discharged from the upstream bodies. -/
@[spec]
theorem vec_index_spec {T : Type} (v : alloc.vec.Vec T) (i : Std.Usize) :
    ⦃ ⌜ (↑i : Nat) < vecLen v ⌝ ⦄
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT T) v i
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
    CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
  simp only [CoreModels.core.Usize.Insts.CoreSliceIndexSliceIndexSliceT.get,
    alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref, alloc.vec.Vec.as_slice,
    CoreModels.rust_primitives.sequence.seq_to_slice,
    CoreModels.rust_primitives.slice.slice_length,
    CoreModels.rust_primitives.slice.slice_index]
  mvcgen

/-- `Vec::push` grows the length by one and appends `x` (panic-free below the size ceiling).
    Proved against the upstream `rust_primitives.sequence.seq_push` body: its dependent `if` on
    `(v.1 ++ [x]).length ≤ Usize.max` is discharged by `mvcgen`'s branch split, with the
    `maximumSizeExceeded` arm contradicting the precondition. -/
@[spec]
theorem vec_push_spec {T : Type} (v : alloc.vec.Vec T) (x : T) :
    ⦃ ⌜ vecLen v < Std.Usize.max ⌝ ⦄
    alloc.vec.Vec.push v x
    ⦃ ⇓ v' => ⌜ vecLen v' = vecLen v + 1 ∧ v'.1 = v.1 ++ [x] ⌝ ⦄ := by
  unfold alloc.vec.Vec.push CoreModels.rust_primitives.sequence.seq_push
  mvcgen
  case vc1.hQ =>
    -- Success branch: the new `Seq`'s list is literally `v.1 ++ [x]`, one longer.
    simp +zetaDelta [vecLen, Aeneas.Std.Slice.length]
  case vc2.hQ =>
    -- `maximumSizeExceeded` branch is dead: `(v.1 ++ [x]).length = vecLen v + 1 ≤ Usize.max`.
    exfalso
    simp +zetaDelta only [vecLen, Aeneas.Std.Slice.length, List.length_append,
      List.length_cons, List.length_nil] at *
    omega

/-- `<[T]>::iter` yields an iterator whose remaining elements are exactly the slice's. Proved
    from the `seq_from_slice` body (the identity). Phrased on `.val` directly rather than via
    `sliceIterElems` (`Openmls.Proofs.Common`); the two are definitionally equal. -/
@[spec]
theorem slice_iter_of_slice_spec {T : Type} (s : Slice T) :
    ⦃ ⌜ True ⌝ ⦄
    core.slice.Slice.iter s
    ⦃ ⇓ it => ⌜ it.val = s.val ⌝ ⦄ := by
  unfold CoreModels.core.slice.Slice.iter CoreModels.rust_primitives.sequence.seq_from_slice
  mvcgen

/-- Draw-loop lemma for `Iterator::all`, phrased on the *upstream* `CoreModels.core.iterAllCount`
    (`CoreModels/Core/FunsEpilogue.lean`) — the structural list recursion that the upstream `all`
    body runs.

    Under the hypothesis that the closure is *pure and state-preserving* on every element of `l`
    (`call_mut f e = ok (P e, f)` — note the same `f` on both sides, which is what lets the
    induction hypothesis reuse it), the draw loop terminates with the boolean `l.all P`. Only the
    boolean is pinned down: the consumed count is existentially quantified, since Rust's
    short-circuit means it depends on where the first `false` sits, and the sole consumer's
    postcondition does not observe the advanced iterator. Deliberately NOT registered `@[spec]`:
    it is a pure-value lemma about the recursion, consumed only by `slice_iter_all_spec` below. -/
theorem slice_iter_all_count_spec {T F : Type}
    (inst : core.ops.function.FnMut F T Bool) (P : T → Bool) (f : F) :
    ∀ l : List T, (∀ e ∈ l, inst.call_mut f e = ok (P e, f)) →
      ∃ n, CoreModels.core.iterAllCount inst f l = ok (l.all P, n) := by
  intro l
  induction l with
  | nil => intro _; exact ⟨0, rfl⟩
  | cons x rest ih =>
    intro hcall
    have hx : inst.call_mut f x = ok (P x, f) := hcall x (by simp)
    cases hP : P x with
    | false =>
      -- Short-circuit: the loop stops after one element and `List.all` is `false`.
      exact ⟨1, by simp [CoreModels.core.iterAllCount, hx, hP]⟩
    | true =>
      obtain ⟨n, hn⟩ := ih (fun e he => hcall e (by simp [he]))
      exact ⟨n + 1, by simp [CoreModels.core.iterAllCount, hx, hP, hn]⟩

/-- `<slice::Iter<'_, T> as Iterator>::all` returns the conjunction of a pure, state-preserving
    predicate over the iterator's remaining elements. Discharged, not admitted: the subject is the
    *upstream* `CoreModels` definition of Rust's short-circuiting draw loop (a real definition, not
    a bare `axiom`), and the value follows from `slice_iter_all_count_spec` above. Registered
    `@[spec]`, so
    `mvcgen` picks it up automatically — it is what discharges the `all` step of the extracted
    `direct_path.post` in `Proofs.lean`. -/
@[spec]
theorem slice_iter_all_spec {T F : Type}
    (inst : core.ops.function.FnMut F T Bool) (iter : core.slice.iter.Iter T) (f : F)
    (P : T → Bool)
    (hcall : ∀ e ∈ sliceIterElems iter, inst.call_mut f e = ok (P e, f)) :
    ⦃ ⌜ True ⌝ ⦄
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all inst iter f
    ⦃ ⇓ r => ⌜ r.1 = (sliceIterElems iter).all P ⌝ ⦄ := by
  -- Phrased on `iter.val` rather than `sliceIterElems iter` (definitionally the same list): the
  -- model's returned iterator carries a `length ≤ Usize.max` proof about `iter.val`, so rewriting
  -- that occurrence would make the motive ill-typed.
  obtain ⟨n, hn⟩ := slice_iter_all_count_spec inst P f iter.val hcall
  -- The advanced iterator is left existential: the postcondition only observes the boolean.
  have hok : ∃ it', core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
      inst iter f = ok (iter.val.all P, it') := by
    unfold core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.all
    -- `simp only` (not `rw`) so the upstream body's `let s := iter` is zeta-reduced first, the
    -- draw-loop call rewritten by `hn`, and the resulting `ok`-bind discharged.
    simp only [hn]
    exact ⟨_, rfl⟩
  obtain ⟨it', hit'⟩ := hok
  exact triple_of_ok hit' rfl

/-- `<[T]>::reverse` never fails and returns the element-reversed slice. Its subject is the
    *upstream* `CoreModels.core.slice.Slice.reverse` (delegating to
    `rust_primitives.slice.slice_reverse`), a real definition rather than a bare `axiom`, so the
    contract is proved here rather than admitted.

    The postcondition carries the full permutation fact `res.val = s.val.reverse`, not just
    panic-freedom — and hence, via `List.length_reverse`, the length fact that
    `common_direct_path` needs, given that `deref_mut_slice_spec` states the faithful *identity*
    write-back rather than a "length is preserved" clause. -/
@[spec]
theorem reverse_slice_spec {T : Type} (s : Slice T) :
    ⦃ ⌜ True ⌝ ⦄
    core.slice.Slice.reverse s
    ⦃ ⇓ res => ⌜ res.val = s.val.reverse ⌝ ⦄ := by
  unfold CoreModels.core.slice.Slice.reverse CoreModels.rust_primitives.slice.slice_reverse
  mvcgen

/-- `<Vec<T> as DerefMut>::deref_mut` never fails: it exposes the vec's contents as a slice and
    the write-back closure is the IDENTITY. Discharged, not admitted: the subject is the *upstream*
    `CoreModels` body `fun self => self.as_mut_slice`, which goes through
    `rust_primitives.sequence.seq_to_mut_slice = fun s => ok (s, fun ss => ss)`, so the slice view
    literally *is* `v`'s contents and writing back any `s'` returns `s'`.

    The statement is faithful to that identity write-back, and deliberately does not claim the
    weaker-looking `∀ s', vecLen (back s') = vecLen v` ("a `&mut [T]` view cannot resize"): the
    identity write-back returns a vec of `s'`'s length, not of `v`'s, so that clause is false of
    the canonical model. The form below is strictly more informative and needs no trust.

    Note on the bind shape: the extracted `let (s, back) ← deref_mut …` is a *tuple-destructuring*
    bind, so `mvcgen` introduces the result as a single opaque variable and may leave the bind's
    `match` on it unreduced — independent of this postcondition's shape. -/
@[spec]
theorem deref_mut_slice_spec {T : Type} (v : alloc.vec.Vec T) :
    ⦃ ⌜ True ⌝ ⦄
    alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut v
    ⦃ ⇓ ⟨s, back⟩ => ⌜ s.val = v.val ∧ ∀ s', (back s').val = s'.val ⌝ ⦄ := by
  unfold alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut
    CoreModels.alloc.vec.Vec.as_mut_slice CoreModels.rust_primitives.sequence.seq_to_mut_slice
  -- Both conjuncts are `rfl` after `mvcgen` normalises the `ok (s, fun ss => ss)` body: the
  -- residual goal is literally `True ∧ ∀ s', True`.
  mvcgen
  · simp

/-- `Vec::append` moves `other`'s elements onto the end of `self` and leaves `other` empty.
    Fails only when the concatenation would exceed `Usize.max` (the `seq_concat` body). -/
@[spec]
theorem vec_append_spec {T : Type} (self other : alloc.vec.Vec T) :
    ⦃ ⌜ self.1.length + other.1.length ≤ Std.Usize.max ⌝ ⦄
    alloc.vec.Vec.append self other
    ⦃ ⇓ r => ⌜ r.1.1 = self.1 ++ other.1 ∧ r.2.1 = [] ⌝ ⦄ := by
  unfold alloc.vec.Vec.append CoreModels.rust_primitives.sequence.seq_concat
    CoreModels.rust_primitives.sequence.seq_empty
  mvcgen
  -- Only the `maximumSizeExceeded` branch survives; it contradicts the precondition.
  exfalso
  rename_i hpre hcomb hgt
  have hc : hcomb = self.1 ++ other.1 := rfl
  rw [hc, List.length_append] at hgt
  omega

/-- `u32::is_multiple_of` (the upstream `CoreModels` model) as a partial-contract: total, and
    equal to the divisibility test `x % y == 0`.

    The upstream body branches on the divisor explicitly —
    `if y = 0 then ok (x = 0) else do let i ← x % y; ok (i = 0)` — so the walk is a case split
    rather than a bare `partialSpec_ok`. On `y = 0` the branch matches the postcondition because
    `Nat`'s `_ % 0 = id`, so `x.val % 0 = 0 ↔ x.val = 0`; on `y ≠ 0` the monadic remainder cannot
    fail (`Aeneas.Std.U32.rem_spec`) and its value is `x.val % y.val`.

    Deliberately *unregistered*: it is the single source of truth from which both the total
    `is_multiple_of_spec` and the generic `u32_is_multiple_of_mvcgen_spec` below are derived. -/
theorem u32_is_multiple_of_partialSpec (x y : Std.U32) :
    Aeneas.Std.WP.partialSpec (core.num.U32.is_multiple_of x y)
      (fun b => b = decide (x.val % y.val = 0))
      (fun _ => False) False := by
  -- Both branches compare a `u32` against the literal `0`, while the postcondition speaks about
  -- the `Nat` value; `UScalar` val-injectivity bridges the two.
  have hzero : ∀ z : Std.U32, (z = 0#u32) ↔ ((↑z : Nat) = 0) := by
    intro z
    constructor
    · intro h; rw [h]; rfl
    · intro h; scalar_tac
  unfold CoreModels.core.num.U32.is_multiple_of
  by_cases hy : y = 0#u32
  · -- Divisor zero: the branch answers `x == 0`, which is the postcondition since `_ % 0 = id`.
    subst hy
    simp [Aeneas.Std.WP.partialSpec_ok, hzero]
  · -- Divisor nonzero: the monadic remainder cannot fail, and its value is `x.val % y.val`.
    rw [if_neg hy]
    have hy' : (↑y : Nat) ≠ 0 := by scalar_tac
    have h := Aeneas.Std.U32.rem_spec (y := y) x
    revert h
    cases hr : (x % y : Aeneas.Std.Result Std.U32) with
    | ok i => simp_all [Aeneas.Std.WP.partialSpec]
    | fail e => cases e <;> simp_all [Aeneas.Std.WP.partialSpec]
    | div => simp_all [Aeneas.Std.WP.partialSpec]

/-- `u32::is_multiple_of` returns exactly the divisibility test `x % y == 0`. Proved, not
    admitted, against the *upstream* `CoreModels` body, which is total: the `y = 0` branch is a
    pure `ok` and the `y ≠ 0` branch's remainder cannot fail. Derived from
    `u32_is_multiple_of_partialSpec`.

    Registered `@[spec]`: unlike `u32_pow_spec` / `leading_zeros_spec`, this ⇓ total is NOT
    subsumed by `u32_is_multiple_of_mvcgen_spec` in practice — `direct_path.spec.proof` needs the
    `x % y = 0` (not `decide`) hypothesis shape this form produces, so both are registered. -/
@[spec]
theorem is_multiple_of_spec (x y : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    core.num.U32.is_multiple_of x y
    ⦃ ⇓ b => ⌜ b = (x.val % y.val = 0) ⌝ ⦄ := by
  refine triple_of_partialSpec (u32_is_multiple_of_partialSpec x y) _ ?_ (by simp) (by simp)
  intro r hr
  simp [Aeneas.Std.willYield, hr]

/-- `u32::div_ceil x y = ⌈x/y⌉`, characterised as `(x + y - 1) / y`, panic-free exactly when the
    divisor is nonzero (Rust panics on division by zero). Proved, not admitted, against the
    *upstream* `CoreModels` body, which is the monadic transcription of Rust's implementation
    `{ let d = self / rhs; let r = self % rhs; if r > 0 { d + 1 } else { d } }`.

    Three obligations come out of that body for `0 < y`: the division and the remainder both
    succeed, and the `d + 1` increment cannot overflow — the latter because the `r > 0` guard
    forces `x % y ≠ 0`, whence `x/y + 1 ≤ x ≤ u32::MAX`. The value then matches
    `(x + y - 1) / y` by the `key` bridge below (note the branch polarity: upstream tests
    `r > 0`, i.e. the *nonzero*-remainder case comes first). -/
@[spec]
theorem u32_div_ceil_spec (x y : Std.U32) :
    ⦃ ⌜ 0 < (↑y : Nat) ⌝ ⦄
    core.num.U32.div_ceil x y
    ⦃ ⇓ r => ⌜ (↑r : Nat) = (↑x + ↑y - 1) / ↑y ⌝ ⦄ := by
  -- The arithmetic bridge: `a/b + (1 if a%b ≠ 0) = (a + b - 1)/b` for `0 < b`.
  have key : ∀ a b : Nat, 0 < b → a / b + (if a % b = 0 then 0 else 1) = (a + b - 1) / b := by
    intro a b hb
    have hab : a + b - 1 = a + (b - 1) := by omega
    have hm : a % b < b := Nat.mod_lt _ hb
    rw [hab, Nat.add_div hb, Nat.div_eq_of_lt (show b - 1 < b by omega),
      Nat.mod_eq_of_lt (show b - 1 < b by omega)]
    split <;> split <;> omega
  -- No overflow on the `d + 1` branch: a nonzero remainder forces `a/b + 1 ≤ a`.
  have le1 : ∀ a b : Nat, 0 < b → a % b ≠ 0 → a / b + 1 ≤ a := by
    intro a b hb hm
    have h1 : b * (a / b) + a % b = a := Nat.div_add_mod a b
    have h2 : a / b ≤ b * (a / b) := Nat.le_mul_of_pos_left _ hb
    omega
  unfold CoreModels.core.num.U32.div_ceil
  mvcgen
  case vc1.h_ok =>
    -- Nonzero remainder (`r > 0`): the result is `x/y + 1`, which `key` identifies with
    -- `(x + y - 1)/y`.
    rename_i hy d hd m hm hgt s hs
    have hm0 : (↑x : Nat) % ↑y ≠ 0 := by scalar_tac
    have h1 := key (↑x) (↑y) hy
    rw [if_neg hm0] at h1
    have hone : ((1#u32 : Std.U32) : Nat) = 1 := by scalar_tac
    rw [hs, hd, hone]
    exact h1
  case vc2.h_fail =>
    -- The `d + 1` increment cannot overflow: a nonzero remainder forces `x/y + 1 ≤ x ≤ u32::MAX`.
    exfalso
    rename_i hy d hd m hm hgt hov
    have hm0 : (↑x : Nat) % ↑y ≠ 0 := by scalar_tac
    have hle := le1 (↑x) (↑y) hy hm0
    have hone : ((1#u32 : Std.U32) : Nat) = 1 := by scalar_tac
    rw [hd, hone] at hov
    scalar_tac
  case vc3.hQ =>
    -- Zero remainder (`¬ r > 0`): the result is exactly `x/y`, and `key`'s `if` takes `0`.
    rename_i hy d hd m hm hgt
    have hm0 : (↑x : Nat) % ↑y = 0 := by scalar_tac
    have h1 := key (↑x) (↑y) hy
    rw [if_pos hm0] at h1
    rw [hd]
    simpa using h1
  -- The two division-by-zero branches contradict the `0 < ↑y` precondition.
  all_goals (exfalso; scalar_tac)

/-! ### `cmp`

`CoreModels` supplies *concrete* `Ord` instances for every scalar type: `core.<Ty>.Insts.CoreCmpOrd`
is a structure literal whose `cmp` field is the standalone pure def
`core.<Ty>.Insts.CoreCmpOrd.cmp = fun self other => if self < other then ok Less else if
self > other then ok Greater else ok Equal`. So the comparison operations below are total and their
specs are proved here rather than admitted. -/

/-- `core::cmp::min` for `usize`: returns a value bounded above by both arguments.
    The `CoreModels` body of `cmp.min` calls `OrdInst.cmp v1 v2` and then returns `v1` on
    `Less`/`Equal` and `v2` on `Greater`; for `core.Usize.Insts.CoreCmpOrd` that `cmp` is the pure
    `<`/`>` cascade, so each branch's returned value is bounded by both
    arguments and no branch can fail. Proved, not admitted. -/
@[spec]
theorem min_usize_spec (a b : Std.Usize) :
    ⦃ ⌜ True ⌝ ⦄
    core.cmp.min core.Usize.Insts.CoreCmpOrd a b
    ⦃ ⇓ m => ⌜ (↑m : Nat) ≤ ↑a ∧ (↑m : Nat) ≤ ↑b ⌝ ⦄ := by
  unfold core.cmp.min core.Usize.Insts.CoreCmpOrd core.Usize.Insts.CoreCmpOrd.cmp
  mvcgen
  -- One goal per `Ordering` branch, each already carrying the `</¬<` facts that decided it;
  -- the returned value is syntactically `a` or `b`, so the bounds are pure scalar arithmetic.
  all_goals scalar_tac

/-- `<u32 as Ord>::cmp` is panic-free. It is the `cmp` projection out of the concrete
    `CoreModels` instance `core.U32.Insts.CoreCmpOrd`, i.e. the pure `<`/`>` cascade
    `core.U32.Insts.CoreCmpOrd.cmp`, so it never fails. Proved, not admitted. -/
@[spec]
theorem u32_cmp_spec (a b : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄ core.U32.Insts.CoreCmpOrd.cmp a b ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold core.U32.Insts.CoreCmpOrd.cmp
  mvcgen

/-! ### Body walks for the `CoreModels` `u32` models

`leading_zeros` and `pow` are the only two `CoreModels` operations whose semantics needs a
real walk through the model's body. The two (three, counting the `pow` corollary) theorems
here are the **single source of truth** for that walk: the total `⇓` specs immediately below,
the generic `@[spec]` mvcgen contracts at the end of this file, and the `log2` /
`TreeSize.valid` walks in `PartialSpecs.lean` are all derived from them.

Deliberately *unregistered* (no `@[spec]`, no `@[step]`): they are plumbing for the specs, not
rules for the automation. -/

/-- `u32::leading_zeros` (the `CoreModels` model) as a partial-contract. The model is a pure
`ok`, so the failure and divergence predicates are `False`. -/
theorem u32_leading_zeros_partialSpec (x : Std.U32) :
    Aeneas.Std.WP.partialSpec (core.num.U32.leading_zeros x)
      (fun r => (↑r : Nat) = if x.val = 0 then 32 else 31 - Nat.log 2 x.val)
      (fun _ => False) False := by
  unfold CoreModels.core.num.U32.leading_zeros
    CoreModels.rust_primitives.arithmetic.leading_zeros_u32
  simp only [Aeneas.Std.WP.partialSpec_ok]
  unfold Aeneas.Std.core.num.U32.leading_zeros Aeneas.Std.BitVec.leadingZeros
  simp only [Aeneas.Std.UScalar.val]
  have hbv : (x.bv = 0) ↔ (x.bv.toNat = 0) := by
    rw [BitVec.toNat_eq]; rfl
  rcases eq_or_ne x.bv.toNat 0 with h | h
  · rw [if_pos (hbv.mpr h), if_pos h]
    show (BitVec.ofNat 32 32).toNat = 32
    rw [BitVec.toNat_ofNat]
  · rw [if_neg (fun hc => h (hbv.mp hc)), if_neg h]
    show (BitVec.ofNat 32 (32 - Nat.log 2 x.bv.toNat - 1)).toNat = 31 - Nat.log 2 x.bv.toNat
    rw [BitVec.toNat_ofNat]
    omega

/-- `u32::pow` (the `CoreModels` model) as a partial-contract: computes `x ^ exp` exactly, and
fails — with `integerOverflow`, and only then — when the result does not fit in a `u32`. -/
theorem u32_pow_partialSpec (x exp : Std.U32) :
    Aeneas.Std.WP.partialSpec (core.num.U32.pow x exp)
      (fun r => (↑r : Nat) = (↑x : Nat) ^ (↑exp : Nat))
      (fun e => e = Aeneas.Std.Error.integerOverflow ∧
        Std.UScalar.max .U32 < (↑x : Nat) ^ (↑exp : Nat))
      False := by
  unfold CoreModels.core.num.U32.pow CoreModels.rust_primitives.arithmetic.pow_u32
  have heq := Std.UScalar.tryMk_eq Std.UScalarTy.U32 ((↑x : Nat) ^ (↑exp : Nat))
  cases hc : Std.UScalar.tryMk Std.UScalarTy.U32 ((↑x : Nat) ^ (↑exp : Nat)) <;>
    simp_all [Std.UScalar.inBounds]
  refine ⟨?_, by scalar_tac⟩
  have hne : ¬ ((↑x : Nat) ^ (↑exp : Nat) < 4294967296) := by omega
  simp_all [Std.UScalar.tryMk, Result.ofOption, Std.UScalar.tryMkOpt]

/-- `u32::pow` under the hypothesis that the result fits: the failure branch of
`u32_pow_partialSpec` is ruled out, so the contract becomes total. -/
theorem u32_pow_partialSpec_total (x exp : Std.U32)
    (h : (↑x : Nat) ^ (↑exp : Nat) ≤ Std.UScalar.max .U32) :
    Aeneas.Std.WP.partialSpec (core.num.U32.pow x exp)
      (fun r => (↑r : Nat) = (↑x : Nat) ^ (↑exp : Nat))
      (fun _ => False) False := by
  have hp := u32_pow_partialSpec x exp
  revert hp
  cases core.num.U32.pow x exp <;> simp_all [Aeneas.Std.WP.partialSpec]

/-- `u32::leading_zeros` returns the number of leading zero bits: `32` for `0`,
    else `31 - ⌊log₂ x⌋`. Total (the `CoreModels` model is a pure `ok`), so proved here.
    Derived from `u32_leading_zeros_partialSpec`.

    Unregistered corollary; the generic-Q `u32_leading_zeros_mvcgen_spec` is the registered
    authority. -/
theorem leading_zeros_spec (x : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    core.num.U32.leading_zeros x
    ⦃ ⇓ r => ⌜ (↑r : Nat) = if x.val = 0 then 32 else 31 - Nat.log 2 x.val ⌝ ⦄ := by
  refine triple_of_partialSpec (u32_leading_zeros_partialSpec x) _ ?_ (by simp) (by simp)
  intro r hr
  simpa [Aeneas.Std.willYield] using hr

/-- `List.find?` over `List.range w` returns the least index satisfying `P`, provided that
    index is in range. Auxiliary for `trailingOnes_bv_eq_tones` (unregistered). -/
private theorem find?_range_eq_some {P : Nat → Bool} {m : Nat} (hP : P m)
    (hmin : ∀ j, j < m → ¬ P j) : ∀ w, m < w → (List.range w).find? P = some m := by
  intro w hw
  induction w with
  | zero => omega
  | succ n ih =>
    rw [List.range_succ, List.find?_append]
    rcases Nat.lt_or_ge m n with h | h
    · rw [ih h]; rfl
    · have hmn : m = n := by omega
      subst hmn
      rw [List.find?_eq_none.2 (fun y hy => hmin y (List.mem_range.1 hy))]
      simp [hP]

/-- Bridge lemma: the upstream `CoreModels` bit-vector trailing-ones count (a `List.find?`
    over `List.range 32` on the complemented bit-vector) agrees with the `Nat.find`-based
    `tones` of the scalar's value. Unregistered. -/
theorem trailingOnes_bv_eq_tones (x : Std.U32) :
    CoreModels.BitVec.trailingOnes x.bv = tones (↑x : Nat) := by
  have hbit : ∀ i, (~~~x.bv).getLsbD i = (decide (i < 32) && !(↑x : Nat).testBit i) := by
    intro i; rw [BitVec.getLsbD_not]; rfl
  set m := tones (↑x : Nat) with hm
  have hspec : (↑x : Nat).testBit m = false := Nat.find_spec (tones_ex _)
  have hmin : ∀ j, j < m → (↑x : Nat).testBit j = true := by
    intro j hj; simpa using Nat.find_min (tones_ex _) hj
  unfold CoreModels.BitVec.trailingOnes CoreModels.BitVec.trailingZeros
  rcases Nat.lt_or_ge m 32 with h | h
  · rw [find?_range_eq_some (P := fun i => (~~~x.bv).getLsbD i) (m := m)
      (by simp only [hbit]; simp [h, hspec])
      (fun j hj => by simp only [hbit]; simp [hmin j hj]) 32 h]
  · have hlt : (↑x : Nat) < 2 ^ 32 := x.hBounds
    have hx : (↑x : Nat) = 2 ^ 32 - 1 := by
      refine Nat.eq_of_testBit_eq fun j => ?_
      rw [Nat.testBit_two_pow_sub_one]
      rcases Nat.lt_or_ge j 32 with hj | hj
      · simp [hmin j (by omega), hj]
      · simp [Nat.testBit_lt_two_pow (Nat.lt_of_lt_of_le hlt (Nat.pow_le_pow_right (by norm_num) hj)),
          show ¬ j < 32 by omega]
    have hm32 : m = 32 := by rw [hm, hx, tones_pow_sub_one]
    rw [List.find?_eq_none.2 (fun y hy => by
      have := List.mem_range.1 hy
      simp only [hbit]; simp [hmin y (by omega)])]
    simp [hm32]

/-- `u32::trailing_ones` returns the trailing-ones count `tones ↑x`. Total: the upstream
    `CoreModels` body is a pure `ok` of `CoreModels.BitVec.trailingOnes x.bv`, so this is
    proved (not admitted) against that body, with `trailingOnes_bv_eq_tones` above doing the
    bit-vector ↔ `tones` bridging.
    An upstream-PR candidate for a registered spec in `CoreModels`. -/
@[spec]
theorem trailing_ones_spec (x : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄
    core.num.U32.trailing_ones x
    ⦃ ⇓ r => ⌜ (↑r : Nat) = tones (↑x : Nat) ⌝ ⦄ := by
  -- The bit-vector count never overflows the `u32` it is injected into: it is at most the
  -- bit-vector width, `32`.
  have hle : CoreModels.BitVec.trailingOnes x.bv ≤ 32 := by
    unfold CoreModels.BitVec.trailingOnes CoreModels.BitVec.trailingZeros
    split
    · next i hi => have := List.mem_range.1 (List.mem_of_find?_eq_some hi); omega
    · omega
  unfold core.num.U32.trailing_ones
    CoreModels.rust_primitives.arithmetic.trailing_ones_u32 CoreModels.utrailing_ones
  mvcgen
  · rw [← trailingOnes_bv_eq_tones]
    simp [Aeneas.Std.UScalar.val]
    -- residual in-rangeness side goal of the `#uscalar` injection
    omega

/-- `u32::pow` computes `x ^ exp` exactly, as long as the result fits in a `u32`.
    Derived from `u32_pow_partialSpec_total`.

    Unregistered corollary; the generic-Q `u32_pow_mvcgen_spec` is the registered authority. -/
theorem u32_pow_spec (x exp : Std.U32) :
    ⦃ ⌜ (↑x : Nat) ^ (↑exp : Nat) ≤ Std.UScalar.max .U32 ⌝ ⦄
    core.num.U32.pow x exp
    ⦃ ⇓ r => ⌜ (↑r : Nat) = (↑x : Nat) ^ (↑exp : Nat) ⌝ ⦄ := by
  intro h
  refine triple_of_partialSpec (u32_pow_partialSpec_total x exp h) _ ?_ (by simp) (by simp)
    trivial
  intro r hr
  simpa [Aeneas.Std.willYield] using hr

/-! ### `Iterator::collect` over a `map` adapter

   `FunsExternal.lean` models `<Map<I, F> as Iterator>::collect` as upstream's generic
   `Iterator::collect` provided method at the `Map` adapter's `Iterator` instance — a real
   definition, no axiom. The two contracts the treemath development consumes
   (`slice_iter_map_collect_spec`, `into_map_collect_spec`) are therefore discharged here, against
   that model, by induction over the drain loop.

   Everything between here and those two contracts is private scaffolding: a non-dependent
   characterisation of a sequence-backed iterator's `next` (`SeqIterNextSpec`, satisfied by both
   the slice iterator and the vec `IntoIter`), and two inductions over `core.iterDrain` — a
   functional one and a success-only one. The success-only one is *not* derived from the
   functional one: recovering a total function from per-element existentials would need choice
   on a possibly-empty, non-`Inhabited` element type. -/

/-- Non-dependent characterisation of a sequence-backed iterator's `next`: on an empty sequence
    it yields `None` and the receiver unchanged; on `x :: rest` it yields `Some x` and the tail.
    Phrased over the underlying list (`s.val = …`) rather than over a reconstructed subtype
    value, so that instantiations never have to match up `Subtype` proofs. -/
private def SeqIterNextSpec {T : Type} (next : Slice T → Result (core.option.Option T × Slice T)) :
    Prop :=
  (∀ s : Slice T, s.val = [] → next s = ok (core.option.Option.None, s)) ∧
  (∀ (s : Slice T) (x : T) (rest : List T), s.val = x :: rest →
    ∃ h : rest.length ≤ Usize.max,
      next s = ok (core.option.Option.Some x, ⟨rest, h⟩))

/-- The shared slice iterator's `next` satisfies `SeqIterNextSpec`. -/
private theorem slice_iter_next_spec {T : Type} :
    SeqIterNextSpec (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next
      (T := T)) := by
  constructor
  · intro s hs
    simp [core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next,
      rust_primitives.sequence.seq_len, Slice.len, hs, Usize.ofNatCore, Usize.ofNat]
    rfl
  · intro s x rest hs
    have hlen : rest.length ≤ Usize.max := by
      have := s.property; rw [hs] at this; simp at this; omega
    refine ⟨hlen, ?_⟩
    simp [core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next,
      rust_primitives.sequence.seq_len, rust_primitives.sequence.seq_remove, Slice.len, hs]
    rfl

/-- The vec `IntoIter`'s `next` satisfies `SeqIterNextSpec`. -/
private theorem into_iter_next_spec {T : Type} :
    SeqIterNextSpec (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
      (T := T)) := by
  constructor
  · intro s hs
    simp [alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next,
      rust_primitives.sequence.seq_len, Slice.len, hs, Usize.ofNatCore, Usize.ofNat]
    rfl
  · intro s x rest hs
    have hlen : rest.length ≤ Usize.max := by
      have := s.property; rw [hs] at this; simp at this; omega
    refine ⟨hlen, ?_⟩
    simp [alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next,
      rust_primitives.sequence.seq_remove, rust_primitives.sequence.seq_len, Slice.len, hs]
    rfl

/-- Sequence-agnostic repackaging of `SeqIterNextSpec`: `toL` reads off an iterator's remaining
    elements, and the `cons` case only claims *some* successor iterator whose remaining elements
    are the tail — no subtype value is ever reconstructed. -/
private def SeqIterNext {I T : Type} (next : I → Result (core.option.Option T × I))
    (toL : I → List T) : Prop :=
  (∀ it, toL it = [] → next it = ok (core.option.Option.None, it)) ∧
  (∀ it x rest, toL it = x :: rest →
    ∃ it', toL it' = rest ∧ next it = ok (core.option.Option.Some x, it'))

/-- Every sequence-backed iterator satisfying `SeqIterNextSpec` satisfies `SeqIterNext` at
    `toL := Subtype.val`. -/
private theorem seqIterNext_of_seqIterNextSpec {T : Type}
    {next : Slice T → Result (core.option.Option T × Slice T)} (h : SeqIterNextSpec next) :
    SeqIterNext next Subtype.val := by
  refine ⟨h.1, ?_⟩
  intro it x rest hit
  obtain ⟨hlen, hnext⟩ := h.2 it x rest hit
  exact ⟨⟨rest, hlen⟩, rfl, hnext⟩

/-- Functional drain: the accumulator loop of `core.iterDrain`, run on the `map` adapter over a
    `SeqIterNext` iterator with a pure, state-preserving closure, consumes exactly the remaining
    elements and conses their images onto the accumulator (hence the `reverse`). Induction on the
    element list; the iterator is an arbitrary value constrained by `toL it = l`, and the loop body
    is abstract (`body`/`hbody`) so that `Aeneas.Std.loop.eq_def` leaves a rewritable
    `body (s, a)` rather than a beta-reduced application. -/
private theorem drain_loop_map_functional {I T O F : Type}
    (IteratorInst : core.iter.traits.iterator.Iterator I T)
    (FnMutInst : CoreModels.core.ops.function.FnMut F T O)
    (toL : I → List T) (hnext : SeqIterNext IteratorInst.next toL) (g : T → O) (f : F)
    (body : core.iter.adapters.map.Map I F × List O →
      Result (ControlFlow (core.iter.adapters.map.Map I F × List O) (List O)))
    (hbody : ∀ (s : core.iter.adapters.map.Map I F) (a : List O), body (s, a) = do
      let (o, it') ← core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
        IteratorInst FnMutInst s
      match o with
      | core.option.Option.Some x => ok (ControlFlow.cont (it', x :: a))
      | core.option.Option.None => ok (ControlFlow.done a)) :
    ∀ (l : List T) (it : I) (acc : List O), toL it = l →
      (∀ e ∈ l, FnMutInst.call_mut f e = ok (g e, f)) →
      Aeneas.Std.loop body (({ iter := it, f := f } : core.iter.adapters.map.Map I F), acc)
      = ok ((l.map g).reverse ++ acc) := by
  intro l
  induction l with
  | nil =>
    intro it acc hit _
    have hb : body (({ iter := it, f := f } : core.iter.adapters.map.Map I F), acc)
        = ok (ControlFlow.done acc) := by
      rw [hbody]
      simp [core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next, hnext.1 it hit]
    rw [Aeneas.Std.loop.eq_def, hb]
    simp
  | cons x rest ih =>
    intro it acc hit hcall
    obtain ⟨it', hit', hnx⟩ := hnext.2 it x rest hit
    have hb : body (({ iter := it, f := f } : core.iter.adapters.map.Map I F), acc)
        = ok (ControlFlow.cont
            (({ iter := it', f := f } : core.iter.adapters.map.Map I F), g x :: acc)) := by
      rw [hbody]
      simp [core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next, hnx,
        hcall x (by simp)]
    rw [Aeneas.Std.loop.eq_def, hb]
    exact (ih it' (g x :: acc) hit' (fun e he => hcall e (by simp [he]))).trans (by simp)

/-- Panic-freedom-only drain, with the resulting length. Proved by its own induction rather than
    derived from `drain_loop_map_functional`: turning per-element existentials into a total
    function would need choice on a possibly-empty, non-`Inhabited` element type. -/
private theorem drain_loop_map_success {I T O F : Type}
    (IteratorInst : core.iter.traits.iterator.Iterator I T)
    (FnMutInst : CoreModels.core.ops.function.FnMut F T O)
    (toL : I → List T) (hnext : SeqIterNext IteratorInst.next toL) (f : F)
    (body : core.iter.adapters.map.Map I F × List O →
      Result (ControlFlow (core.iter.adapters.map.Map I F × List O) (List O)))
    (hbody : ∀ (s : core.iter.adapters.map.Map I F) (a : List O), body (s, a) = do
      let (o, it') ← core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
        IteratorInst FnMutInst s
      match o with
      | core.option.Option.Some x => ok (ControlFlow.cont (it', x :: a))
      | core.option.Option.None => ok (ControlFlow.done a)) :
    ∀ (l : List T) (it : I) (acc : List O), toL it = l →
      (∀ e ∈ l, ∃ o, FnMutInst.call_mut f e = ok (o, f)) →
      ∃ out : List O,
        Aeneas.Std.loop body (({ iter := it, f := f } : core.iter.adapters.map.Map I F), acc)
        = ok out ∧ out.length = l.length + acc.length := by
  intro l
  induction l with
  | nil =>
    intro it acc hit _
    have hb : body (({ iter := it, f := f } : core.iter.adapters.map.Map I F), acc)
        = ok (ControlFlow.done acc) := by
      rw [hbody]
      simp [core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next, hnext.1 it hit]
    refine ⟨acc, ?_, by simp⟩
    rw [Aeneas.Std.loop.eq_def, hb]
  | cons x rest ih =>
    intro it acc hit hcall
    obtain ⟨it', hit', hnx⟩ := hnext.2 it x rest hit
    obtain ⟨o, ho⟩ := hcall x (by simp)
    have hb : body (({ iter := it, f := f } : core.iter.adapters.map.Map I F), acc)
        = ok (ControlFlow.cont
            (({ iter := it', f := f } : core.iter.adapters.map.Map I F), o :: acc)) := by
      rw [hbody]
      simp [core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next, hnx, ho]
    obtain ⟨out, hout, hlen⟩ := ih it' (o :: acc) hit' (fun e he => hcall e (by simp [he]))
    refine ⟨out, ?_, by simp at hlen ⊢; omega⟩
    rw [Aeneas.Std.loop.eq_def, hb]
    exact hout

/-- `core.iterDrain` over the `map` adapter, functional version. The `show` step is a defeq
    unfolding of `core.iterDrain` (`CoreModels/Core/FunsEpilogue.lean`) that names the loop body
    explicitly, which is what lets the abstract-body induction above be applied. -/
private theorem iterDrain_map_functional {I T O F : Type}
    (IteratorInst : core.iter.traits.iterator.Iterator I T)
    (FnMutInst : CoreModels.core.ops.function.FnMut F T O)
    (toL : I → List T) (hnext : SeqIterNext IteratorInst.next toL) (g : T → O) (f : F)
    (l : List T) (it : I) (hit : toL it = l)
    (hcall : ∀ e ∈ l, FnMutInst.call_mut f e = ok (g e, f)) :
    core.iterDrain
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator IteratorInst FnMutInst)
      ({ iter := it, f := f } : core.iter.adapters.map.Map I F)
    = ok (l.map g) := by
  have h := drain_loop_map_functional IteratorInst FnMutInst toL hnext g f
    (fun (s, a) => do
      let (o, it') ← core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
        IteratorInst FnMutInst s
      match o with
      | core.option.Option.Some x => ok (ControlFlow.cont (it', x :: a))
      | core.option.Option.None => ok (ControlFlow.done a))
    (fun _ _ => rfl) l it [] hit hcall
  show (do
    let acc ← Aeneas.Std.loop
      (fun (s, a) => do
        let (o, it') ← core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
          IteratorInst FnMutInst s
        match o with
        | core.option.Option.Some x => ok (ControlFlow.cont (it', x :: a))
        | core.option.Option.None => ok (ControlFlow.done a))
      (({ iter := it, f := f } : core.iter.adapters.map.Map I F), ([] : List O))
    ok acc.reverse) = ok (l.map g)
  rw [h]
  simp

/-- `core.iterDrain` over the `map` adapter, panic-freedom-only version (with the length of the
    drained list, which is what bounds the target `Vec`'s length). -/
private theorem iterDrain_map_success {I T O F : Type}
    (IteratorInst : core.iter.traits.iterator.Iterator I T)
    (FnMutInst : CoreModels.core.ops.function.FnMut F T O)
    (toL : I → List T) (hnext : SeqIterNext IteratorInst.next toL) (f : F)
    (l : List T) (it : I) (hit : toL it = l)
    (hcall : ∀ e ∈ l, ∃ o, FnMutInst.call_mut f e = ok (o, f)) :
    ∃ out : List O,
      core.iterDrain
        (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator IteratorInst FnMutInst)
        ({ iter := it, f := f } : core.iter.adapters.map.Map I F)
      = ok out ∧ out.length = l.length := by
  obtain ⟨out, hout, hlen⟩ := drain_loop_map_success IteratorInst FnMutInst toL hnext f
    (fun (s, a) => do
      let (o, it') ← core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
        IteratorInst FnMutInst s
      match o with
      | core.option.Option.Some x => ok (ControlFlow.cont (it', x :: a))
      | core.option.Option.None => ok (ControlFlow.done a))
    (fun _ _ => rfl) l it [] hit hcall
  refine ⟨out.reverse, ?_, by simp [hlen]⟩
  show (do
    let acc ← Aeneas.Std.loop
      (fun (s, a) => do
        let (o, it') ← core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
          IteratorInst FnMutInst s
        match o with
        | core.option.Option.Some x => ok (ControlFlow.cont (it', x :: a))
        | core.option.Option.None => ok (ControlFlow.done a))
      (({ iter := it, f := f } : core.iter.adapters.map.Map I F), ([] : List O))
    ok acc.reverse) = ok out.reverse
  rw [hout]
  simp

/-- Collecting a pure, state-preserving closure mapped over a slice iterator yields exactly the
    mapped element list. Discharged against the concrete `collect` model in `FunsExternal.lean`,
    via `iterDrain_map_functional`, so it costs no trust. -/
theorem slice_iter_map_collect_spec {T O F : Type}
    (inst : core.ops.function.FnMut F T O) (iter : core.slice.iter.Iter T) (f : F) (g : T → O)
    (hcall : ∀ e ∈ sliceIterElems iter, inst.call_mut f e = ok (g e, f)) :
    ⦃ ⌜ True ⌝ ⦄
    (do
      let m ← core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.map inst iter f
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT T) inst
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator O) m)
    ⦃ ⇓ v => ⌜ v.1 = (sliceIterElems iter).map g ⌝ ⦄ := by
  have hlen : ((sliceIterElems iter).map g).length ≤ Usize.max := by
    simpa [sliceIterElems] using iter.property
  have hdrain := iterDrain_map_functional
    (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT T) inst
    sliceIterElems (seqIterNext_of_seqIterNextSpec slice_iter_next_spec) g f
    (sliceIterElems iter) iter rfl hcall
  refine triple_of_ok (v := (⟨(sliceIterElems iter).map g, hlen⟩ : alloc.vec.Vec O)) ?_ rfl
  show (do
    let l ← core.iterDrain
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
        (core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT T) inst)
      ({ iter := iter, f := f } : core.iter.adapters.map.Map (core.slice.iter.Iter T) F)
    alloc.vec.ofList l) = _
  rw [hdrain]
  have hsrc : (sliceIterElems iter).length ≤ Usize.max := iter.property
  simp [alloc.vec.ofList, hsrc]
  rfl

/-- Collecting a closure `f` over a vec via `into_iter`/`map`/`collect` is panic-free when `f` is
    panic-free on every element. Generic over the element type and closure — purely a `core` fact.
    Discharged against the concrete `collect` model in `FunsExternal.lean`, via
    `iterDrain_map_success`. The `sibling` instance used by `copath` is *derived* (not admitted) in
    `Proofs.lean`. -/
theorem into_map_collect_spec {T : Type} (v : alloc.vec.Vec T) (f : T → Result T)
    (hsafe : ∀ e ∈ v.1, ⦃ ⌜ True ⌝ ⦄ f e ⦃ ⇓ _ => ⌜ True ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄
    (do
      let ii ← alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter v
      let m ← alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.map
          (BuiltinFnMut T T) ii f
      core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.collect
        (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator T)
        (BuiltinFnMut T T)
        (alloc.vec.Vec.Insts.CoreIterTraitsCollectFromIterator T) m)
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  have hcall : ∀ e ∈ v.1, ∃ o : T,
      (CollectFnMut.toFnMut (BuiltinFnMut T T) :
        CoreModels.core.ops.function.FnMut (T → Result T) T T).call_mut f e = ok (o, f) := by
    intro e he
    obtain ⟨o, ho⟩ := triple_noThrow_exists_ok (hsafe e he)
    refine ⟨o, ?_⟩
    -- `Aeneas.Std.BuiltinFnMut`'s closure state is literally constant, so `call_mut` is just the
    -- Rust call; `instCollectFnMutAeneas` re-packages it field-for-field (both steps are defeq).
    show (do let y ← f e; ok (y, f)) = ok (o, f)
    rw [ho]
    rfl
  obtain ⟨out, hout, hlenout⟩ := iterDrain_map_success
    (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator T)
    (CollectFnMut.toFnMut (BuiltinFnMut T T) :
      CoreModels.core.ops.function.FnMut (T → Result T) T T)
    Subtype.val (seqIterNext_of_seqIterNextSpec into_iter_next_spec) f v.1 v rfl hcall
  have hlen : out.length ≤ Usize.max := by rw [hlenout]; exact v.property
  refine triple_of_ok (v := (⟨out, hlen⟩ : alloc.vec.Vec T)) ?_ trivial
  show (do
    let l ← core.iterDrain
      (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
        (alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator T)
        (CollectFnMut.toFnMut (BuiltinFnMut T T) :
          CoreModels.core.ops.function.FnMut (T → Result T) T T))
      ({ iter := v, f := f } : core.iter.adapters.map.Map (alloc.vec.into_iter.IntoIter T)
        (T → Result T))
    alloc.vec.ofList l) = _
  rw [hout]
  simp [alloc.vec.ofList, hlen]
  rfl

end openmls

/-! ### Partial-correctness contracts for stepping in hypothesis position

The total (`⇓`) specs above are what `mvcgen` needs in *goal* position. But when
`hax_mvcgen` steps a do-block in *hypothesis* position — a pre/post already known to have
succeeded — a total spec forces its precondition to be discharged as a side goal, even
though success is given. This section supplies contracts that avoid those side goals, in
two different shapes depending on who owns the operation:

* **`Aeneas.Std` subjects** (casts, shifts, `massert`) are stated with
  `Aeneas.Std.WP.partialSpec` and marked `@[step]`, which is the upstream Aeneas
  convention: the attribute derives both a `.step_spec` (total, side conditions as
  hypotheses) and a `.mvcgen_spec` (generic over `PostCond`, serving `⇓` *and* `⇓?` goals
  with no obligation in the partial case). Arithmetic (`+ - * / %`) already has such
  theorems in `Aeneas/Std/Scalar/Ops/`; casts, shifts and `massert` do not, so the six
  below are **candidates for an upstream Aeneas PR as-is**.

* **`CoreModels` subjects** (the hax core-model `u32::{pow, leading_zeros,
  is_multiple_of}` our extraction actually calls) are necessarily project-local, so rather
  than registering more `@[step]` lemmas we state the `@[spec]` triple directly, in the
  same shape `@[step]` would have derived: generic `Q : PostCond _ Result.postShape` with
  one `willYield`/`willFail` hypothesis per outcome. Compare
  `@Aeneas.Std.U8.add_spec.mvcgen_spec`. These do NOT replace the total specs above, which other
  proofs in this development depend on.
-/

namespace Aeneas.Std

open Result Error WP

/-- `UScalar.cast` (Rust `as` between unsigned integers) truncates or zero-extends, and
`lift` wraps the result in `ok`, so it never fails and never diverges.

Partial-correctness counterpart of `Aeneas.Std.UScalar.cast_inBounds_spec`
(`Aeneas/Std/Scalar/Casts.lean`), which assumes `x.val ≤ UScalar.max tgt_ty`. That
hypothesis becomes a spurious side goal whenever a cast is stepped in hypothesis position,
where success is already given. Stating the truncating semantics directly removes it. -/
@[step]
theorem UScalar.cast_partialSpec {src_ty : UScalarTy} (tgt_ty : UScalarTy)
    (x : UScalar src_ty) :
    partialSpec (lift (UScalar.cast tgt_ty x))
      (fun y => (↑y : Nat) = (↑x : Nat) % 2 ^ tgt_ty.numBits)
      (fun _ => False)
      False := by
  simp only [lift, partialSpec_ok, UScalar.cast, UScalar.val, BitVec.truncate_eq_setWidth,
    BitVec.toNat_setWidth]

/-- `x <<< y` on unsigned integers with an unsigned shift amount: succeeds exactly when the
shift amount is below the source width, and then truncates modulo `UScalar.size ty0`.

Partial-correctness counterpart of `Aeneas.Std.UScalar.ShiftLeft_spec`
(`Aeneas/Std/Scalar/Bitwise.lean`), whose `hy : y.val < ty0.numBits` hypothesis is a
spurious side goal when the shift is stepped in hypothesis position. -/
@[step]
theorem UScalar.ShiftLeft_partialSpec {ty0 ty1} (x : UScalar ty0) (y : UScalar ty1) :
    partialSpec (x <<< y)
      (fun z => (↑z : Nat) = ((↑x : Nat) <<< (↑y : Nat)) % UScalar.size ty0)
      (fun | .integerOverflow => ty0.numBits ≤ (↑y : Nat) | _ => False)
      False := by
  simp only [HShiftLeft.hShiftLeft, shiftLeft_UScalar, shiftLeft]
  split <;> rename_i h
  · simp only [partialSpec_ok, UScalar.val, UScalar.size, BitVec.shiftLeft_eq,
      BitVec.toNat_shiftLeft]
    rfl
  · simp only [partialSpec_fail]; omega

/-- `x >>> y` on unsigned integers with an unsigned shift amount: succeeds exactly when the
shift amount is below the source width.

Partial-correctness counterpart of `Aeneas.Std.UScalar.ShiftRight_spec`
(`Aeneas/Std/Scalar/Bitwise.lean`); see `UScalar.ShiftLeft_partialSpec` for the motivation. -/
@[step]
theorem UScalar.ShiftRight_partialSpec {ty0 ty1} (x : UScalar ty0) (y : UScalar ty1) :
    partialSpec (x >>> y)
      (fun z => (↑z : Nat) = (↑x : Nat) >>> (↑y : Nat))
      (fun | .integerOverflow => ty0.numBits ≤ (↑y : Nat) | _ => False)
      False := by
  simp only [HShiftRight.hShiftRight, shiftRight_UScalar, shiftRight]
  split <;> rename_i h
  · simp only [partialSpec_ok, UScalar.val, BitVec.ushiftRight_eq, BitVec.toNat_ushiftRight]
    rfl
  · simp only [partialSpec_fail]; omega

/-- `x <<< y` where the shift amount is a *signed* integer (how `i32` shift amounts are
extracted): fails on a negative amount or an amount at/above the source width. -/
@[step]
theorem UScalar.ShiftLeft_IScalar_partialSpec {ty0 ty1} (x : UScalar ty0) (y : IScalar ty1) :
    partialSpec (x <<< y)
      (fun z => (↑z : Nat) = ((↑x : Nat) <<< y.toNat) % UScalar.size ty0)
      (fun | .integerOverflow => (↑y : Int) < 0 ∨ ty0.numBits ≤ y.toNat | _ => False)
      False := by
  simp only [HShiftLeft.hShiftLeft, shiftLeft_IScalar]
  split <;> rename_i h
  · simp only [shiftLeft]
    split <;> rename_i h'
    · simp only [partialSpec_ok, UScalar.val, UScalar.size, BitVec.shiftLeft_eq,
        BitVec.toNat_shiftLeft]
      rfl
    · simp only [partialSpec_fail]; omega
  · simp only [partialSpec_fail]; omega

/-- `x >>> y` where the shift amount is a *signed* integer: fails on a negative amount or an
amount at/above the source width. -/
@[step]
theorem UScalar.ShiftRight_IScalar_partialSpec {ty0 ty1} (x : UScalar ty0) (y : IScalar ty1) :
    partialSpec (x >>> y)
      (fun z => (↑z : Nat) = (↑x : Nat) >>> y.toNat)
      (fun | .integerOverflow => (↑y : Int) < 0 ∨ ty0.numBits ≤ y.toNat | _ => False)
      False := by
  simp only [HShiftRight.hShiftRight, shiftRight_IScalar]
  split <;> rename_i h
  · simp only [shiftRight]
    split <;> rename_i h'
    · simp only [partialSpec_ok, UScalar.val, BitVec.ushiftRight_eq, BitVec.toNat_ushiftRight]
      rfl
    · simp only [partialSpec_fail]; omega
  · simp only [partialSpec_fail]; omega

/-- `massert b` succeeds iff `b` holds, and otherwise fails with `assertionFailure`.

The total spec forces `b` to be proved; in hypothesis position the assertion has already
gone through, so the partial form lets `b` be *recovered* instead of discharged. -/
@[step]
theorem massert_partialSpec (b : Prop) [Decidable b] :
    partialSpec (massert b)
      (fun _ => b)
      (fun | .assertionFailure => ¬ b | _ => False)
      False := by
  simp only [massert]
  split <;> rename_i h
  · simp only [partialSpec_ok]; exact h
  · simp only [partialSpec_fail]; exact h

end Aeneas.Std

namespace openmls

-- `triple_of_partialSpec` (the bridge each of the three contracts below goes through) lives in
-- `Openmls.Proofs.Common`; the `partialSpec` facts they are built from are earlier in this file.

/-- `u32::pow` (the `CoreModels` model our extraction calls, not `Aeneas.Std`'s): computes
`x ^ exp` exactly, and fails with `integerOverflow` only when the result does not fit in a
`u32`.

Partial-correctness counterpart of `u32_pow_spec` above, whose
`↑x ^ ↑exp ≤ UScalar.max .U32` precondition is the most costly spurious side goal in the
treemath development when a `pow` is stepped in hypothesis position. Stated in the shape
`@[step]` derives (cf. `@Aeneas.Std.U8.add_spec.mvcgen_spec`) so that the overflow bound is
*recovered* from the failure branch rather than discharged up front. -/
@[spec]
theorem u32_pow_mvcgen_spec (x exp : Std.U32)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (↑x : Nat) ^ (↑exp : Nat) →
      Aeneas.Std.willYield r Q)
    (h_fail : Std.UScalar.max .U32 < (↑x : Nat) ^ (↑exp : Nat) →
      Aeneas.Std.willFail Aeneas.Std.Error.integerOverflow Q) :
    ⦃ ⌜ True ⌝ ⦄ core.num.U32.pow x exp ⦃ Q ⦄ := by
  have hp := u32_pow_partialSpec x exp
  refine triple_of_partialSpec hp Q h_ok ?_ (by simp)
  rintro e ⟨rfl, hlt⟩
  exact h_fail hlt

/-- `u32::leading_zeros` (the `CoreModels` model): genuinely total — the model is a pure
`ok` — so there is no failure hypothesis at all.

Partial-correctness counterpart of `leading_zeros_spec` above. The total spec already has a
`True` precondition, so this adds no logical information; it exists purely so that stepping
a `leading_zeros` in hypothesis position produces no success obligation. -/
@[spec]
theorem u32_leading_zeros_mvcgen_spec (x : Std.U32)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32,
      (↑r : Nat) = (if x.val = 0 then 32 else 31 - Nat.log 2 x.val) →
      Aeneas.Std.willYield r Q) :
    ⦃ ⌜ True ⌝ ⦄ core.num.U32.leading_zeros x ⦃ Q ⦄ := by
  exact triple_of_partialSpec (u32_leading_zeros_partialSpec x) Q h_ok (by simp) (by simp)

/-- `u32::is_multiple_of` is a total divisibility test, so again there is no failure
hypothesis. Total even though the upstream `CoreModels` body is a two-branch `if` over a
monadic remainder: the `y = 0` branch is a pure `ok`, and for `y ≠ 0` the remainder cannot
fail — that is exactly what `u32_is_multiple_of_partialSpec` (earlier in this file, proved
against the upstream body) establishes.

Partial-correctness counterpart of `is_multiple_of_spec` above; as with `leading_zeros` it
adds no logical information and exists only to suppress the success obligation when stepped
in hypothesis position. -/
@[spec]
theorem u32_is_multiple_of_mvcgen_spec (x y : Std.U32)
    (Q : PostCond Bool Aeneas.Std.Result.postShape)
    (h_ok : ∀ b : Bool, b = decide (x.val % y.val = 0) →
      Aeneas.Std.willYield b Q) :
    ⦃ ⌜ True ⌝ ⦄ core.num.U32.is_multiple_of x y ⦃ Q ⦄ :=
  triple_of_partialSpec (u32_is_multiple_of_partialSpec x y) Q h_ok (by simp) (by simp)


end openmls
