-- [openmls]: PROVED mvcgen-style `@[spec]` triples for the treemath *spec-vocabulary* functions —
-- the helpers (`valid`, `log2`, `u32`, `leaf_count`, `parent_count`, …) that appear inside
-- extraction-generated preconditions and postconditions.
--
-- Purpose: when `hax_mvcgen` steps a pre/post in HYPOTHESIS position, success is already given, so
-- a total spec's precondition becomes a spurious side goal. These triples are stated in the shape
-- `@[step]` derives for `partialSpec` theorems (generic `Q : PostCond α Result.postShape` with one
-- `willYield`/`willFail` hypothesis per outcome; cf. `@Aeneas.Std.U8.add_spec.mvcgen_spec`), so a
-- failure branch *recovers* its bound instead of discharging it. Companion to the `CoreModels` trio
-- at the end of `MissingCoreSpecs.lean`, which this file imports: the `CoreModels` `u32` body walks
-- (`u32_leading_zeros_partialSpec`, `u32_pow_partialSpec{,_total}`) live there and are reused here
-- rather than repeated.
--
-- Every theorem here is discharged (no `sorry`), so this file is NOT part of the trusted audit
-- surface. Hand-written; not regenerated by extraction.
--
-- NOTE: `level` is deliberately absent — its body is `trailing_ones()` (no loop), so stepping it
-- goes through the registered `level.spec_pure` in `Proofs.lean`, at the cost of discharging its
-- `< 2^30` hypothesis at each site.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
import Openmls.Proofs.BitMath
import Openmls.Proofs.MissingCoreSpecs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

namespace binary_tree.array_representation.treemath

-- The generic bridge `triple_of_partialSpec`, used throughout, lives in `Openmls.Proofs.Common`.

/-- Specialisation of `openmls.triple_of_partialSpec` for the (common) case of a total operation
whose body has already been reduced to `ok v`: the triple is exactly `willYield v Q`.
Named apart from `openmls.triple_of_ok` (the `x = ok v` / plain-`Prop` postcondition flavour in
`Common`), which it would otherwise shadow inside this namespace. -/
theorem triple_of_ok_willYield {α} (v : α) (Q : PostCond α Aeneas.Std.Result.postShape)
    (h_ok : Aeneas.Std.willYield v Q) :
    ⦃ ⌜ True ⌝ ⦄ (ok v : Result α) ⦃ Q ⦄ := by
  simpa [Triple, _root_.Std.Do.WP.wp, PredTrans.apply, Aeneas.Std.willYield] using h_ok

/-- A total `spec` yields the partial contract with empty failure/divergence cases. Lets us reuse
Aeneas' `@[step]`-derived `.step_spec` lemmas (which discharge the failure side conditions once,
here) to build the partial contracts below. -/
theorem partialSpec_of_spec {α} {x : Result α} {P : α → Prop}
    (h : Aeneas.Std.WP.spec x P) :
    Aeneas.Std.WP.partialSpec x P (fun _ => False) False := by
  obtain ⟨v, hv, hP⟩ := Aeneas.Std.WP.spec_imp_exists h
  simp [hv, hP, Aeneas.Std.WP.partialSpec]

/-! ### `valid` predicates (all total — they only read constants and compare) -/

/-- `LeafNodeIndex::valid` is `self ≤ MAX_LEAF = 2^29 − 1`. Total: it reads a constant and
compares, so there is no failure branch and hence no `willFail` hypothesis — stepping it in
hypothesis position produces no side goal. -/
@[spec]
theorem LeafNodeIndex.valid_mvcgen_spec (self : LeafNodeIndex)
    (Q : PostCond Bool Aeneas.Std.Result.postShape)
    (h_ok : ∀ b : Bool, b = decide ((↑self : Nat) ≤ 2 ^ 29 - 1) →
      Aeneas.Std.willYield b Q) :
    ⦃ ⌜ True ⌝ ⦄ LeafNodeIndex.valid self ⦃ Q ⦄ := by
  have hc : binary_tree.array_representation.treemath.MAX_LEAF = ok 536870911#u32 := by
    unfold MAX_LEAF MAX_TREE_INDEX MAX_TREE_SIZE; rfl
  unfold LeafNodeIndex.valid
  rw [hc]
  exact triple_of_ok_willYield _ Q (h_ok _ (by norm_num))

/-- `ParentNodeIndex::valid` is `self ≤ MAX_PARENT = 2^29 − 2`. Total, as for `LeafNodeIndex`. -/
@[spec]
theorem ParentNodeIndex.valid_mvcgen_spec (self : ParentNodeIndex)
    (Q : PostCond Bool Aeneas.Std.Result.postShape)
    (h_ok : ∀ b : Bool, b = decide ((↑self : Nat) ≤ 2 ^ 29 - 2) →
      Aeneas.Std.willYield b Q) :
    ⦃ ⌜ True ⌝ ⦄ ParentNodeIndex.valid self ⦃ Q ⦄ := by
  have hc : binary_tree.array_representation.treemath.MAX_PARENT = ok 536870910#u32 := by
    unfold MAX_PARENT MAX_LEAF MAX_TREE_INDEX MAX_TREE_SIZE; rfl
  unfold ParentNodeIndex.valid
  rw [hc]
  exact triple_of_ok_willYield _ Q (h_ok _ (by norm_num))

/-- `TreeNodeIndex::valid` dispatches on the constructor to the leaf/parent bound. Total. -/
@[spec]
theorem TreeNodeIndex.valid_mvcgen_spec (self : TreeNodeIndex)
    (Q : PostCond Bool Aeneas.Std.Result.postShape)
    (h_ok : ∀ b : Bool, b = (match self with
        | TreeNodeIndex.Leaf l => decide ((↑l : Nat) ≤ 2 ^ 29 - 1)
        | TreeNodeIndex.Parent p => decide ((↑p : Nat) ≤ 2 ^ 29 - 2)) →
      Aeneas.Std.willYield b Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeNodeIndex.valid self ⦃ Q ⦄ := by
  unfold TreeNodeIndex.valid
  cases self with
  | Leaf l => exact LeafNodeIndex.valid_mvcgen_spec l Q (fun b hb => h_ok b (by simpa using hb))
  | Parent p => exact ParentNodeIndex.valid_mvcgen_spec p Q (fun b hb => h_ok b (by simpa using hb))

/-- `TreeSize::u32` is the identity injection. Total. -/
@[spec]
theorem TreeSize.u32_mvcgen_spec (self : TreeSize)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (↑self : Nat) → Aeneas.Std.willYield r Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeSize.u32 self ⦃ Q ⦄ := by
  unfold TreeSize.u32
  exact triple_of_ok_willYield _ Q (h_ok _ rfl)

/-- `TreeSize::parent_count` is `self / 2`. Total: the divisor is the literal `2`, so the
division cannot fail. -/
@[spec]
theorem TreeSize.parent_count_mvcgen_spec (self : TreeSize)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (↑self : Nat) / 2 → Aeneas.Std.willYield r Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeSize.parent_count self ⦃ Q ⦄ := by
  unfold TreeSize.parent_count
  refine triple_of_partialSpec (p_fail := fun _ => False) (p_div := False) ?_ Q h_ok
    (by simp) (by simp)
  refine partialSpec_of_spec ?_
  have h := Std.U32.div_spec.step_spec (x := self) (y := 2#u32) (by simp)
  exact h

/-- Weakening of a partial-contract in both the success and the failure predicate. -/
theorem partialSpec_weaken {α} {x : Result α} {P P' : α → Prop}
    {pf pf' : Aeneas.Std.Error → Prop}
    (h : Aeneas.Std.WP.partialSpec x P pf False)
    (hP : ∀ a, P a → P' a) (hF : ∀ e, pf e → pf' e) :
    Aeneas.Std.WP.partialSpec x P' pf' False := by
  cases x <;> simp_all [Aeneas.Std.WP.partialSpec]

/-- Chaining for partial-contracts that share a failure predicate (both steps may fail). -/
theorem partialSpec_bind_fail {α β} {x : Result α} {f : α → Result β}
    {P : α → Prop} {R : β → Prop} {pf : Aeneas.Std.Error → Prop}
    (hx : Aeneas.Std.WP.partialSpec x P pf False)
    (hf : ∀ a, P a → Aeneas.Std.WP.partialSpec (f a) R pf False) :
    Aeneas.Std.WP.partialSpec (x >>= f) R pf False := by
  cases x <;> simp_all [Aeneas.Std.WP.partialSpec]

/-! ### Index identities -/

/-- `LeafNodeIndex::u32` is the identity injection. Total. -/
@[spec]
theorem LeafNodeIndex.u32_mvcgen_spec (self : LeafNodeIndex)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (↑self : Nat) → Aeneas.Std.willYield r Q) :
    ⦃ ⌜ True ⌝ ⦄ LeafNodeIndex.u32 self ⦃ Q ⦄ := by
  unfold LeafNodeIndex.u32
  exact triple_of_ok_willYield _ Q (h_ok _ rfl)

/-- `ParentNodeIndex::u32` is the identity injection. Total. -/
@[spec]
theorem ParentNodeIndex.u32_mvcgen_spec (self : ParentNodeIndex)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (↑self : Nat) → Aeneas.Std.willYield r Q) :
    ⦃ ⌜ True ⌝ ⦄ ParentNodeIndex.u32 self ⦃ Q ⦄ := by
  unfold ParentNodeIndex.u32
  exact triple_of_ok_willYield _ Q (h_ok _ rfl)

-- Elsewhere: the `MAX_*` / `MIN_TREE_SIZE` value specs are in `Proofs.lean` (`MAX_*.spec_value`,
-- one per constant, no `willYield` layer); the `to_tree_index` pair, `TreeNodeIndex.u32` and
-- `TreeSize.leaf_count` triples are in `PureSpecs.lean` (single `@[spec]` per transparent function).

-- The two `CoreModels` body walks that the `log2` / `TreeSize.valid` proofs below step through —
-- `openmls.u32_leading_zeros_partialSpec` and `openmls.u32_pow_partialSpec_total` — are proved
-- once in `MissingCoreSpecs.lean` and used directly here.

/-! ### `log2` -/

/-- `log2 x = Nat.log 2 x`, for every `x` including `0` (the guarded branch returns `0`, and
`Nat.log 2 0 = 0`). Total: `leading_zeros` is a pure model, and `31 − lz x` cannot underflow
because `lz x ≤ 31` whenever `x ≠ 0`. -/
private theorem log2_partialSpec (x : Std.U32) :
    Aeneas.Std.WP.partialSpec (log2 x)
      (fun r => (↑r : Nat) = Nat.log 2 (↑x : Nat)) (fun _ => False) False := by
  unfold log2
  split
  · rename_i h
    have hx : (↑x : Nat) = 0 := by simp [h]
    simp only [Aeneas.Std.WP.partialSpec_ok, hx, Nat.log_zero_right]
    rfl
  · rename_i h
    have hx : (↑x : Nat) ≠ 0 := by
      intro hc; apply h; scalar_tac
    have hlog : Nat.log 2 (↑x : Nat) ≤ 31 := by
      have : (↑x : Nat) < 2 ^ 32 := by scalar_tac
      have := Nat.log_lt_of_lt_pow hx this
      omega
    refine partialSpec_bind_fail (u32_leading_zeros_partialSpec x) ?_
    intro lz hlz
    rw [if_neg hx] at hlz
    have h31 : ((31#u32 : Std.U32) : Nat) = 31 := by scalar_tac
    refine partialSpec_bind_fail (partialSpec_of_spec (Std.U32.sub_spec.step_spec ?_)) ?_
    · rw [hlz, h31]; omega
    · intro s hs
      have hsv : (↑s : Nat) = Nat.log 2 (↑x : Nat) := by rw [hs.1, h31, hlz]; omega
      have hcast : ((UScalar.cast .Usize s : Std.Usize) : Nat) = (↑s : Nat) := by scalar_tac
      simp only [Aeneas.Std.WP.partialSpec_ok, hcast, hsv]

/-- `log2 x = Nat.log 2 x`. Total, so no `willFail` hypothesis: stepping a `log2` in hypothesis
position produces no side goal. -/
@[spec]
theorem log2_mvcgen_spec (x : Std.U32) :
    ⦃ ⌜ True ⌝ ⦄ log2 x ⦃ ⇓ r => ⌜ (↑r : Nat) = Nat.log 2 (↑x : Nat) ⌝ ⦄ := by
  apply triple_of_partialSpec (log2_partialSpec x) <;> try grind

/-! ### `TreeSize.valid` -/

set_option maxRecDepth 8000 in
/-- `TreeSize::valid` is `1 ≤ self ∧ self ≤ MAX_TREE_SIZE ∧ self = 2^(log₂ self + 1) − 1`, where
`MAX_TREE_SIZE = 2^30` — note the guard is *inclusive* of `2^30`.

**Total.** The `self ≤ MAX_TREE_SIZE` guard runs BEFORE the `pow`, so under it `log₂ self ≤ 30`,
the exponent `log₂ self + 1 ≤ 31`, and `2^31 ≤ u32::MAX` — `tryMk` never fails. The `Usize → U32`
cast is in range and the final `− 1` cannot underflow. Hence no `willFail` hypothesis, and stepping
a `TreeSize.valid` in hypothesis position produces no side goal.

The body decides `self = i5` on `U32`; the characterization states the third conjunct on `Nat`,
which is equivalent by `UScalar` value injectivity. The postcondition is instantiated directly
(rather than universally quantified over the returned `Bool`) so that no `Decidable` instance is
ever forced open during elaboration.

**Internal stepping stone only** — the raw body-walk in the `Nat.log` fixpoint shape the extracted
code computes. `private` and NOT `@[spec]`-registered: that equation is self-referential in `self`
and makes `scalar_tac` diverge in consumers. The registered rule is `TreeSize.valid_mask_spec`
below, which transports this through `all_ones_iff_and_succ_eq_zero`. -/
private theorem TreeSize.valid_log_characterization (self : TreeSize)
    (Q : PostCond Bool Aeneas.Std.Result.postShape)
    (h_ok : Aeneas.Std.willYield
      (decide (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
        (↑self : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1)) Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeSize.valid self ⦃ Q ⦄ := by
  refine triple_of_partialSpec (p_fail := fun _ => False) (p_div := False)
    (p_ok := fun b => b = decide (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
      (↑self : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1))
    ?_ Q (fun b hb => by rw [hb]; exact h_ok) (by simp) (by simp)
  have h1u : ((1#u32 : Std.U32) : Nat) = 1 := by scalar_tac
  have h2u : ((2#u32 : Std.U32) : Nat) = 2 := by scalar_tac
  have hpow30 : (2 : Nat) ^ 30 - 1 = 1073741823 := by norm_num
  have hmax : binary_tree.array_representation.treemath.MAX_TREE_SIZE = ok 1073741823#u32 := by
    unfold MAX_TREE_SIZE; rfl
  unfold TreeSize.valid
  rw [hmax]
  simp only [bind_tc_ok]
  split
  · rename_i hmin
    have h1 : 1 ≤ (↑self : Nat) := by unfold MIN_TREE_SIZE at hmin; scalar_tac
    split
    · rename_i hle
      have h2 : (↑self : Nat) ≤ 2 ^ 30 - 1 := by rw [hpow30]; scalar_tac
      have hlog : Nat.log 2 (↑self : Nat) ≤ 30 := by
        have h2' : (↑self : Nat) ≤ 2 ^ 30 := le_trans h2 (by norm_num)
        have h := Nat.log_mono_right (b := 2) h2'
        rwa [Nat.log_pow (by omega)] at h
      refine partialSpec_bind_fail (log2_partialSpec self) ?_
      intro k hk
      refine partialSpec_bind_fail
        (partialSpec_of_spec (Aeneas.Std.UScalar.cast_inBounds_spec (src_ty := .Usize) .U32 k
          (by simp only [Aeneas.Std.UScalar.max, Std.UScalarTy.numBits]; omega))) ?_
      intro c hc
      · have hcv : (↑c : Nat) = Nat.log 2 (↑self : Nat) := by rw [hc, hk]
        refine partialSpec_bind_fail
          (partialSpec_of_spec (Std.U32.add_spec.step_spec (x := c) (y := 1#u32) ?_)) ?_
        · simp only [h1u, hcv]; scalar_tac
        · intro e he
          have hee : (↑e : Nat) = Nat.log 2 (↑self : Nat) + 1 := by rw [he, h1u, hcv]
          have hpb : (2 : Nat) ^ (↑e : Nat) ≤ 2 ^ 31 :=
            Nat.pow_le_pow_right (by omega) (by omega)
          refine partialSpec_bind_fail (u32_pow_partialSpec_total 2#u32 e ?_) ?_
          · simp only [Aeneas.Std.UScalar.max, Std.UScalarTy.numBits, h2u]; omega
          · intro pw hpw
            have hpwv : (↑pw : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) := by
              rw [hpw, h2u, hee]
            refine partialSpec_bind_fail
              (partialSpec_of_spec (Std.U32.sub_spec.step_spec (x := pw) (y := 1#u32) ?_)) ?_
            · rw [h1u, hpwv]
              have : 1 ≤ (2 : Nat) ^ (Nat.log 2 (↑self : Nat) + 1) := Nat.one_le_two_pow
              omega
            · intro d hd
              have hdv : (↑d : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1 := by
                rw [hd.1, h1u, hpwv]
              have hiff : (self = d) ↔ (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
                  (↑self : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1) := by
                refine ⟨fun hEq => ⟨h1, h2, ?_⟩, fun hC => ?_⟩
                · exact (by rw [hEq] : (↑self : Nat) = (↑d : Nat)).trans hdv
                · have hv : (↑self : Nat) = (↑d : Nat) := by rw [hC.2.2, hdv]
                  exact Aeneas.Std.UScalar.eq_of_val_eq hv
              exact decide_eq_decide.mpr hiff
    · rename_i hle
      have hnot : ¬ (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
          (↑self : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1) := by
        rintro ⟨-, hb, -⟩; rw [hpow30] at hb; scalar_tac
      exact (decide_eq_false hnot).symm
  · rename_i hmin
    unfold MIN_TREE_SIZE at hmin
    have hnot : ¬ (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
        (↑self : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1) := by
      rintro ⟨ha, -, -⟩; scalar_tac
    exact (decide_eq_false hnot).symm

/-- **The** spec for `TreeSize::valid` (the `@[spec]`-registered rule). Decides
`1 ≤ s ∧ s ≤ 2^30 − 1 ∧ s &&& (s+1) = 0`: the third conjunct is the all-ones bit test, NOT the
`Nat.log` fixpoint equation the extracted body computes (equivalent under `1 ≤ s` by
`all_ones_iff_and_succ_eq_zero`). The mask shape is the `scalar_tac`-safe one — no `Nat.log` reaches
a consumer's context, so no `set`/`clear_value` quarantine preamble is needed anywhere.

CONSUMER RECIPE: fires under plain `hax_mvcgen [...]`, no erasure pair. To *use* a mask hypothesis
quantitatively go through `all_ones_of_and_succ_eq_zero` (fresh existential witness); to *produce*
one from a known all-ones value use `and_succ_eq_zero_of_all_ones`. `&&&` is opaque to `omega`, so
an explicit `pow_succ`-expanded `have` is usually needed alongside.

**Total** (as the underlying body walk): no `willFail` hypothesis, so stepping this in hypothesis
position produces no side goal. -/
@[spec]
theorem TreeSize.valid_mask_spec (self : TreeSize)
    (Q : PostCond Bool Aeneas.Std.Result.postShape)
    (h_ok : Aeneas.Std.willYield
      (decide (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
        (↑self : Nat) &&& ((↑self : Nat) + 1) = 0)) Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeSize.valid self ⦃ Q ⦄ := by
  refine TreeSize.valid_log_characterization self Q ?_
  have hiff : (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
      (↑self : Nat) = 2 ^ (Nat.log 2 (↑self : Nat) + 1) - 1) ↔
      (1 ≤ (↑self : Nat) ∧ (↑self : Nat) ≤ 2 ^ 30 - 1 ∧
        (↑self : Nat) &&& ((↑self : Nat) + 1) = 0) := by
    constructor
    · rintro ⟨ha, hb, hc⟩
      exact ⟨ha, hb, (all_ones_iff_and_succ_eq_zero _ ha).mp hc⟩
    · rintro ⟨ha, hb, hc⟩
      exact ⟨ha, hb, (all_ones_iff_and_succ_eq_zero _ ha).mpr hc⟩
  rw [decide_eq_decide.mpr hiff]
  exact h_ok

end binary_tree.array_representation.treemath

end openmls
