-- [openmls]: treemath panic-freedom — the 19 proof obligations (the audit surface).
-- One theorem per obligation, statements verbatim 1:1 with
-- `Openmls/Extraction/ProofObligationsExplicit.lean`. Also holds the loop specs/invariants
-- (loop machinery lives here by design), the validated companion specs (`level.spec_pure`,
-- `parent.spec_value`, `direct_path.spec_pure`), the `sibling.pre` discharge helpers, and the
-- raw `attribute [spec]` block. Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
import Openmls.Proofs.BitMath
import Openmls.Proofs.PartialSpecs
import Openmls.Proofs.PureSpecs
import Openmls.Proofs.MissingCoreSpecs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

-- set_option maxRecDepth 2048

noncomputable section

namespace openmls
namespace binary_tree.array_representation.treemath

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false
set_option linter.unusedTactic false

-- DOUBLE AUTHORITY (build-verified, load-bearing).  This bare block registers extracted
-- *definitions* for body-unfolding; several of the ops below ALSO carry a hand `*_mvcgen_spec`
-- triple, and BOTH authorities are required.  `TreeSize.{u32,leaf_count,parent_count}`,
-- `{Leaf,Parent}NodeIndex.u32`, `TreeNodeIndex.u32` and both `to_tree_index` are irreducibly
-- double-live: the proofs of `parent`, `sibling`, `direct_path`, `lowest_common_ancestor` and
-- `is_node_in_tree` consume the unfolded body at some VCs and the triple at others, so dropping
-- the def registration here breaks them, and dropping the triples instead breaks even more.
-- mvcgen's resolution order between the two authorities is load-bearing: do not remove either side
-- without repairing the consuming proof bodies.
attribute [spec]
  pure
  MIN_TREE_SIZE
  --
  --log2
  is_node_in_tree
  --
  TreeSize.u32
  TreeSize.leaf_count
  TreeSize.parent_count
  --
  TreeNodeIndex.new
  TreeNodeIndex.u32
  --
  LeafNodeIndex.new
  LeafNodeIndex.u32
  LeafNodeIndex.to_tree_index
  LeafNodeIndex.from_tree_index
  --
  ParentNodeIndex.new
  ParentNodeIndex.u32
  ParentNodeIndex.to_tree_index
  ParentNodeIndex.from_tree_index

/-! ### Value specs for the treemath constants -/

@[spec]
theorem MAX_TREE_SIZE.spec_value :
    ⦃ ⌜ True ⌝ ⦄ MAX_TREE_SIZE ⦃ ⇓ r => ⌜ r = 1073741823#u32 ⌝ ⦄ := by
  hax_mvcgen [MAX_TREE_SIZE] <;> scalar_tac

@[spec]
theorem MAX_TREE_INDEX.spec_value :
    ⦃ ⌜ True ⌝ ⦄ MAX_TREE_INDEX ⦃ ⇓ r => ⌜ r = 1073741822#u32 ⌝ ⦄ := by
  hax_mvcgen [MAX_TREE_INDEX] <;> scalar_tac

@[spec]
theorem MAX_LEAF.spec_value :
    ⦃ ⌜ True ⌝ ⦄ MAX_LEAF ⦃ ⇓ r => ⌜ r = 536870911#u32 ⌝ ⦄ := by
  hax_mvcgen [MAX_LEAF] ; scalar_tac

@[spec]
theorem MAX_PARENT.spec_value :
    ⦃ ⌜ True ⌝ ⦄ MAX_PARENT ⦃ ⇓ r => ⌜ r = 536870910#u32 ⌝ ⦄ := by
  hax_mvcgen [MAX_PARENT] <;> scalar_tac

@[spec]
theorem MAX_LEAF_COUNT.spec_value :
    ⦃ ⌜ True ⌝ ⦄ MAX_LEAF_COUNT ⦃ ⇓ r => ⌜ r = 536870912#u32 ⌝ ⦄ := by
  hax_mvcgen [MAX_LEAF_COUNT] <;> scalar_tac

@[spec]
theorem MAX_ROOT_INDEX.spec_value :
    ⦃ ⌜ True ⌝ ⦄ MAX_ROOT_INDEX ⦃ ⇓ r => ⌜ r = 536870911#u32 ⌝ ⦄ := by
  hax_mvcgen [MAX_ROOT_INDEX] ; scalar_tac

/-! ### Loop specs: `common_direct_path` / `lowest_common_ancestor` -/

/-- The `common_direct_path` collection loop is panic-free: it indexes both paths only
    at positions `< len ≤ length`, and grows `common_path` by at most one per step. -/
@[spec]
theorem common_direct_path_loop_spec
    (x_path y_path common_path : alloc.vec.Vec ParentNodeIndex) (len i : Std.Usize)
    (hx : (↑len : Nat) ≤ vecLen x_path) (hy : (↑len : Nat) ≤ vecLen y_path)
    (hi : (↑i : Nat) ≤ ↑len) (hcp : vecLen common_path ≤ (↑i : Nat)) :
    ⦃ ⌜ True ⌝ ⦄
    common_direct_path_loop x_path y_path len common_path i
    ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
  unfold common_direct_path_loop
  apply loop_spec_measure
    (measure := fun p => (↑len : Nat) - p.2.val)
    (inv := fun p => (↑p.2 : Nat) ≤ ↑len ∧ vecLen p.1 ≤ (↑p.2 : Nat))
    (post := fun _ => True)
  · exact ⟨hi, hcp⟩
  · intro p hinv
    obtain ⟨cp, j⟩ := p
    obtain ⟨hj, hcpj⟩ := hinv
    simp only at hj hcpj ⊢
    have hxmax : vecLen x_path ≤ Std.Usize.max := x_path.property
    unfold common_direct_path_loop.body
    split
    · -- `j < len`
      rename_i hlt
      have hjlen : (↑j : Nat) < ↑len := by scalar_tac
      have hidxx : (↑j : Nat) < vecLen x_path := by omega
      have hidxy : (↑j : Nat) < vecLen y_path := by omega
      have hpush : vecLen cp < Std.Usize.max := by omega
      unfold ParentNodeIndex.Insts.CoreCmpPartialEqParentNodeIndex.eq
      mvcgen [vec_index_spec, vec_push_spec]
      all_goals scalar_tac
    · -- `j ≥ len`: stop
      mvcgen

/-- The `lowest_common_ancestor` while-loop (`loop0`), reached on two distinct even
    leaf tree-indices below `2^30`: it shifts both operands right until they coincide,
    counting steps in `k`. On exit `2 ≤ k ≤ 30` and `xn · 2^k < 2^30`. -/
@[spec]
theorem lca_loop0_spec (x1 y1 : Std.U32)
    (hx : (↑x1 : Nat) < 2 ^ 30) (hy : (↑y1 : Nat) < 2 ^ 30)
    (hex : (↑x1 : Nat) % 2 = 0) (hey : (↑y1 : Nat) % 2 = 0)
    (hne : (↑x1 : Nat) ≠ (↑y1 : Nat)) :
    ⦃ ⌜ True ⌝ ⦄
    lowest_common_ancestor_loop0 x1 y1 0#i32
    ⦃ ⇓ p => ⌜ 2 ≤ p.2.toNat ∧ p.2.toNat ≤ 30
        ∧ (↑p.1 : Nat) * 2 ^ p.2.toNat < 2 ^ 30 ⌝ ⦄ := by
  unfold lowest_common_ancestor_loop0
  apply loop_spec_measure
    (measure := fun (p : Std.U32 × Std.U32 × Std.I32) => 31 - p.2.2.toNat)
    (inv := fun (p : Std.U32 × Std.U32 × Std.I32) => (0 : Int) ≤ ↑p.2.2 ∧ p.2.2.toNat ≤ 30
        ∧ (↑p.1 : Nat) = (↑x1 : Nat) / 2 ^ p.2.2.toNat
        ∧ (↑p.2.1 : Nat) = (↑y1 : Nat) / 2 ^ p.2.2.toNat)
    (post := fun (p : Std.U32 × Std.I32) => 2 ≤ p.2.toNat ∧ p.2.toNat ≤ 30
        ∧ (↑p.1 : Nat) * 2 ^ p.2.toNat < 2 ^ 30)
  · -- init at k = 0
    refine ⟨by simp, by simp, ?_, ?_⟩ <;> simp
  · intro p hinv
    obtain ⟨xn, yn, k⟩ := p
    obtain ⟨hk0, hk30, hxn, hyn⟩ := hinv
    simp only at hk0 hk30 hxn hyn ⊢
    unfold lowest_common_ancestor_loop0.body
    split
    · -- xn ≠ yn : continue
      rename_i hcond
      have hxyne : (↑xn : Nat) ≠ (↑yn : Nat) := by
        have hne' : xn ≠ yn := by simpa [bne_iff_ne] using hcond
        scalar_tac
      have hk29 : k.toNat ≤ 29 := by
        by_contra hc
        have hk30' : k.toNat = 30 := by omega
        rw [hxn, hyn, hk30', Nat.div_eq_of_lt hx, Nat.div_eq_of_lt hy] at hxyne
        exact hxyne rfl
      mvcgen <;> try scalar_tac
      · rename_i xn1 hxn1 yn1 hyn1 k1 hk1
        have h1 : (1#i32).toNat = 1 := by decide
        have hItn : I32.toNat k1 = k.toNat + 1 := by scalar_tac
        refine ⟨⟨by scalar_tac, by scalar_tac, ?_, ?_⟩, by scalar_tac⟩
        · rw [hxn1, h1, Nat.shiftRight_eq_div_pow, pow_one, hxn, hItn,
              Nat.div_div_eq_div_mul, ← pow_succ]
        · rw [hyn1, h1, Nat.shiftRight_eq_div_pow, pow_one, hyn, hItn,
              Nat.div_div_eq_div_mul, ← pow_succ]
    · -- xn = yn : done
      rename_i hcond
      have hxyeq : (↑xn : Nat) = (↑yn : Nat) := by simpa [bne_iff_ne] using hcond
      mvcgen
      have heq : (↑x1 : Nat) / 2 ^ k.toNat = (↑y1 : Nat) / 2 ^ k.toNat := by
        rw [← hxn, ← hyn, hxyeq]
      have hk2 : 2 ≤ k.toNat := even_shift_eq_ge_two hex hey hne heq
      refine ⟨hk2, hk30, ?_⟩
      calc (↑xn : Nat) * 2 ^ k.toNat = (↑x1 / 2 ^ k.toNat) * 2 ^ k.toNat := by rw [hxn]
        _ ≤ ↑x1 := Nat.div_mul_le_self _ _
        _ < 2 ^ 30 := hx

/-! ### The per-function obligations (statements 1:1 with `ProofObligationsExplicit.lean`) -/

/-- Pure-`Prop` spec for `level`: the trailing-ones characterization, with a pure hypothesis pre.
    Registered `@[spec]` (user-validated exception to the "generated specs only" rule): `level`
    occurs in the postconditions of `parent`/`left`/`right`, and re-stepping its monadic post at
    every use site is a performance blocker. -/
@[spec]
theorem level.spec_pure (index : Std.U32) (hidx : (↑index : Nat) < 2 ^ 30) :
    ⦃ ⌜ True ⌝ ⦄
    level index
    ⦃ ⇓ r => ⌜ (↑r : Nat) ≤ 30
        ∧ (↑index : Nat) % 2 ^ ((↑r : Nat) + 1) = 2 ^ (↑r : Nat) - 1 ⌝ ⦄ := by
  mvcgen [level]
  simp_all
  grind [tones_le_30, tones_mod]

/-- Value-carrying spec for `root` (mirrors `parent.spec_value`): the root's tree index is
    `2 ^ L − 1` with `L = Nat.log 2 ↑size` the tree depth (`valid_mask_destruct`'s `hlog` bridges
    `Nat.log 2 ↑size` to the `L` its consumers carry).
    Deliberately NOT `@[spec]`-registered: registering it (with `root.spec.proof` deregistered)
    regresses elaboration of `Openmls.Proofs.Proofs` by ~55% — 84 s against a 54.5 s baseline,
    measured; the same constraint holds for `parent.spec_value`.  Feeding it
    into `direct_path.spec_pure` also needs the constructor equation of the returned
    `TreeNodeIndex` substituted, which `subst_vals` cannot do there without eliminating `size`. -/
theorem root.spec_value (size : TreeSize) :
  (root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄ root size
  ⦃ ⇓ r => ⌜ (match r with
              | .Leaf l => 2 * (↑l : Nat)
              | .Parent p => 2 * (↑p : Nat) + 1) = 2 ^ Nat.log 2 (↑size : Nat) - 1 ⌝ ⦄
  := by
  hax_mvcgen [root, TreeNodeIndex.new, LeafNodeIndex.from_tree_index,
    ParentNodeIndex.from_tree_index] <;> simp at *
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  all_goals
    (have ⟨L, hL, hlog, _, _, _, _, _⟩ := valid_mask_destruct size (by scalar_tac)
     try simp only [hlog]
     scalar_tac)

@[spec]
theorem root.spec.proof (size : TreeSize) :
  (root.pre size).holds →
  ⦃ ⌜ True ⌝ ⦄ root size ⦃ ⇓ res => ⌜ (root.post size res).holds ⌝ ⦄
  := by
  hax_mvcgen [root] <;> simp at *
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  guard_goal_nums 5
  all_goals
    have ⟨L, _, _, _, _, _, _, _⟩ := valid_mask_destruct size ?_
    <;> scalar_tac

-- The registered `level.spec_pure` fires by default (no erasure): its trailing-ones post is fed to
-- the pure `trailing_ones_xor_vals`, whose `1 <<< (k−1)` xor clause makes the result DROP by
-- `2^(k−1)`.  A cheap `scalar_tac` sweep takes every VC that needs no bit reasoning; the four that
-- remain (`res < index` and the two range-check branches, per `from_tree_index` parity) are closed
-- by the one `have`.  `hchar` is `trailing_ones_xor_vals`'
-- FIRST argument so that `by assumption` pins `x`/`k` before the remaining `by scalar_tac` side
-- goals elaborate.
set_option maxHeartbeats 400000 in
@[spec]
theorem left.spec.proof (index : ParentNodeIndex) :
  (left.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄ left index ⦃ ⇓ res => ⌜ (left.post index res).holds ⌝ ⦄
  := by
  hax_mvcgen [left]
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  guard_goal_nums 4
  all_goals
    (casesm* _ ∧ _
     have := trailing_ones_xor_vals _ _ (by assumption) (by scalar_tac) (by scalar_tac) (by scalar_tac)
     obtain ⟨_, _, _, _, _, _⟩ := this
     subst_vals
     scalar_tac)

-- The registered `level.spec_pure` fires by default (no erasure): its trailing-ones post is fed to
-- the pure `trailing_ones_xor_vals`, whose `3 <<< (k−1)` xor clause makes the result RISE by
-- `2^(k−1)`.  A cheap `scalar_tac` sweep takes every VC that needs no bit reasoning; the four that
-- remain (`res > index` and the two range-check branches, per `from_tree_index` parity) are closed
-- by the one `have`.  `hchar` is `trailing_ones_xor_vals`' FIRST argument so that `by assumption`
-- pins `x`/`k` before the remaining `by scalar_tac` side goals elaborate.
set_option maxHeartbeats 400000 in
@[spec]
theorem right.spec.proof (index : ParentNodeIndex) :
  (right.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄ right index ⦃ ⇓ res => ⌜ (right.post index res).holds ⌝ ⦄
  := by
  hax_mvcgen [right]
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  guard_goal_nums 4

  all_goals
    (casesm* _ ∧ _
     have := trailing_ones_xor_vals _ _ (by assumption) (by scalar_tac) (by scalar_tac) (by scalar_tac)
     obtain ⟨_, _, _, _, _, _⟩ := this
     subst_vals
     scalar_tac)

/-- Value-carrying spec for `parent` (user-validated exception, mirrors `level.spec_pure`): with `v`
    the tree index of `x` and `tones v` its trailing-ones count, the parent's tree index is the
    classic bit formula.  Deliberately NOT `@[spec]`-registered: registering it in place of
    `parent.spec.proof` regresses elaboration of this file substantially (measured; the same
    constraint holds for `root.spec_value`).  Its call sites apply it by scoped erasure instead. -/
theorem parent.spec_value (x : TreeNodeIndex)
    (hx : match x with
          | .Leaf l => (↑l : Nat) ≤ 2^29 - 1
          | .Parent p => (↑p : Nat) ≤ 2^29 - 2) :
    ⦃ ⌜ True ⌝ ⦄
    parent x
    ⦃ ⇓ r => ⌜ 2 * (↑r : Nat) + 1 =
        (let v := match x with
                  | .Leaf l => 2 * (↑l : Nat)
                  | .Parent p => 2 * (↑p : Nat) + 1;
         2 ^ (tones v + 2) * (v / 2 ^ (tones v + 2)) + (2 ^ (tones v + 1) - 1)) ⌝ ⦄ := by
  -- `x` must be split BEFORE `mvcgen`: the dependent pure pre `hx` is a `match` on `x` and the
  -- matcher splitter cannot lift it.  Safe here only because no folded monadic post is in scope yet.
  cases x
  all_goals dsimp only at hx ⊢
  all_goals hax_mvcgen [parent]
  all_goals try scalar_tac
  case vc2.h =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr
    obtain ⟨hge, hpos⟩ := parent_bits_pos v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  case vc2.h =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr
    obtain ⟨hge, hpos⟩ := parent_bits_pos v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  -- `X` is odd: `2 ∣ 2^(k+2)·q` and `2^(k+1) − 1` is odd.
  case vc3.h =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u1 hposX m hm
    have hodd := parent_bits_odd v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  case vc3.h =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u1 hposX m hm
    have hodd := parent_bits_odd v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  -- The value equation itself: `trailing_unique` pins `k = tones ↑v`, `parent_bits_val` supplies
  -- the right-hand side, and `from_tree_index` returns `(X − 1)/2` with `X` odd.
  case vc4.hQ =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u1 hposX m hm u2 hm1 xm1 hxm1 hX1 dd hd
    have key : ∀ V : Nat, V = (↑v : Nat) →
        2 * (↑dd : Nat) + 1 =
          2 ^ (tones V + 2) * (V / 2 ^ (tones V + 2)) + (2 ^ (tones V + 1) - 1) := by
      intro V hV
      subst hV
      have e1 : (↑(1#u32) : Nat) = 1 := by simp
      have e2 : (↑(2#u32) : Nat) = 2 := by simp
      have hval := parent_bits_val v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
      have hkt : (↑k : Nat) = tones (↑v : Nat) :=
        trailing_unique (↑v : Nat) (↑k : Nat) (tones (↑v : Nat)) hk.2 (tones_mod _)
      have hoddX : (↑((v ||| r1) ^^^ rr) : Nat) % 2 = 1 := by rw [hm1, e1, e2] at hm; omega
      rw [← hkt, ← hval]
      rw [e1] at hxm1 hX1
      rw [e2] at hd
      omega
    exact key _ (by scalar_tac)
  case vc4.hQ =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u1 hposX m hm u2 hm1 xm1 hxm1 hX1 dd hd
    have key : ∀ V : Nat, V = (↑v : Nat) →
        2 * (↑dd : Nat) + 1 =
          2 ^ (tones V + 2) * (V / 2 ^ (tones V + 2)) + (2 ^ (tones V + 1) - 1) := by
      intro V hV
      subst hV
      have e1 : (↑(1#u32) : Nat) = 1 := by simp
      have e2 : (↑(2#u32) : Nat) = 2 := by simp
      have hval := parent_bits_val v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
      have hkt : (↑k : Nat) = tones (↑v : Nat) :=
        trailing_unique (↑v : Nat) (↑k : Nat) (tones (↑v : Nat)) hk.2 (tones_mod _)
      have hoddX : (↑((v ||| r1) ^^^ rr) : Nat) % 2 = 1 := by rw [hm1, e1, e2] at hm; omega
      rw [← hkt, ← hval]
      rw [e1] at hxm1 hX1
      rw [e2] at hd
      omega
    exact key _ (by scalar_tac)

@[spec]
theorem parent.spec.proof
  (x : TreeNodeIndex) :
  (parent.pre x).holds →
  ⦃ ⌜ True ⌝ ⦄
  parent x
  ⦃ ⇓ res =>
  ⌜ (parent.post x res).holds ⌝ ⦄
  := by
  unfold parent.pre parent.post
  intro h_pre
  apply triple_in_hypothesis (h := h_pre)
  clear h_pre
  hax_mvcgen [parent, MAX_ROOT_INDEX.spec_value]
  all_goals try scalar_tac
  -- `Leaf` branch --------------------------------------------------------------------------------
  case vc2.h =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr
    obtain ⟨hge, hpos⟩ := parent_bits_pos v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  case vc3.h =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u hposX m hm
    have hodd := parent_bits_odd v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  -- Level successor (post clause 2): `tones t2 = k+1` by `tones_parent`, and `trailing_unique` pins
  -- both `level` results, so `lvl2 = k+1 = lvl1+1`.
  case vc3.hQ =>
    rename_i v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u1 hposX m hm u2 hm1 xm1 hxm1 hX1
      dd hd bb hbb hbbt t2 ht2 lvl2 hlvl2 t1 ht1 lvl1 hlvl1 succ hsucc
    have e1 : (↑(1#u32) : Nat) = 1 := by simp
    have e1' : (↑(1#usize) : Nat) = 1 := by simp
    have e2 : (↑(2#u32) : Nat) = 2 := by simp
    have hval := parent_bits_val v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    rw [e1] at hxm1 hX1
    rw [e2] at hd hv
    rw [e1'] at hsucc
    have hoddX : (↑((v ||| r1) ^^^ rr) : Nat) % 2 = 1 := by rw [hm1, e1, e2] at hm; omega
    have ht2v : (↑t2 : Nat) = (↑((v ||| r1) ^^^ rr) : Nat) := by omega
    have htn : tones (↑t2 : Nat) = (↑k : Nat) + 1 := by rw [ht2v, hval]; exact tones_parent _ _
    have hlvl2eq : (↑lvl2 : Nat) = (↑k : Nat) + 1 := by
      have := trailing_unique (↑t2 : Nat) (↑lvl2 : Nat) (tones (↑t2 : Nat)) hlvl2.2 (tones_mod _)
      omega
    have ht1v : (↑t1 : Nat) = (↑v : Nat) := by omega
    rw [ht1v] at hlvl1
    have hlvl1eq : (↑lvl1 : Nat) = (↑k : Nat) :=
      trailing_unique (↑v : Nat) (↑lvl1 : Nat) (↑k : Nat) hlvl1.2 hk.2
    exact decide_eq_true (UScalar.eq_of_val_eq (by omega))
  -- Validity of the result (post clause 1, `dd = (X−1)/2 ≤ 2^29−2`), by contradiction.  For a
  -- `Leaf`, `v = 2·l` is even so `tones v = 0` and the parent value collapses to `4·(v/4) + 1`.
  case vc7.hQ =>
    -- `MAX_ROOT_INDEX.spec_value` binds the constant as `rM` plus `rM = 536870911#u32`; `subst`
    -- restores the numeral inside the `x.u32 != MAX_ROOT_INDEX` test.
    rename_i bb0 hbb0 hbb0t xu hxu rM hrM hxune l hx v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr
      u1 hposX m hm u2 hm1 xm1 hxm1 hX1 dd hd bb hbb hbbt
    subst hrM
    have e1 : (↑(1#u32) : Nat) = 1 := by simp
    have e2 : (↑(2#u32) : Nat) = 2 := by simp
    simp only [hx] at hbb0
    rw [hbb0] at hbb0t
    have hl : (↑l : Nat) ≤ 2 ^ 29 - 1 := of_decide_eq_true hbb0t
    have hval := parent_bits_val v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    rw [e1] at hxm1 hX1
    rw [e2] at hd hv
    have hk0 : (↑k : Nat) = 0 :=
      (trailing_unique (↑v : Nat) 0 (↑k : Nat)
        (by simpa using (by omega : (↑v : Nat) % 2 = 0)) hk.2).symm
    have hXv : (↑((v ||| r1) ^^^ rr) : Nat) = 4 * ((↑v : Nat) / 4) + 1 := by
      rw [hval, hk0]; norm_num
    exact absurd (hbb.trans (decide_eq_true (by omega))) hbbt
  -- `Parent` branch ------------------------------------------------------------------------------
  case vc14.h =>
    rename_i v0 hv0 v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr
    obtain ⟨hge, hpos⟩ := parent_bits_pos v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  case vc15.h =>
    rename_i v0 hv0 v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u hposX m hm
    have hodd := parent_bits_odd v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    scalar_tac
  -- Same level-successor argument; the `Parent` shape adds the `2·p+1` step for `x.u32`.
  case vc3.hQ =>
    rename_i v0 hv0 v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr u1 hposX m hm u2 hm1 xm1 hxm1 hX1
      dd hd bb hbb hbbt t2 ht2 lvl2 hlvl2 t1 ht1 lvl1 hlvl1 succ hsucc
    have e1 : (↑(1#u32) : Nat) = 1 := by simp
    have e1' : (↑(1#usize) : Nat) = 1 := by simp
    have e2 : (↑(2#u32) : Nat) = 2 := by simp
    have hval := parent_bits_val v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    rw [e1] at hxm1 hX1 hv
    rw [e2] at hd hv0
    rw [e1'] at hsucc
    have hoddX : (↑((v ||| r1) ^^^ rr) : Nat) % 2 = 1 := by rw [hm1, e1, e2] at hm; omega
    have ht2v : (↑t2 : Nat) = (↑((v ||| r1) ^^^ rr) : Nat) := by omega
    have htn : tones (↑t2 : Nat) = (↑k : Nat) + 1 := by rw [ht2v, hval]; exact tones_parent _ _
    have hlvl2eq : (↑lvl2 : Nat) = (↑k : Nat) + 1 := by
      have := trailing_unique (↑t2 : Nat) (↑lvl2 : Nat) (tones (↑t2 : Nat)) hlvl2.2 (tones_mod _)
      omega
    have ht1v : (↑t1 : Nat) = (↑v : Nat) := by omega
    rw [ht1v] at hlvl1
    have hlvl1eq : (↑lvl1 : Nat) = (↑k : Nat) :=
      trailing_unique (↑v : Nat) (↑lvl1 : Nat) (↑k : Nat) hlvl1.2 hk.2
    exact decide_eq_true (UScalar.eq_of_val_eq (by omega))
  -- Validity for a `Parent`: `parent_val_lt_two_pow_30` gives `X < 2^30`, and `dd = 2^29−1` would
  -- force `x.u32 = MAX_ROOT_INDEX`, which the precondition excludes.
  case vc7.hQ =>
    rename_i bb0 hbb0 hbb0t xu hxu rM hrM hxune p hx v0 hv0 v hv k hk k1 hk1 r2 hr2 r1 hr1 rr hrr
      u1 hposX m hm u2 hm1 xm1 hxm1 hX1 dd hd bb hbb hbbt
    subst hrM
    have e1 : (↑(1#u32) : Nat) = 1 := by simp
    have e2 : (↑(2#u32) : Nat) = 2 := by simp
    have hb2 : (↑(536870911#u32) : Nat) = 536870911 := by simp
    simp only [hx] at hbb0 hxu
    rw [hbb0] at hbb0t
    have hp : (↑p : Nat) ≤ 2 ^ 29 - 2 := of_decide_eq_true hbb0t
    have hxune' : ¬ (xu = 536870911#u32) := by simpa using hxune
    have hval := parent_bits_val v r1 r2 rr k k1 hk.1 hk.2 hk1 hr2 hr1 hrr
    rw [e1] at hxm1 hX1 hv
    rw [e2] at hd hv0
    have hoddX : (↑((v ||| r1) ^^^ rr) : Nat) % 2 = 1 := by rw [hm1, e1, e2] at hm; omega
    have hvlt : (↑v : Nat) < 2 ^ 30 - 1 := by omega
    have hXlt := parent_val_lt_two_pow_30 (↑v : Nat) (↑k : Nat) hvlt hk.2
    rw [← hval] at hXlt
    have hne : (↑dd : Nat) ≠ 2 ^ 29 - 1 := by
      intro hdd
      have hXeq : (↑((v ||| r1) ^^^ rr) : Nat) = 2 ^ 30 - 1 := by omega
      have h30 : tones ((↑((v ||| r1) ^^^ rr)) : Nat) = 30 := by
        rw [hXeq]; exact tones_pow_sub_one 30
      have hkp : tones ((↑((v ||| r1) ^^^ rr)) : Nat) = (↑k : Nat) + 1 := by
        rw [hval]; exact tones_parent _ _
      have hkeq : (↑k : Nat) = 29 := by omega
      have h2 := hk.2
      rw [hkeq] at h2
      norm_num at h2
      exact hxune' (UScalar.eq_of_val_eq (by rw [hb2]; omega))
    exact absurd (hbb.trans (decide_eq_true (by omega))) hbbt

@[spec]
theorem sibling.spec.proof
  (index : TreeNodeIndex) :
  (sibling.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  sibling index
  ⦃ ⇓ res => ⌜ True ⌝ ⦄
  := by
  -- Post is `True`: pure panic-freedom, discharged from `parent.post`'s clause 1 (`p.valid`), which
  -- is exactly what `left.pre`/`right.pre` and the `level` side conditions need.  CAUTION: the
  -- `cases index <;> simp_all` fallback must stay behind `first | scalar_tac | …` — run into a
  -- folded `parent.post` hypothesis it blows the heartbeat budget on `whnf`.
  unfold sibling.pre
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [sibling]
  all_goals first | scalar_tac | (cases index <;> simp_all <;> scalar_tac)

/-! #### `sibling.pre` discharge lemmas (consumed by `copath.spec.proof`) -/

/-- A `Result Bool` precondition under `.holds` IS a triple, so `mvcgen` steps `sibling.pre`'s body
    directly — no term-level rewriting: the constants come from the registered specs above (via
    their `mvcgen_spec` companions, see RESOLUTION ORDER), the guard from
    `TreeNodeIndex.valid_mvcgen_spec` and the index from `LeafNodeIndex.to_tree_index_mvcgen_spec`.
    Residue, all pure `u32` bounds and hence `scalar_tac`: the root-index disequality (`2·l` is
    even, `2^29 − 1` odd), the `to_tree_index` overflow branch, and the `valid` guard itself. -/
theorem sibling_pre_leaf (l : LeafNodeIndex) (hl : (↑l : Nat) ≤ 2 ^ 29 - 1) :
    (sibling.pre (TreeNodeIndex.Leaf l)).holds := by
  unfold sibling.pre
  mvcgen
  all_goals scalar_tac

/-- Parent counterpart of `sibling_pre_leaf`.  Same spec-based stepping; here the root-index
    disequality is not a parity argument but the caller-supplied `hnr`. -/
theorem sibling_pre_parent (p : ParentNodeIndex) (hp : (↑p : Nat) ≤ 2 ^ 29 - 2)
    (hnr : 2 * (↑p : Nat) + 1 ≠ 2 ^ 29 - 1) :
    (sibling.pre (TreeNodeIndex.Parent p)).holds := by
  unfold sibling.pre
  mvcgen
  all_goals scalar_tac

/-! ### `direct_path`: the on-path walk -/

/-- Loop invariant for `direct_path_loop` on the state `(d, x)`, with `s = ↑size = 2^(L+1) − 1`:
    `↑x < s` (inside the tree), `tones ↑x ≤ L` (on the direct path), `vecLen d = tones ↑x` (which
    yields the postcondition's `len ≤ 30`), and every collected parent `valid` and inside the tree.
    The final POSITIONAL clause pins the entry at index `i` to the level-`(i+1)` ancestor
    (`tones` of its tree index `2·e+1` is exactly `i+1`), which is what lets `direct_path.spec_pure`
    read off the path level-by-level.  The measure is `L − tones ↑x`. -/
def direct_path_loop_inv (s L : Nat)
    (p : alloc.vec.Vec ParentNodeIndex × Std.U32) : Prop :=
  (↑p.2 : Nat) < s ∧ tones (↑p.2 : Nat) ≤ L
  ∧ vecLen p.1 = tones (↑p.2 : Nat)
  ∧ (∀ e ∈ p.1.1, (↑e : Nat) ≤ 2 ^ 29 - 2 ∧ 2 * (↑e : Nat) + 1 < s)
  ∧ ∀ i (hi : i < p.1.1.length), tones (2 * (↑p.1.1[i] : Nat) + 1) = i + 1

/-- The `direct_path` walk: from an on-path node `x` inside the tree, repeatedly replace `x` by its
    parent until the root value `↑r = 2^L − 1` is reached, collecting the parents.  On exit the
    vector has length exactly `L` (`≤ 29`) and every entry is `valid` and inside the tree — the two
    per-entry clauses of `direct_path.post`, in membership form.

    ERASURE RECIPE: the step runs on `parent.spec_value`, which fires past the globally registered
    `parent.spec.proof` only via `mvcgen`'s simp-style scoped erasure `- parent.spec.proof`
    (neither a plain list entry nor a section-local `@[spec]` overrides it).

    Deliberately NOT `@[spec]`-registered: `s` and `L` are explicit arguments that no unifier can
    guess from the call, so a registration could never fire; the single call site in
    `direct_path.spec_pure` applies it by hand with `mspec`. -/
theorem direct_path_loop_spec (s L : Nat) (r : Std.U32)
    (d : alloc.vec.Vec ParentNodeIndex) (x : Std.U32)
    (hs : s = 2 ^ (L + 1) - 1) (hL : L ≤ 29) (hr : (↑r : Nat) = 2 ^ L - 1)
    (hinv : direct_path_loop_inv s L (d, x)) :
    ⦃ ⌜ True ⌝ ⦄
    direct_path_loop r d x
    ⦃ ⇓ res => ⌜ vecLen res = L
        ∧ (∀ e ∈ res.1, (↑e : Nat) ≤ 2 ^ 29 - 2 ∧ 2 * (↑e : Nat) + 1 < s)
        ∧ ∀ i (hi : i < res.1.length), tones (2 * (↑res.1[i] : Nat) + 1) = i + 1 ⌝ ⦄ := by
  -- Numeric shape of the tree size, in numerals: the `2 ^ L` atoms stay out of `scalar_tac`'s way.
  have hp1 : (1 : Nat) ≤ 2 ^ L := Nat.one_le_two_pow
  have hpL : (2 : Nat) ^ L ≤ 2 ^ 29 := Nat.pow_le_pow_right (by norm_num) hL
  have hpS : (2 : Nat) ^ (L + 1) = 2 * 2 ^ L := by rw [pow_succ]; ring
  have hsnum : s ≤ 1073741823 := by simp only [hs]; omega
  unfold direct_path_loop
  apply loop_spec_measure
    (measure := fun p => L - tones (↑p.2 : Nat))
    (inv := direct_path_loop_inv s L)
    -- The `Vec ParentNodeIndex` ascription is REQUIRED: without it `β` is inferred as `Vec ℕ` from
    -- the `↑e` coercion and `apply` fails to unify.
    (post := fun (res : alloc.vec.Vec ParentNodeIndex) => vecLen res = L
        ∧ (∀ e ∈ res.1, (↑e : Nat) ≤ 2 ^ 29 - 2 ∧ 2 * (↑e : Nat) + 1 < s)
        ∧ ∀ i (hi : i < res.1.length), tones (2 * (↑res.1[i] : Nat) + 1) = i + 1)
  · exact hinv
  · rintro ⟨dd, xx⟩ hI
    obtain ⟨hxs, hxt, hlen, hents, hpos⟩ := hI
    simp only at hxs hxt hlen hents hpos ⊢
    unfold direct_path_loop.body
    split
    · -- `xx ≠ r`: one more step up the path.
      rename_i hne
      have hxr : (↑xx : Nat) ≠ 2 ^ L - 1 := by
        intro h
        exact absurd (by scalar_tac : xx = r) (by simpa [bne_iff_ne] using hne)
      have hklt : tones (↑xx : Nat) < L := tones_lt_of_ne_root _ L (by omega) hxt hxr
      have hxnum : (↑xx : Nat) ≤ 1073741822 := by omega
      have hPlt : 2 ^ (tones (↑xx : Nat) + 2) * ((↑xx : Nat) / 2 ^ (tones (↑xx : Nat) + 2))
          + (2 ^ (tones (↑xx : Nat) + 1) - 1) < s := by
        rw [hs]; exact parent_val_lt_size _ L _ hklt (by omega)
      have hlen29 : vecLen dd ≤ 29 := by omega
      have h2u : ((2#u32 : Std.U32) : Nat) = 2 := by simp
      have h1u : ((1#u32 : Std.U32) : Nat) = 1 := by simp
      -- ERASURE TAXONOMY (stated once here; other sites point back at this comment).  A scoped
      -- `- foo.spec.proof` in an `mvcgen`/`hax_mvcgen` set is needed for exactly two reasons:
      --   (A) SELF-SPEC HAZARD — the theorem being proved is itself `@[spec]`-registered, so the
      --       call it is about would be discharged by its own registration, circularly.  Sites:
      --       `direct_path.spec.proof` (`- direct_path.spec.proof`) and `copath.spec.proof`
      --       (`- copath.spec.proof`).  `common_direct_path.spec.proof` avoids the same hazard by
      --       `unfold`ing the function instead of erasing, see the comment there.
      --   (B) OUTRANKING — a stronger companion (`*.spec_value` / `*.spec_pure`) must beat the
      --       registered obligation, whose generated post is too weak for the caller.  Erasure is
      --       the ONLY way: neither a plain list entry nor a section-local `@[spec]` overrides a
      --       global registration.  Sites: this one, and `- root.spec.proof` in
      --       `direct_path.spec_pure`.
      -- Cause (B): `parent.spec.proof`'s post carries no value, `parent.spec_value` does.
      mvcgen [parent.spec_value, - parent.spec.proof, TreeNodeIndex.new,
        LeafNodeIndex.from_tree_index, ParentNodeIndex.from_tree_index, vec_push_spec]
      -- Even `xx`: the step maintains the invariant and drops the measure.
      case vc4.hQ =>
        rename_i b2 hb2e u1 hb2 half hhalf p hval d1 hd1 x1 hx1
        have heven : (↑xx : Nat) % 2 = 0 := by simpa using hb2e ▸ hb2
        have hv : 2 * (↑half : Nat) = (↑xx : Nat) := by rw [hhalf, h2u]; omega
        rw [hv] at hval
        obtain ⟨hlen1, hlist⟩ := hd1
        have hx1s : (↑x1 : Nat) < s := by rw [hx1, hval]; exact hPlt
        have htn : tones (↑x1 : Nat) = tones (↑xx : Nat) + 1 := by
          rw [hx1, hval]; exact tones_parent _ _
        have hple : (↑p : Nat) ≤ 2 ^ 29 - 2 := by omega
        -- The pushed entry's tree index is the parent of `↑xx`, so its `tones` is one higher.
        have htp : tones (2 * (↑p : Nat) + 1) = tones (↑xx : Nat) + 1 := by
          rw [← hx1]; exact htn
        refine ⟨?_, by omega⟩
        simp only [direct_path_loop_inv]
        refine ⟨hx1s, by omega, ?_, ?_, ?_⟩
        · rw [hlen1, hlen, htn]
        · rw [hlist]
          intro e he
          rcases List.mem_append.1 he with h | h
          · exact hents e h
          · simp only [List.mem_singleton] at h
            subst h
            exact ⟨hple, by omega⟩
        · rw [hlist]
          intro i hi
          rcases Nat.lt_or_ge i dd.1.length with h | h
          · rw [List.getElem_append_left h]; exact hpos i h
          · have hie : i = dd.1.length := by
              simp only [List.length_append, List.length_cons, List.length_nil] at hi; omega
            rw [List.getElem_concat_length hie, htp]
            have hll : dd.1.length = tones (↑xx : Nat) := hlen
            omega
      -- Odd `xx`: same, with `2·((↑xx − 1)/2) + 1 = ↑xx`.
      case vc11.hQ =>
        rename_i m hm u2 hm1 xm1 hxm1 hxge1 half hhalf p hval d1 hd1 x1 hx1
        have hodd : (↑xx : Nat) % 2 = 1 := by
          have hm1' : (↑m : Nat) = 1 := by rw [hm1]; simp
          rw [hm, h2u] at hm1'; exact hm1'
        have hv : 2 * (↑half : Nat) + 1 = (↑xx : Nat) := by
          rw [hhalf, hxm1, h1u, h2u]; omega
        rw [hv] at hval
        obtain ⟨hlen1, hlist⟩ := hd1
        have hx1s : (↑x1 : Nat) < s := by rw [hx1, hval]; exact hPlt
        have htn : tones (↑x1 : Nat) = tones (↑xx : Nat) + 1 := by
          rw [hx1, hval]; exact tones_parent _ _
        have hple : (↑p : Nat) ≤ 2 ^ 29 - 2 := by omega
        have htp : tones (2 * (↑p : Nat) + 1) = tones (↑xx : Nat) + 1 := by
          rw [← hx1]; exact htn
        refine ⟨?_, by omega⟩
        simp only [direct_path_loop_inv]
        refine ⟨hx1s, by omega, ?_, ?_, ?_⟩
        · rw [hlen1, hlen, htn]
        · rw [hlist]
          intro e he
          rcases List.mem_append.1 he with h | h
          · exact hents e h
          · simp only [List.mem_singleton] at h
            subst h
            exact ⟨hple, by omega⟩
        · rw [hlist]
          intro i hi
          rcases Nat.lt_or_ge i dd.1.length with h | h
          · rw [List.getElem_append_left h]; exact hpos i h
          · have hie : i = dd.1.length := by
              simp only [List.length_append, List.length_cons, List.length_nil] at hi; omega
            rw [List.getElem_concat_length hie, htp]
            have hll : dd.1.length = tones (↑xx : Nat) := hlen
            omega
      -- `to_tree_index`'s `2·p + 1` cannot overflow: the value equation plus `parent_val_lt_size`
      -- bound it by `s ≤ 2^30 − 1`.  Even, then odd branch.
      case vc5.h_fail =>
        rename_i b2 hb2e u1 hb2 half hhalf p hval d1 hd1 hof
        have heven : (↑xx : Nat) % 2 = 0 := by simpa using hb2e ▸ hb2
        have hv : 2 * (↑half : Nat) = (↑xx : Nat) := by rw [hhalf, h2u]; omega
        rw [hv] at hval
        have hlt : 2 * (↑p : Nat) + 1 < s := by rw [hval]; exact hPlt
        scalar_tac
      case vc12.h_fail =>
        rename_i m hm u2 hm1 xm1 hxm1 hxge1 half hhalf p hval d1 hd1 hof
        have hodd : (↑xx : Nat) % 2 = 1 := by
          have hm1' : (↑m : Nat) = 1 := by rw [hm1]; simp
          rw [hm, h2u] at hm1'; exact hm1'
        have hv : 2 * (↑half : Nat) + 1 = (↑xx : Nat) := by
          rw [hhalf, hxm1, h1u, h2u]; omega
        rw [hv] at hval
        have hlt : 2 * (↑p : Nat) + 1 < s := by rw [hval]; exact hPlt
        scalar_tac
      -- Residue: the `spec_value` payload bounds, the `push` capacity, the parity massertions and
      -- the `↑xx − 1` underflow guard — all linear.
      all_goals scalar_tac
    · -- `xx = r`: done, and `vecLen dd = tones ↑r = L` by `tones_pow_sub_one`.
      rename_i heq
      have hxr : (↑xx : Nat) = 2 ^ L - 1 := by
        have h : (↑xx : Nat) = (↑r : Nat) := by simpa [bne_iff_ne] using heq
        rw [h, hr]
      mvcgen
      refine ⟨?_, hents, hpos⟩
      rw [hlen, hxr, tones_pow_sub_one]

/-- Pure membership-form companion of `direct_path.spec` (statement user-validated; the Rust spec
    may later gain clause 3 phrased via `level`).
    Clause 1-2 are the Rust post in membership form: at most 29 entries, every entry `valid`
    (`≤ 2^29 − 2 = MAX_PARENT`) and below `parent_count size = ↑size / 2`. Clause 3 is a
    positional strengthening needed by `copath`: the entry at position `i` is the level-`i+1`
    ancestor (`tones (2·e+1) = i+1`), so after `pop` no remaining entry can be the root.
    Deliberately NOT `@[spec]`-registered: the official registration is `direct_path.spec.proof`;
    this companion is consumed by explicit application / scoped erasure at its call sites. -/
theorem direct_path.spec_pure (node_index : LeafNodeIndex) (size : TreeSize)
    (h : (direct_path.pre node_index size).holds) :
    ⦃ ⌜ True ⌝ ⦄
    direct_path node_index size
    ⦃ ⇓ res => ⌜ vecLen res ≤ 29
        ∧ (∀ e ∈ res.1, (↑e : Nat) ≤ 2 ^ 29 - 2 ∧ (↑e : Nat) < (↑size : Nat) / 2)
        ∧ (∀ i, (hi : i < res.1.length) → tones (2 * (↑res.1[i] : Nat) + 1) = i + 1) ⌝ ⦄ := by
  -- Erasure cause (B), see the ERASURE TAXONOMY comment in `direct_path_loop_spec`:
  -- `root.spec.proof`'s post (`res.valid ∧ res.u32 < size`) is too weak — the loop spec needs the
  -- root VALUE `↑r = 2^L − 1`.  The value-form companion `root.spec_value` (post:
  -- `(match r with .Leaf l => 2*↑l | .Parent p => 2*↑p+1) = 2 ^ Nat.log 2 ↑size − 1`) is NOT usable
  -- here: registering it costs ~55% of this file's elaboration time (measured), and its `match`-form
  -- post would still need the constructor equation substituted at this site, which `subst_vals`
  -- cannot do without also eliminating `size`.
  -- So `root` is stepped by its body (`- root.spec.proof, root`, plus
  -- the two `from_tree_index` unfolds inside `TreeNodeIndex.new`), which is where
  -- `log2_mvcgen_spec` supplies `↑ = Nat.log 2 ↑size`.  `direct_path_loop_spec` needs no erasure:
  -- it is unregistered (unguessable explicit `s`/`L`) and applied by hand with `mspec` below.
  apply triple_in_hypothesis (h := h) ; clear h
  hax_mvcgen [direct_path.pre, direct_path, - root.spec.proof, root, TreeNodeIndex.new,
    LeafNodeIndex.from_tree_index, ParentNodeIndex.from_tree_index]
  -- Same mask-form preamble as `root.spec.proof`: `all_ones_of_and_succ_eq_zero` turns the bit-form
  -- validity decide into a FRESH existential `L` with `hL : ↑size = 2^(L+1) − 1`; `hlog` bridges the
  -- `Nat.log 2 ↑size` terms the stepped `log2` body produces.
  all_goals
    (obtain ⟨hs1, hs2, hmask⟩ :=
        of_decide_eq_true
          (show decide (1 ≤ (↑size : Nat) ∧ (↑size : Nat) ≤ 2 ^ 30 - 1 ∧
              (↑size : Nat) &&& ((↑size : Nat) + 1) = 0) = true by assumption)
     obtain ⟨L, hL, hlog, hL29, hp1, hp29, hpow, hsh⟩ :=
        valid_mask_destruct _ ⟨hs1, hs2, hmask⟩
     try scalar_tac)
  -- The two surviving goals are the loop call, once per `TreeNodeIndex.new` branch: `2^L − 1` is
  -- even only for `L = 0` (the singleton tree), odd otherwise, and BOTH reconstructions collapse
  -- back to `↑rt = 2^L − 1` by `omega`.  The last SIX inaccessible hypotheses sit at the same depth
  -- in both branches — root value, `Vec::new`, `to_tree_index`.
  all_goals
    (rename_i rt hrt dv hdv xv hxv
     have hx2 : (↑xv : Nat) = 2 * (↑node_index : Nat) := by scalar_tac
     have hxt : tones (↑xv : Nat) = 0 := tones_even _ (by omega)
     have hinv : direct_path_loop_inv (↑size : Nat) L (dv, xv) := by
       simp only [direct_path_loop_inv]
       refine ⟨by scalar_tac, by rw [hxt]; omega, ?_, ?_, ?_⟩
       · rw [hxt]; exact hdv.1
       · rw [hdv.2]; simp
       · rw [hdv.2]; simp
     mspec (direct_path_loop_spec (↑size : Nat) L rt dv xv (by omega) hL29 (by scalar_tac) hinv)
     intro hpost
     obtain ⟨hlen, hents, hpos⟩ := hpost
     refine ⟨by omega, ?_, hpos⟩
     intro e he
     obtain ⟨he1, he2⟩ := hents e he
     exact ⟨he1, by omega⟩)

@[spec]
theorem direct_path.spec.proof (node_index : LeafNodeIndex) (size : TreeSize) :
  (direct_path.pre node_index size).holds →
  ⦃ ⌜ True ⌝ ⦄
  direct_path node_index size
  ⦃ ⇓ res => ⌜ (direct_path.post node_index size res).holds ⌝ ⦄
  := by
  -- The function's behaviour comes entirely from `direct_path.spec_pure` (membership form); the
  -- Rust post is then re-derived by STEPPING THE POST do-block (`len`/`deref`/`iter`/`all`).
  -- Erasure cause (A), self-spec hazard — see the ERASURE TAXONOMY in `direct_path_loop_spec`.
  -- The `all` step goes through the trusted `slice_iter_all_spec`, whose predicate `P` is not
  -- inferable: it arrives as the `vc1.P` goal (a `Bool` with the element in scope) and is
  -- instantiated with the pointwise value of the Rust closure `__18.ensures.closure`.
  intro h_pre
  unfold direct_path.post
  hax_mvcgen [- direct_path.spec.proof, direct_path.spec_pure]
  case vc1.P =>
    rename_i e
    exact decide ((↑e : Nat) ≤ 2 ^ 29 - 2 ∧ (↑e : Nat) < (↑size : Nat) / 2)
  case vc1.hQ =>
    rename_i h1 e1 he1 e2 he2 hlt h2 f1 hf1 f2 hf2
    clear h1 h2
    scalar_tac
  case vc2.hcall =>
    rename_i e he
    unfold __18.ensures.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexBool.call_mut
      ParentNodeIndex.valid ParentNodeIndex.u32 TreeSize.parent_count
    rw [show binary_tree.array_representation.treemath.MAX_PARENT = ok 536870910#u32 by
      unfold MAX_PARENT MAX_LEAF MAX_TREE_INDEX MAX_TREE_SIZE; rfl]
    obtain ⟨q, hq, hqv⟩ := Aeneas.Std.UScalar.div_spec (x := size) (y := 2#u32) (by scalar_tac)
    simp [hq, hqv]
    split <;> rename_i hb <;> simp [hb]
  case vc3 =>
    rename_i hpre e1 he1 e2 he2 hlt v hlen hents hposs l hl29 hlv s hs it hit p hp
    rw [hp]
    simp only [sliceIterElems, hit, hs, List.all_eq_true, decide_eq_true_eq]
    intro e he
    exact hents e he
  case vc4 =>
    rename_i hpre e1 he1 e2 he2 hlt v hlen hents hposs l hl29 hlv
    clear hpre
    scalar_tac

@[spec]
theorem copath.spec.proof (leaf_index : LeafNodeIndex) (size : TreeSize) :
  (copath.pre leaf_index size).holds →
  ⦃ ⌜ True ⌝ ⦄ copath leaf_index size ⦃ ⇓ res => ⌜ True ⌝ ⦄
  := by
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  -- Erasures: cause (A) for `- copath.spec.proof` (self-spec hazard) and cause (B) for
  -- `- direct_path.spec.proof` (outranked by `direct_path.spec_pure`); see the ERASURE TAXONOMY
  -- in `direct_path_loop_spec`.
  hax_mvcgen [copath, - copath.spec.proof, - direct_path.spec.proof, direct_path.spec_pure,
    slice_iter_map_collect_spec, into_map_collect_spec]
  case vc1.hQ =>
    rename_i h1 e1 he1 e2 he2 hlt h2 f1 hf1 f2 hf2
    clear h1 h2
    scalar_tac
  case vc4.hQ =>
    rename_i hdec e1 he1 e2 he2 hlt dp hdp b hbne hb pr hpr
    obtain ⟨hsz1, hsz, hsz3⟩ := of_decide_eq_true hdec
    clear hdec
    obtain ⟨hlen29, hents, hposs⟩ := hdp
    obtain ⟨hpr2, -⟩ := hpr
    simp only [alloc.slice.Slice.into_vec]
    mvcgen [alloc.slice.Dummy.into_vec, rust_primitives.sequence.seq_from_boxed_slice,
      alloc.vec.from_seq, slice_iter_map_collect_spec, into_map_collect_spec]
    -- mvcgen stalls at the `map`/`collect` pair: apply the trusted contract by hand.
    rename_i s hs it hit
    have hmc := slice_iter_map_collect_spec
      copath.closure.Insts.CoreOpsFunctionFnMutTupleSharedParentNodeIndexTreeNodeIndex
      it () TreeNodeIndex.Parent (by intro e he; rfl)
    obtain ⟨mv, hmv⟩ := triple_noThrow_exists_ok hmc
    have hmvp := triple_noThrow_elim hmc hmv
    simp only [SPred.down_pure] at hmvp
    rw [← Std.Do.WP.bind, ← bind_assoc, hmv]
    simp only [bind_tc_ok]
    mvcgen [vec_append_spec, into_map_collect_spec]
    · -- `Vec::append` capacity: `|[Leaf leaf_index]| + |dp.dropLast| = 1 + (|dp| − 1) ≤ Usize.max`.
      simp only [hmvp, List.length_map, sliceIterElems, hit, hs, hpr2, List.length_dropLast]
      simp only [Aeneas.Std.Array.to_slice, Aeneas.Std.Array.make, List.length_cons,
        List.length_nil, Nat.zero_add]
      have hne0 : vecLen dp ≠ 0 := by intro hh; exact hbne (by rw [hb, hh]; rfl)
      rw [vecLen_eq_length] at hne0
      have hdm : dp.val.length ≤ Std.Usize.max := dp.property
      omega
    · -- The final `into_iter` / `map sibling` / `collect`.  `mvcgen` will not re-associate the
      -- three-step do-block into the shape of `into_map_collect_spec`, so the trusted contract is
      -- applied by hand (as for `slice_iter_map_collect_spec` above), with
      --   `hsafe : ∀ e ∈ [Leaf leaf_index] ++ (dp.dropLast).map Parent, ⦃True⦄ sibling e ⦃True⦄`
      -- derived from the registered `sibling.spec.proof` by computing `(sibling.pre e).holds`.
      rename_i r hr
      have hrl : r.1.val
          = TreeNodeIndex.Leaf leaf_index :: (dp.val.dropLast).map TreeNodeIndex.Parent := by
        rw [hr.1, hmvp]
        simp only [sliceIterElems, hit, hs, hpr2, Aeneas.Std.Array.to_slice,
          Aeneas.Std.Array.make, List.cons_append, List.nil_append]
      have hsafe : ∀ e ∈ r.1.val, ⦃ ⌜ True ⌝ ⦄ sibling e ⦃ ⇓ _ => ⌜ True ⌝ ⦄ := by
        intro t ht
        rw [hrl] at ht
        refine sibling.spec.proof t ?_
        rcases List.mem_cons.1 ht with rfl | hR
        · -- `Leaf leaf_index`: `↑leaf_index < ↑size/2 + 1 ≤ 2^29` and `2·leaf` is even.
          refine sibling_pre_leaf leaf_index ?_
          have hlt' : (↑e1 : Nat) < (↑e2 : Nat) := by
            simpa only [u32_lt_nat] using of_decide_eq_true hlt
          rw [he1, he2] at hlt'
          omega
        · -- `Parent p` with `p ∈ dp.dropLast`.
          obtain ⟨p, hp, rfl⟩ := List.mem_map.1 hR
          refine sibling_pre_parent p (hents p (List.dropLast_subset _ hp)).1 ?_
          have hlen' : dp.val.length ≤ 29 := by
            simpa only [vecLen_eq_length] using hlen29
          exact dropLast_entries_ne_max_root dp.val hlen' hposs p hp
      have hcol := into_map_collect_spec r.1 sibling hsafe
      obtain ⟨cv, hcv⟩ := triple_noThrow_exists_ok hcol
      rw [← Std.Do.WP.bind, hcv]
      trivial

set_option maxHeartbeats 400000 in
@[spec]
theorem lowest_common_ancestor.spec.proof (x : LeafNodeIndex) (y : LeafNodeIndex) :
  (lowest_common_ancestor.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄ lowest_common_ancestor x y
  ⦃ ⇓ res => ⌜ (lowest_common_ancestor.post x y res).holds ⌝ ⦄
  := by
  -- The pre forces two distinct valid (`< 2^29`) leaves, so `level` returns `0` and both
  -- early-return branches are unreachable; the shift-loop tail closes via `lca_tail_aux`.
  unfold lowest_common_ancestor.pre lowest_common_ancestor.post LeafNodeIndex.valid
    LeafNodeIndex.u32 ParentNodeIndex.valid
  intro h_pre
  apply triple_in_hypothesis (h := h_pre)
  clear h_pre
  mvcgen ; simp
  case vc2.hQ =>
    grind
  case vc3.hQ =>
    grind
  simp_all; intro
  hax_mvcgen [lowest_common_ancestor]
  all_goals try scalar_tac
  case vc3.h =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy heq
    exfalso
    exact lca_shift_ne heq hxy hxv hyv (lca_level_one hyv hky hky1).1 hsx hsy
  case vc4.h =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy heq
      u hpos m hm
    exfalso
    exact lca_shift_ne heq hxy hxv hyv (lca_level_one hyv hky hky1).1 hsx hsy
  case vc9.h =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne
      hle2 tx htx ty hty heq
    exfalso
    exact lca_shift_ne heq hxy hxv hyv (lca_level_one hxv hkx hkx1).1 htx hty
  case vc10.h =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne
      hle2 tx htx ty hty heq u hpos m hm
    exfalso
    exact lca_shift_ne heq hxy hxv hyv (lca_level_one hxv hkx hkx1).1 htx hty
  case vc36.h_ok.isFalse.isFalse =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne hnle
    exfalso
    have hkx1' := (lca_level_one hxv hkx hkx1).1
    have hky1' := (lca_level_one hyv hky hky1).1
    clear hkx hky hxv hyv hsx hsy hne hle hx hy hxy
    exact hnle (by scalar_tac)
  case vc39.h =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hnle hle sx hsx sy hsy heq
    exfalso
    have hkx1' := (lca_level_one hxv hkx hkx1).1
    have hky1' := (lca_level_one hyv hky hky1).1
    clear hkx hky hxv hyv hsx hsy heq hle hx hy hxy
    exact hnle (by scalar_tac)
  case vc40.h =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hnle hle sx hsx sy hsy heq
      u hpos m hm
    exfalso
    have hkx1' := (lca_level_one hxv hkx hkx1).1
    have hky1' := (lca_level_one hyv hky hky1).1
    clear hkx hky hxv hyv hsx hsy heq hle hx hy hxy hm hpos
    exact hnle (by scalar_tac)
  case vc45.h_ok.isFalse =>
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hnle hle sx hsx sy hsy hne
    exfalso
    have hkx1' := (lca_level_one hxv hkx hkx1).1
    have hky1' := (lca_level_one hyv hky hky1).1
    clear hkx hky hxv hyv hsx hsy hne hle hx hy hxy
    exact hnle (by scalar_tac)
  -- Family (b). In each block the `2 ^ …`-laden `level`/`loop0` hypotheses are cleared before
  -- `scalar_tac`, which otherwise diverges on them (see `Common.lean`).
  case vc1.hQ =>
    -- Result validity. `lca_tail_bound` gives `i6 + i8 ≤ 2^30 − 1`, so the returned
    -- `((i6 + i8 − 1) − 1)/2 ≤ (2^30 − 3)/2 = 2^29 − 2 = MAX_PARENT`.
    rename_i c1 hc1 c2 hx hc2 hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle
      sx hsx sy hsy hne hle2 tx htx ty hty hne2
      p hp i6 hi6 i7 hi7 i8 hi8 j1 hj1 j2 hj2 hj2le u1 hu1 j3 hj3 u2 hu2 j4 hj4 hj4le
      j5 hj5 mp hmp
    obtain ⟨hk2, hk30, hbnd⟩ := hp
    have hb := lca_tail_bound hk2 hk30 hbnd hi6 hi7 hi8
    clear hkx hky hxv hyv hsx hsy htx hty hbnd hi6 hi7 hi8 hk2 hk30
    scalar_tac
  case vc20.h =>
    -- `i10 = i6 + i8 − 1 > 0` because `i8 = 1 <<< (k−1) ≥ 2`.
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne
      hle2 tx htx ty hty hne2 p hp i6 hi6 i7 hi7 i8 hi8 i9 hi9 i10 hi10 hge
    obtain ⟨hk2, hk30, hbnd⟩ := hp
    obtain ⟨-, -, hi8ge, -⟩ := lca_tail_aux hk2 hk30 hbnd hi6 hi7 hi8
    clear hkx hky hxv hyv hsx hsy htx hty hbnd hi6 hi7 hi8 hk2 hk30
    scalar_tac
  case vc21.h =>
    -- `i10 = i6 + i8 − 1` is odd: `i6 = xn <<< k` and `i8 = 1 <<< (k−1)` are both even (`k ≥ 2`).
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne
      hle2 tx htx ty hty hne2 p hp i6 hi6 i7 hi7 i8 hi8 i9 hi9 i10 hi10 hge u hpos m hm
    obtain ⟨hk2, hk30, hbnd⟩ := hp
    obtain ⟨-, hi6ev, hi8ge, hi8ev⟩ := lca_tail_aux hk2 hk30 hbnd hi6 hi7 hi8
    clear hkx hky hxv hyv hsx hsy htx hty hbnd hi6 hi7 hi8 hk2 hk30
    scalar_tac
  case vc26.h_fail =>
    -- The `i9 − 1` subtraction cannot underflow: `i9 = i6 + i8 ≥ 2`.
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne
      hle2 tx htx ty hty hne2 p hp i6 hi6 i7 hi7 i8 hi8 i9 hi9 hlt
    obtain ⟨hk2, hk30, hbnd⟩ := hp
    obtain ⟨-, -, hi8ge, -⟩ := lca_tail_aux hk2 hk30 hbnd hi6 hi7 hi8
    clear hkx hky hxv hyv hsx hsy htx hty hbnd hi6 hi7 hi8 hk2 hk30
    exfalso ; scalar_tac
  case vc27.h_fail =>
    -- The `i6 + i8` addition cannot overflow: `xn·2^k < 2^30` and `2^(k−1) ≤ 2^29`.
    rename_i hx hy hxy xv hxv yv hyv kx hkx kx1 hkx1 ky hky ky1 hky1 hle sx hsx sy hsy hne
      hle2 tx htx ty hty hne2 p hp i6 hi6 i7 hi7 i8 hi8 hovf
    obtain ⟨hk2, hk30, hbnd⟩ := hp
    obtain ⟨hsum, -, -, -⟩ := lca_tail_aux hk2 hk30 hbnd hi6 hi7 hi8
    have hmax : UScalar.max UScalarTy.U32 = 2 ^ 32 - 1 := by simp [Aeneas.Std.U32.max_eq]
    exfalso ; omega


@[spec]
theorem common_direct_path.spec.proof (x : LeafNodeIndex) (y : LeafNodeIndex)
  (size : TreeSize) :
  (common_direct_path.pre x y size).holds →
  ⦃ ⌜ True ⌝ ⦄ common_direct_path x y size ⦃ ⇓ res => ⌜ True ⌝ ⦄
  := by
  intro h_pre
  apply triple_in_hypothesis (h := h_pre)
  clear h_pre
  mvcgen [common_direct_path]
  case vc2.hQ => simp
  case vc3.hQ => simp
  case vc1.hQ =>
    intro _
    -- Self-spec hazard (taxonomy cause (A), stated in `direct_path_loop_spec`), remedied by
    -- `unfold` rather than erasure: without it the goal matches `common_direct_path.spec.proof`
    -- itself and `mvcgen` discharges it circularly with the spec being proved.
    unfold common_direct_path
    mvcgen
    case vc1.hQ => simp only [decide_eq_true_eq, u32_lt_nat] at * ; omega
    case vc3.hQ => simp only [decide_eq_true_eq, u32_lt_nat] at * ; omega
    case vc5.hx => omega
    case vc6.hy => omega
    case vc7.hi => simp
    case vc8.hcp => omega


@[spec]
theorem is_node_in_tree.spec.proof (node_index : TreeNodeIndex) (size : TreeSize) :
  (is_node_in_tree.pre node_index size).holds →
  ⦃ ⌜ True ⌝ ⦄ is_node_in_tree node_index size ⦃ ⇓ res => ⌜ True ⌝ ⦄
  := by
  hax_mvcgen [is_node_in_tree, pure, pre]
  all_goals scalar_tac

@[spec]
theorem LeafNodeIndex.new.spec.proof (index : Std.U32) :
  (LeafNodeIndex.new.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  LeafNodeIndex.new index
  ⦃ ⇓ res => ⌜ (LeafNodeIndex.new.post index res).holds ⌝ ⦄
  := by
  -- `new` is the identity on the payload, so `index ≤ MAX_LEAF` *is* `res.valid`.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [LeafNodeIndex.new, LeafNodeIndex.new.pre, LeafNodeIndex.new.post,
    LeafNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem LeafNodeIndex.to_tree_index.spec.proof (self : LeafNodeIndex) :
  (LeafNodeIndex.to_tree_index.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  LeafNodeIndex.to_tree_index self
  ⦃ ⇓ res => ⌜ (LeafNodeIndex.to_tree_index.post self res).holds ⌝ ⦄
  := by
  -- `2·self` with `self ≤ 2^29 − 1` is `≤ 2^30 − 2 = MAX_TREE_INDEX` (tight) and even.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [LeafNodeIndex.to_tree_index, LeafNodeIndex.to_tree_index.pre,
    LeafNodeIndex.to_tree_index.post, LeafNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem LeafNodeIndex.from_tree_index.spec.proof (node_index : Std.U32) :
  (LeafNodeIndex.from_tree_index.pre node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  LeafNodeIndex.from_tree_index node_index
  ⦃ ⇓ res => ⌜ (LeafNodeIndex.from_tree_index.post node_index res).holds ⌝ ⦄
  := by
  -- `node_index / 2 ≤ (2^30 − 2)/2 = 2^29 − 1 = MAX_LEAF`.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [LeafNodeIndex.from_tree_index, LeafNodeIndex.from_tree_index.pre,
    LeafNodeIndex.from_tree_index.post, LeafNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem ParentNodeIndex.new.spec.proof (index : Std.U32) :
  (ParentNodeIndex.new.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  ParentNodeIndex.new index
  ⦃ ⇓ res => ⌜ (ParentNodeIndex.new.post index res).holds ⌝ ⦄
  := by
  -- `new` is the identity on the payload, so `index ≤ MAX_PARENT` *is* `res.valid`.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [ParentNodeIndex.new, ParentNodeIndex.new.pre, ParentNodeIndex.new.post,
    ParentNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem ParentNodeIndex.to_tree_index.spec.proof (self : ParentNodeIndex) :
  (ParentNodeIndex.to_tree_index.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  ParentNodeIndex.to_tree_index self
  ⦃ ⇓ res => ⌜ (ParentNodeIndex.to_tree_index.post self res).holds ⌝ ⦄
  := by
  -- `2·self + 1` with `self ≤ 2^29 − 2` is `≤ 2^30 − 3 < MAX_TREE_INDEX` and odd.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [ParentNodeIndex.to_tree_index, ParentNodeIndex.to_tree_index.pre,
    ParentNodeIndex.to_tree_index.post, ParentNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem ParentNodeIndex.from_tree_index.spec.proof (node_index : Std.U32) :
  (ParentNodeIndex.from_tree_index.pre node_index).holds →
  ⦃ ⌜ True ⌝ ⦄
  ParentNodeIndex.from_tree_index node_index
  ⦃ ⇓ res => ⌜ (ParentNodeIndex.from_tree_index.post node_index res).holds ⌝ ⦄
  := by
  -- `node_index` odd and `≤ 2^30 − 2` forces `≤ 2^30 − 3`, so `(node_index − 1)/2 ≤ 2^29 − 2`.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [ParentNodeIndex.from_tree_index, ParentNodeIndex.from_tree_index.pre,
    ParentNodeIndex.from_tree_index.post, ParentNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem TreeNodeIndex.new.spec.proof (index : Std.U32) :
  (TreeNodeIndex.new.pre index).holds →
  ⦃ ⌜ True ⌝ ⦄
  TreeNodeIndex.new index
  ⦃ ⇓ res => ⌜ (TreeNodeIndex.new.post index res).holds ⌝ ⦄
  := by
  -- With `index ≤ 2^30 − 2` the constructed index is valid: even `index ↦ Leaf (index/2)` with
  -- `index/2 ≤ MAX_LEAF`; odd `index ↦ Parent ((index−1)/2)` with `(index−1)/2 ≤ MAX_PARENT`.
  intro h_pre
  apply triple_in_hypothesis (h := h_pre) ; clear h_pre
  hax_mvcgen [TreeNodeIndex.new, TreeNodeIndex.new.pre, TreeNodeIndex.new.post,
    TreeNodeIndex.valid,
    LeafNodeIndex.from_tree_index, ParentNodeIndex.from_tree_index,
    LeafNodeIndex.valid, ParentNodeIndex.valid]
  all_goals scalar_tac

@[spec]
theorem TreeNodeIndex.u32.spec.proof (self : TreeNodeIndex) :
  (TreeNodeIndex.u32.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  TreeNodeIndex.u32 self
  ⦃ ⇓ res => ⌜ (TreeNodeIndex.u32.post self res).holds ⌝ ⦄
  := by
  cases self <;> hax_mvcgen [u32]
  all_goals grind

@[spec]
theorem TreeSize.new.spec.proof
   (nodes : Std.U32) :
  (TreeSize.new.pre nodes).holds →
  ⦃ ⌜ True ⌝ ⦄
  TreeSize.new nodes
  ⦃ ⇓ res =>
  ⌜ (TreeSize.new.post nodes res).holds ⌝ ⦄
  := by
  -- `simp_all!` rather than `simp at *` as the normalizer: the shift VCs need the let-bindings
  -- substituted before `scalar_tac` can see the `Nat.log` bound (that is what kills `vc2`/`vc3`).
  hax_mvcgen [new] <;> simp_all!
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  guard_goal_nums 1
  -- The real content: `valid (1 <<< (log₂ nodes + 1) − 1)`.  `nodes < 2^30` gives
  -- `log₂ nodes ≤ log₂ (2^30 − 1) = 29`, so the shift `L + 1 ≤ 30` does not wrap and
  -- `1 <<< (L+1) % U32.size = 2^(L+1)`.  The result is then the all-ones mask of width `L + 1`,
  -- certified producer-side by `valid_mask_intro`; mvcgen has already collapsed
  -- `(2^(L+1) − 1) + 1` to `2^(L+1)` in the mask conjunct, which `convert` bridges.
  have hM : Nat.log 2 (↑nodes : Nat) ≤ 29 := by
    have hpow30 : (2 : Nat) ^ (29 + 1) - 1 = 1073741823 := by norm_num
    have h := Nat.log_mono_right (b := 2) (show (↑nodes : Nat) ≤ 2 ^ (29 + 1) - 1 by omega)
    rwa [log2_two_pow_sub_one 29] at h
  rw [one_shiftLeft_mod_eq _ (by omega)]
  have h30 : (2 : Nat) ^ 30 = 1073741824 := by norm_num
  have hpos : 1 ≤ (2 : Nat) ^ (Nat.log 2 (↑nodes : Nat) + 1) := Nat.one_le_two_pow
  have ⟨h1, h2, hmask⟩ := valid_mask_intro _ _ rfl hM
  exact ⟨by omega, by omega, by convert hmask using 2; omega⟩

@[spec]
theorem TreeSize.inc.spec.proof (self : TreeSize) :
  (TreeSize.inc.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  TreeSize.inc self
  ⦃ ⇓ res => ⌜ (TreeSize.inc.post self res).holds ⌝ ⦄
  := by
  hax_mvcgen [inc] <;> simp at *
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  guard_goal_nums 1
  -- The real content: `valid (2·self + 1)`.  The pre only gives `self < 2^30 − 1`, so the
  -- `L + 1 ≤ 29` bound must come from validity: `self = 2^(L+1) − 1 < 2^30 − 1` forces
  -- `2^(L+1) < 2^30`.  Then `2·self + 1 = 2^(L+2) − 1` is certified by `valid_mask_intro`,
  -- contradicting the failure hypothesis.  `hb` is the pow-atom bridge omega needs on top of
  -- the destruct's `2^(L+1) = 2·2^L`.
  rename_i hvr
  have ⟨L, _, _, _, _, _, _, _⟩ := valid_mask_destruct self (by scalar_tac)
  have hb : (2 : Nat) ^ (L + 1 + 1) = 2 * 2 ^ (L + 1) := by ring
  have hM : L + 1 ≤ 29 := by
    by_contra hc
    have : (2 : Nat) ^ 30 ≤ 2 ^ (L + 1) := Nat.pow_le_pow_right (by omega) (by omega)
    scalar_tac
  have ⟨_, _, hmask⟩ := valid_mask_intro (2 ^ (L + 1 + 1) - 1) (L + 1) rfl hM
  exact hvr (by omega) (by omega) (by convert hmask using 2 <;> omega)

@[spec]
theorem TreeSize.dec.spec.proof (self : TreeSize) :
  (TreeSize.dec.pre self).holds →
  ⦃ ⌜ True ⌝ ⦄
  TreeSize.dec self
  ⦃ ⇓ res => ⌜ (TreeSize.dec.post self res).holds ⌝ ⦄
  := by
  hax_mvcgen [dec] <;> simp at *
  all_goals set_option maxHeartbeats 1_000 in (try scalar_tac)
  guard_goal_nums 3

  case vc1.h =>
    -- `MIN_TREE_SIZE = 1 < self` gives `self ≥ 2`.
    simp only [MIN_TREE_SIZE] at *
    scalar_tac
  case vc1.hQ =>
    -- `divCeil self 2 − 1 = self / 2`: needs `self` ODD, which the destruct supplies via
    -- `self = 2^(L+1) − 1` together with the `pow_succ` doubling.
    have ⟨L, _, _, _, _, _, _, _⟩ := valid_mask_destruct self (by scalar_tac)
    exact Aeneas.Std.UScalar.eq_of_val_eq (by scalar_tac)
  case vc3.hQ =>
    -- The real content: `valid (divCeil self 2 − 1)`.  `self = 2^(L+1) − 1` with `self ≥ 2`
    -- forces `L ≥ 1`, and `divCeil self 2 − 1 = 2^L − 1 = 2^((L−1)+1) − 1`, certified by
    -- `valid_mask_intro` at `M := L − 1`.  So the failure hypothesis is absurd.
    rename_i hvd
    have ⟨L, _, _, _, _, _, _, _⟩ := valid_mask_destruct self (by scalar_tac)
    have hp2 : 2 ≤ (2 : Nat) ^ L := by scalar_tac
    have hL1 : 1 ≤ L := by
      by_contra hc
      have : (2 : Nat) ^ L = 1 := by rw [show L = 0 from by omega, pow_zero]
      omega
    have hb : L - 1 + 1 = L := by omega
    have ⟨_, _, hmask⟩ := valid_mask_intro (2 ^ L - 1) (L - 1) (by rw [hb]) (by omega)
    exact hvd (by scalar_tac) (by scalar_tac) (by convert hmask using 2 <;> scalar_tac)


end binary_tree.array_representation.treemath
end openmls
