-- [openmls]: value triples for the verification-transparent functions, monadic ok-helpers, and
-- pure companion lemmas consumed by `Proofs.lean`. Everything here is proved (no `sorry`), so the
-- file is NOT part of the trusted audit surface. Hand-written; not regenerated by extraction.
--
-- STANDING RULE (user): new companion specs of any kind require explicit user validation, and no
-- spec may be `@[spec]`-registered while its proof is still `sorry` — a registered sorried spec
-- would let `mvcgen` discharge a function's own verification condition with that function's
-- (unproved) spec, silently closing the obligation.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
import Openmls.Proofs.BitMath
import Openmls.Proofs.PartialSpecs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxRecDepth 2048

noncomputable section

namespace openmls

set_option mvcgen.warning false
set_option hax_mvcgen.warnings false

namespace binary_tree.array_representation.treemath

/-! ### Value specs for the verification-transparent functions

The Rust `to_tree_index` / `leaf_count` (and the `u32` dispatcher over them) carry no
`ensures`: they are transparent to verification — their postcondition *is* their one-line body.
Each carries exactly ONE `@[spec]` registration, the value-carrying mvcgen triple below. The
`partialSpec` proof combinators they use live in `PartialSpecs.lean`. -/

/-- `LeafNodeIndex::to_tree_index` is `self * 2`. **Fallible:** the multiplication overflows when
`2·self > u32::MAX`, so the contract carries a `willFail Error.integerOverflow` hypothesis — in
hypothesis position the bound is recovered rather than discharged. -/
@[spec]
theorem LeafNodeIndex.to_tree_index_mvcgen_spec (self : LeafNodeIndex)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = 2 * (↑self : Nat) → Aeneas.Std.willYield r Q)
    (h_fail : Std.UScalar.max .U32 < 2 * (↑self : Nat) →
      Aeneas.Std.willFail Aeneas.Std.Error.integerOverflow Q) :
    ⦃ ⌜ True ⌝ ⦄ LeafNodeIndex.to_tree_index self ⦃ Q ⦄ := by
  have h2u : ((2#u32 : Std.U32) : Nat) = 2 := by scalar_tac
  unfold LeafNodeIndex.to_tree_index
  refine triple_of_partialSpec (Std.U32.mul_spec (x := self) (y := 2#u32)) Q ?_ ?_ (by simp)
  · intro r hr
    exact h_ok r (by rw [hr, h2u]; omega)
  · intro e he
    have hcase : e = Aeneas.Std.Error.integerOverflow ∧
        Std.UScalar.max .U32 < 2 * (↑self : Nat) := by
      cases e <;> simp_all; omega
    rw [hcase.1]; exact h_fail hcase.2

/-- `ParentNodeIndex::to_tree_index` is `self * 2 + 1`. **Fallible:** either the doubling or the
increment can overflow; both are covered by the single bound `2·self + 1 > u32::MAX`. -/
@[spec]
theorem ParentNodeIndex.to_tree_index_mvcgen_spec (self : ParentNodeIndex)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = 2 * (↑self : Nat) + 1 → Aeneas.Std.willYield r Q)
    (h_fail : Std.UScalar.max .U32 < 2 * (↑self : Nat) + 1 →
      Aeneas.Std.willFail Aeneas.Std.Error.integerOverflow Q) :
    ⦃ ⌜ True ⌝ ⦄ ParentNodeIndex.to_tree_index self ⦃ Q ⦄ := by
  have h1u : ((1#u32 : Std.U32) : Nat) = 1 := by scalar_tac
  have h2u : ((2#u32 : Std.U32) : Nat) = 2 := by scalar_tac
  have hp : Aeneas.Std.WP.partialSpec
      (binary_tree.array_representation.treemath.ParentNodeIndex.to_tree_index self)
      (fun r => (↑r : Nat) = 2 * (↑self : Nat) + 1)
      (fun e => e = Aeneas.Std.Error.integerOverflow ∧
        Std.UScalar.max .U32 < 2 * (↑self : Nat) + 1) False := by
    unfold ParentNodeIndex.to_tree_index
    refine partialSpec_bind_fail
      (partialSpec_weaken (Std.U32.mul_spec (x := self) (y := 2#u32))
        (fun a ha => ha) (fun e he => ?_)) ?_
    · cases e <;> simp_all; omega
    · intro m hm
      have hmv : (↑m : Nat) = 2 * (↑self : Nat) := by rw [hm, h2u]; omega
      refine partialSpec_weaken (Std.U32.add_spec (x := m) (y := 1#u32))
        (fun a ha => ?_) (fun e he => ?_)
      · rw [ha, h1u, hmv]
      · cases e <;> simp_all
  refine triple_of_partialSpec hp Q h_ok ?_ (by simp)
  intro e he
  rw [he.1]; exact h_fail he.2

/-- `TreeNodeIndex::u32` dispatches on the constructor to `to_tree_index`. **Fallible** in both
branches (the doubling can overflow). -/
@[spec]
theorem TreeNodeIndex.u32_mvcgen_spec (self : TreeNodeIndex)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (match self with
        | TreeNodeIndex.Leaf l => 2 * (↑l : Nat)
        | TreeNodeIndex.Parent p => 2 * (↑p : Nat) + 1) →
      Aeneas.Std.willYield r Q)
    (h_fail : Std.UScalar.max .U32 < (match self with
        | TreeNodeIndex.Leaf l => 2 * (↑l : Nat)
        | TreeNodeIndex.Parent p => 2 * (↑p : Nat) + 1) →
      Aeneas.Std.willFail Aeneas.Std.Error.integerOverflow Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeNodeIndex.u32 self ⦃ Q ⦄ := by
  unfold TreeNodeIndex.u32
  cases self with
  | Leaf l =>
    exact LeafNodeIndex.to_tree_index_mvcgen_spec l Q
      (fun r hr => h_ok r (by simpa using hr)) (fun h => h_fail (by simpa using h))
  | Parent p =>
    exact ParentNodeIndex.to_tree_index_mvcgen_spec p Q
      (fun r hr => h_ok r (by simpa using hr)) (fun h => h_fail (by simpa using h))

/-- `TreeSize::leaf_count` is `self / 2 + 1`. Total: the divisor is the literal `2`, and
`self / 2 + 1 ≤ 2^31` always fits a `u32`, so neither step can fail. -/
@[spec]
theorem TreeSize.leaf_count_mvcgen_spec (self : TreeSize)
    (Q : PostCond Std.U32 Aeneas.Std.Result.postShape)
    (h_ok : ∀ r : Std.U32, (↑r : Nat) = (↑self : Nat) / 2 + 1 →
      Aeneas.Std.willYield r Q) :
    ⦃ ⌜ True ⌝ ⦄ TreeSize.leaf_count self ⦃ Q ⦄ := by
  refine triple_of_partialSpec (p_fail := fun _ => False) (p_div := False) ?_ Q h_ok
    (by simp) (by simp)
  unfold TreeSize.leaf_count
  refine partialSpec_bind_fail
    (partialSpec_of_spec (Std.U32.div_spec.step_spec (x := self) (y := 2#u32) (by simp))) ?_
  intro q hq
  refine partialSpec_weaken
    (partialSpec_of_spec (Std.U32.add_spec.step_spec (x := q) (y := 1#u32) ?_)) ?_
    (fun _ he => he)
  · simp only [hq]; scalar_tac
  · intro a ha; rw [ha, hq]; scalar_tac

/-! ### Monadic helpers about the extracted functions -/

/-- Shared arithmetic for the `from_tree_index ((xn << k) + (1 << (k-1)) - 1)` tail of
    `lowest_common_ancestor`, given `loop0`'s postcondition (`2 ≤ k ≤ 30`, `xn·2^k < 2^30`):
    the two shifts don't wrap, their sum stays below `2^32`, `xn<<k` is even, and `1<<(k-1)`
    is an even value `≥ 2` (so the final `−1` is odd and positive). -/
theorem lca_tail_aux {p : Std.U32 × Std.I32} {i6 i8 : Std.U32} {i7 : Std.I32}
    (hk2 : 2 ≤ IScalar.toNat p.2) (hk30 : IScalar.toNat p.2 ≤ 30)
    (hbnd : (↑p.1 : Nat) * 2 ^ IScalar.toNat p.2 < 2 ^ 30)
    (hi6v : (↑i6 : Nat) = ↑p.1 <<< IScalar.toNat p.2 % UScalar.size UScalarTy.U32)
    (hi7 : (↑i7 : Int) = ↑p.2 - ↑(1#i32))
    (hi8v : (↑i8 : Nat) = ↑(1#u32) <<< IScalar.toNat i7 % UScalar.size UScalarTy.U32) :
    (↑i6 : Nat) + ↑i8 < 2 ^ 32 ∧ 2 ∣ (↑i6 : Nat) ∧ 2 ≤ (↑i8 : Nat) ∧ 2 ∣ (↑i8 : Nat) := by
  have hi7t1 : 1 ≤ IScalar.toNat i7 := by scalar_tac
  have hi7t : IScalar.toNat i7 ≤ 29 := by scalar_tac
  have hsz : (2 : Nat) ^ 31 < UScalar.size UScalarTy.U32 := by simp [Aeneas.Std.U32.size_eq]
  have h1u : (↑(1#u32) : Nat) = 1 := rfl
  have hi6val : (↑i6 : Nat) = ↑p.1 * 2 ^ IScalar.toNat p.2 := by
    rw [hi6v, Nat.shiftLeft_eq, Nat.mod_eq_of_lt (by omega)]
  have hi8val : (↑i8 : Nat) = 2 ^ IScalar.toNat i7 := by
    have hb : (2 : Nat) ^ IScalar.toNat i7 < UScalar.size UScalarTy.U32 :=
      lt_of_le_of_lt (Nat.pow_le_pow_right (by norm_num) (show IScalar.toNat i7 ≤ 31 by omega)) hsz
    rw [hi8v, Nat.shiftLeft_eq, h1u, one_mul, Nat.mod_eq_of_lt hb]
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [hi6val, hi8val]
    have hle : (2 : Nat) ^ IScalar.toNat i7 ≤ 2 ^ 29 := Nat.pow_le_pow_right (by norm_num) hi7t
    omega
  · rw [hi6val]; exact (dvd_pow_self 2 (by omega : IScalar.toNat p.2 ≠ 0)).mul_left _
  · rw [hi8val]
    calc (2 : Nat) = 2 ^ 1 := (pow_one 2).symm
      _ ≤ 2 ^ IScalar.toNat i7 := Nat.pow_le_pow_right (by norm_num) hi7t1
  · rw [hi8val]; exact dvd_pow_self 2 (by omega : IScalar.toNat i7 ≠ 0)

/-- Tail bound for `lowest_common_ancestor`: the returned *tree* index
    `i6 + i8 − 1 = (xn <<< k) + (1 <<< (k−1)) − 1` stays within `MAX_TREE_INDEX = 2^30 − 2`.
    Sharper than `lca_tail_aux`'s `< 2^32` no-overflow clause, and what the strengthened
    `ParentNodeIndex.from_tree_index` postcondition (`res.valid`) needs: `i6 = xn·2^k < 2^30`
    with `2^k ∣ i6` gives `i6 ≤ 2^30 − 2^k`, so `i6 + 2^(k−1) ≤ 2^30 − 2^(k−1) ≤ 2^30 − 2`. -/
theorem lca_tail_bound {p : Std.U32 × Std.I32} {i6 i8 : Std.U32} {i7 : Std.I32}
    (hk2 : 2 ≤ IScalar.toNat p.2) (hk30 : IScalar.toNat p.2 ≤ 30)
    (hbnd : (↑p.1 : Nat) * 2 ^ IScalar.toNat p.2 < 2 ^ 30)
    (hi6v : (↑i6 : Nat) = ↑p.1 <<< IScalar.toNat p.2 % UScalar.size UScalarTy.U32)
    (hi7 : (↑i7 : Int) = ↑p.2 - ↑(1#i32))
    (hi8v : (↑i8 : Nat) = ↑(1#u32) <<< IScalar.toNat i7 % UScalar.size UScalarTy.U32) :
    (↑i6 : Nat) + ↑i8 ≤ 2 ^ 30 - 1 := by
  have hi7t1 : 1 ≤ IScalar.toNat i7 := by scalar_tac
  have hi7t : IScalar.toNat i7 ≤ 29 := by scalar_tac
  have hksucc : IScalar.toNat p.2 = IScalar.toNat i7 + 1 := by scalar_tac
  have hsz : (2 : Nat) ^ 31 < UScalar.size UScalarTy.U32 := by simp [Aeneas.Std.U32.size_eq]
  have hi6val : (↑i6 : Nat) = ↑p.1 * 2 ^ IScalar.toNat p.2 := by
    rw [hi6v, Nat.shiftLeft_eq, Nat.mod_eq_of_lt (by omega)]
  have hi8val : (↑i8 : Nat) = 2 ^ IScalar.toNat i7 := by
    have hb : (2 : Nat) ^ IScalar.toNat i7 < UScalar.size UScalarTy.U32 :=
      lt_of_le_of_lt (Nat.pow_le_pow_right (by norm_num) (show IScalar.toNat i7 ≤ 31 by omega)) hsz
    rw [hi8v, Nat.shiftLeft_eq, show ((1#u32 : Std.U32) : Nat) = 1 from rfl, one_mul,
      Nat.mod_eq_of_lt hb]
  have hpow : (2 : Nat) ^ 30 = 2 ^ (30 - IScalar.toNat p.2) * 2 ^ IScalar.toNat p.2 := by
    rw [← Nat.pow_add]; congr 1; omega
  have hxn : (↑p.1 : Nat) < 2 ^ (30 - IScalar.toNat p.2) := by
    rw [hpow] at hbnd; exact Nat.lt_of_mul_lt_mul_right hbnd
  have hstep : ((↑p.1 : Nat) + 1) * 2 ^ IScalar.toNat p.2 ≤ 2 ^ 30 := by
    rw [hpow]; exact Nat.mul_le_mul_right _ hxn
  rw [add_mul, one_mul, ← hi6val] at hstep
  have hsplit : (2 : Nat) ^ IScalar.toNat p.2 = 2 ^ IScalar.toNat i7 * 2 := by
    rw [hksucc, pow_succ]
  have h2t : (2 : Nat) ≤ 2 ^ IScalar.toNat i7 := by
    calc (2 : Nat) = 2 ^ 1 := (pow_one 2).symm
      _ ≤ 2 ^ IScalar.toNat i7 := Nat.pow_le_pow_right (by norm_num) hi7t1
  rw [hi8val]
  omega

/-- On a tree index `xv = 2·xn` the `level` call returns `0`, so the `k+1` shift amount that
    `lowest_common_ancestor` compares is exactly `1` and shifting by it recovers the leaf index
    `xn`. This is what makes all early-return branches unreachable: both tests degenerate to
    `xn = yn`, which the precondition rules out. -/
theorem lca_level_one {xn : Nat} {xv : Std.U32} {k k1 : Std.Usize}
    (hxv : (↑xv : Nat) = xn * (↑(2#u32) : Nat))
    (hk : (↑k : Nat) ≤ 30 ∧ (↑xv : Nat) % 2 ^ ((↑k : Nat) + 1) = 2 ^ (↑k : Nat) - 1)
    (hk1 : (↑k1 : Nat) = ↑k + (↑(1#usize) : Nat)) :
    (↑k1 : Nat) = 1 ∧ (↑xv : Nat) >>> (↑k1 : Nat) = xn := by
  have h2 : (↑(2#u32) : Nat) = 2 := rfl
  have h1 : (↑(1#usize) : Nat) = 1 := rfl
  have hev : (↑xv : Nat) % 2 = 0 := by rw [hxv, h2]; omega
  have hk0 : (↑k : Nat) = 0 := level_res_eq_zero hev hk.2
  have hk1' : (↑k1 : Nat) = 1 := by rw [hk1, hk0, h1]
  refine ⟨hk1', ?_⟩
  rw [hk1', hxv, h2, Nat.shiftRight_eq_div_pow, pow_one]
  omega

/-- Collision of the two shifted leaf recoveries is absurd: on even tree indices both `level`s
    are `0`, so equal shifted values force equal leaf indices, contradicting distinctness. Closes
    each of `lowest_common_ancestor`'s four early-return contradiction blocks with one `exact`. -/
theorem lca_shift_ne {xn yn : Nat} {xv yv sx sy : Std.U32} {k1 : Std.Usize}
    (heq : sx = sy) (hxy : ¬ xn = yn)
    (hxv : (↑xv : Nat) = xn * (↑(2#u32) : Nat))
    (hyv : (↑yv : Nat) = yn * (↑(2#u32) : Nat))
    (hk1 : (↑k1 : Nat) = 1)
    (hsx : (↑sx : Nat) = (↑xv : Nat) >>> (↑k1 : Nat))
    (hsy : (↑sy : Nat) = (↑yv : Nat) >>> (↑k1 : Nat)) : False := by
  have h2 : (↑(2#u32) : Nat) = 2 := rfl
  have hxs : (↑xv : Nat) >>> (↑k1 : Nat) = xn := by
    rw [hk1, hxv, h2, Nat.shiftRight_eq_div_pow, pow_one]; omega
  have hys : (↑yv : Nat) >>> (↑k1 : Nat) = yn := by
    rw [hk1, hyv, h2, Nat.shiftRight_eq_div_pow, pow_one]; omega
  have hval : (↑sx : Nat) = ↑sy := by rw [heq]
  rw [hsx, hsy, hxs, hys] at hval
  exact hxy hval

/-- No non-final `direct_path` entry is the maximal tree's root: entry `i` has
    `tones (2·e+1) = i+1 ≤ 28` on the popped list, while the root value `2^29 − 1` has
    `tones = 29`. Feeds `sibling.pre` in `copath.spec.proof`. -/
theorem dropLast_entries_ne_max_root (l : List ParentNodeIndex)
    (hlen : l.length ≤ 29)
    (hpos : ∀ i (hi : i < l.length), tones (2 * (↑l[i] : Nat) + 1) = i + 1) :
    ∀ e ∈ l.dropLast, 2 * (↑e : Nat) + 1 ≠ 2 ^ 29 - 1 := by
  intro e he heq
  obtain ⟨i, hi, hie⟩ := List.getElem_of_mem he
  rw [List.length_dropLast] at hi
  have hi' : i < l.length := by omega
  have hle : l[i] = e := by rw [← hie, List.getElem_dropLast]
  have ht := hpos i hi'
  rw [hle, heq, tones_pow_sub_one] at ht
  omega

end binary_tree.array_representation.treemath

end openmls
