-- [openmls]: the mechanized statement-freeze check for the treemath audit surface.
-- Each theorem below certifies, by definitional unfolding alone (the proof term is nothing but
-- the corresponding hand-stated obligation theorem from `Openmls/Proofs/Proofs.lean`), that the
-- hand-written statement in `Proofs.lean` proves EXACTLY the machine-generated `<fn>.spec` Prop
-- from `Openmls/Extraction/Specs.lean` — same precondition, same triple, same postcondition.
-- Consequence: a re-extraction that changes any `<fn>.spec` makes the corresponding
-- `<fn>.spec.conformance` theorem below fail to elaborate, so the audit cannot silently drift.
-- Hand-written; not regenerated by extraction.
import Aeneas
import CoreModels
import Openmls.Extraction.Types
import Openmls.Extraction.Funs
import Openmls.Extraction.Specs
import Openmls.Proofs.Common
import Openmls.Proofs.BitMath
import Openmls.Proofs.PartialSpecs
import Openmls.Proofs.PureSpecs
import Openmls.Proofs.MissingCoreSpecs
import Openmls.Proofs.Proofs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open Result ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

noncomputable section

namespace openmls
namespace binary_tree.array_representation.treemath

/-! ## Statement freeze: hand-written obligation ≡ generated `.spec`

Each theorem is proved by the corresponding `<fn>.spec.proof` term applied to the same arguments,
with no tactics and no unfolding lemmas: elaboration succeeds only if the hand-written statement in
`Proofs.lean` is definitionally the generated `<fn>.spec` Prop. These theorems carry NO attributes —
in particular they are not `@[spec]`-registered, so they take no part in mvcgen's spec resolution and
cannot perturb any proof in `Proofs.lean`. -/

theorem root.spec.conformance (size : TreeSize) : root.spec size :=
  root.spec.proof size

theorem left.spec.conformance (index : ParentNodeIndex) : left.spec index :=
  left.spec.proof index

theorem right.spec.conformance (index : ParentNodeIndex) : right.spec index :=
  right.spec.proof index

theorem parent.spec.conformance (x : TreeNodeIndex) : parent.spec x :=
  parent.spec.proof x

theorem sibling.spec.conformance (index : TreeNodeIndex) : sibling.spec index :=
  sibling.spec.proof index

theorem direct_path.spec.conformance (node_index : LeafNodeIndex) (size : TreeSize) :
    direct_path.spec node_index size :=
  direct_path.spec.proof node_index size

theorem copath.spec.conformance (leaf_index : LeafNodeIndex) (size : TreeSize) :
    copath.spec leaf_index size :=
  copath.spec.proof leaf_index size

theorem lowest_common_ancestor.spec.conformance (x : LeafNodeIndex) (y : LeafNodeIndex) :
    lowest_common_ancestor.spec x y :=
  lowest_common_ancestor.spec.proof x y

theorem common_direct_path.spec.conformance (x : LeafNodeIndex) (y : LeafNodeIndex)
    (size : TreeSize) : common_direct_path.spec x y size :=
  common_direct_path.spec.proof x y size

-- `is_node_in_tree` has NO conformance theorem by design: the Rust function is now total
-- (no `requires`, no `ensures`), so `Specs.lean` declares no `is_node_in_tree.spec` to freeze
-- and `ProofObligations.lean` carries no obligation for it.  Its panic-freedom is stated
-- and proved by hand as `is_node_in_tree.no_panic` in `Proofs.lean`.  Do not invent a
-- conformance theorem here for a spec that does not exist.

theorem LeafNodeIndex.new.spec.conformance (index : Std.U32) : LeafNodeIndex.new.spec index :=
  LeafNodeIndex.new.spec.proof index

theorem LeafNodeIndex.to_tree_index.spec.conformance (self : LeafNodeIndex) :
    LeafNodeIndex.to_tree_index.spec self :=
  LeafNodeIndex.to_tree_index.spec.proof self

theorem LeafNodeIndex.from_tree_index.spec.conformance (node_index : Std.U32) :
    LeafNodeIndex.from_tree_index.spec node_index :=
  LeafNodeIndex.from_tree_index.spec.proof node_index

theorem ParentNodeIndex.new.spec.conformance (index : Std.U32) :
    ParentNodeIndex.new.spec index :=
  ParentNodeIndex.new.spec.proof index

theorem ParentNodeIndex.to_tree_index.spec.conformance (self : ParentNodeIndex) :
    ParentNodeIndex.to_tree_index.spec self :=
  ParentNodeIndex.to_tree_index.spec.proof self

theorem ParentNodeIndex.from_tree_index.spec.conformance (node_index : Std.U32) :
    ParentNodeIndex.from_tree_index.spec node_index :=
  ParentNodeIndex.from_tree_index.spec.proof node_index

theorem TreeNodeIndex.new.spec.conformance (index : Std.U32) : TreeNodeIndex.new.spec index :=
  TreeNodeIndex.new.spec.proof index

theorem TreeNodeIndex.u32.spec.conformance (self : TreeNodeIndex) : TreeNodeIndex.u32.spec self :=
  TreeNodeIndex.u32.spec.proof self

theorem TreeSize.new.spec.conformance (nodes : Std.U32) : TreeSize.new.spec nodes :=
  TreeSize.new.spec.proof nodes

theorem TreeSize.inc.spec.conformance (self : TreeSize) : TreeSize.inc.spec self :=
  TreeSize.inc.spec.proof self

theorem TreeSize.dec.spec.conformance (self : TreeSize) : TreeSize.dec.spec self :=
  TreeSize.dec.spec.proof self

end binary_tree.array_representation.treemath
end openmls
