name: Build

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - konrad/treesync
  pull_request:
    branches:
      - main
      - konrad/treesync
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          # Windows
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
          # macOS
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          # Linux
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          # Android
          - aarch64-linux-android
          - armv7-linux-androideabi
          - x86_64-linux-android
          - i686-linux-android
          # iOS
          - aarch64-apple-ios
          # WASM
          - wasm32-unknown-unknown
        include:
          # Compile iOS sim on macOS
          - os: macos-latest
            arch: aarch64-apple-ios-sim
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install the required target
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.arch }}
      - name: Build debug
        run: cargo build --verbose --target ${{ matrix.arch }} -p openmls
      - name: Build release
        run: cargo build --release --verbose --target ${{ matrix.arch }} -p openmls
