on: [push, pull_request]

defaults:
  run:
    working-directory: openmls

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint package
    steps:
      - uses: actions/checkout@v2
      - uses: qernal/github-actions-rust-clippy@v1.4.0
        with:
          clippy-args: --manifest-path openmls/Cargo.toml