name: Spot Fuzz

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'book/**'
      - 'LICENSE*'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'book/**'
      - 'LICENSE*'
      - '.gitignore'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  fuzz:
    strategy:
      fail-fast: false
      matrix:
        tests:
          - welcome_decode
          - key_package_decode
          - mls_message_decode
          - proposal_decode
          - welcome_decode_bytes
          - key_package_decode_bytes
          - mls_message_decode_bytes
          - proposal_decode_bytes
          - extension_decode_bytes
        include:
          - tests: welcome_decode
            runs: 10000
          - tests: key_package_decode
            runs: 50000
          - tests: mls_message_decode
            runs: 50000
          - tests: proposal_decode
            runs: 50000
          - tests: welcome_decode_bytes
            runs: 10000
          - tests: key_package_decode_bytes
            runs: 50000
          - tests: mls_message_decode_bytes
            runs: 50000
          - tests: proposal_decode_bytes
            runs: 50000
          - tests: extension_decode_bytes
            runs: 50000
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-fuzz
          version: latest
      - run: cargo fuzz run ${{ matrix.tests }} -- -runs=${{ matrix.runs }}
