name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: openmls

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Release
        run: cargo build --release --verbose
      - name: Test Release
        run: cargo test --release --verbose
      - name: Build Release w/ Evercrypt
        run: cargo build --release --verbose --no-default-features --features="evercrypt-backend"
